# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

import copy
from dataclasses import dataclass
import gzip
import hashlib
import io
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import stat
import subprocess
import tarfile
import tempfile

from .distributions import DistributionCatalog, DistributionTarget, load_distribution_catalog
from .distribution_native import (
    NativePackageContext,
    normalize_tree as _normalize,
    tree_digest as _tree_digest,
    tree_files as _tree_files,
    write_payload_tar as _tar_payload,
)
from .linux_runtime import LinuxRuntime, load_linux_runtime
from .model import ModelError, sha256_file
from .package_pipeline import ArtifactSet, StageResult, load_artifact_set, stage_rootfs


BUILD_MANIFEST_NAME = "distribution-package-build-manifest.json"
CANONICAL_ARCH_BUILD_ROOT = "/build/hyperflux-next"
CANONICAL_ARCH_PACKAGER = "HyperFlux Next Build System <build@hyperflux.invalid>"
INSTALLED_MANIFEST_PATH = PurePosixPath(
    "/usr/share/hyperflux-next/distribution-package.json"
)
ARCH_POST_TRANSACTION_HOOK = PurePosixPath(
    "/usr/share/libalpm/hooks/95-hyperflux-next-post-transaction.hook"
)


@dataclass(frozen=True)
class DistributionPackageResult:
    package: Path
    manifest: Path
    distribution: str
    architecture: str
    common_payload_sha256: str
    distribution_payload_sha256: str


def _new_output_directory(path: Path) -> Path:
    path = path.resolve()
    if path in {Path("/"), Path.home()}:
        raise ModelError("distribution package: refusing unsafe output directory")
    if path.exists():
        if not path.is_dir() or path.is_symlink() or any(path.iterdir()):
            raise ModelError("distribution package: output directory must be absent or empty")
    else:
        path.mkdir(parents=True)
    return path


def _stage_path(root: Path, destination: str | PurePosixPath) -> Path:
    path = PurePosixPath(destination)
    if not path.is_absolute() or len(path.parts) < 2 or path.parts[1] not in {"etc", "usr"}:
        raise ModelError(f"unsafe distribution payload destination: {destination}")
    return root.joinpath(*path.parts[1:])


def _write_overlay(root: Path, destination: str | PurePosixPath, content: str) -> Path:
    path = _stage_path(root, destination)
    if path.exists() or path.is_symlink():
        raise ModelError(f"distribution payload collision: {destination}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(0o644)
    return path


def _installed_distribution_manifest(
    distribution: str,
    runtime: LinuxRuntime,
    artifacts: ArtifactSet,
    common: StageResult,
    target: DistributionTarget,
    architecture: str,
    overlay_paths: list[Path],
    root: Path,
) -> str:
    value = {
        "schema": "hyperflux-installed-distribution-package-v1",
        "distribution": distribution,
        "package": runtime.product.package_name,
        "version": runtime.product.version,
        "release": runtime.product.package_release,
        "architecture": architecture,
        "source_revision": artifacts.revision,
        "common_payload_sha256": common.payload_sha256,
        "python_discovery_path": target.python_discovery_for(artifacts.python),
        "overlay_files": [
            {
                "path": "/" + path.relative_to(root).as_posix(),
                "mode": f"{stat.S_IMODE(path.stat().st_mode):04o}",
                "sha256": sha256_file(path),
            }
            for path in sorted(overlay_paths)
        ],
    }
    return json.dumps(value, indent=2, ensure_ascii=True) + "\n"


def _arch_hook(runtime: LinuxRuntime) -> str:
    return "\n".join(
        [
            "[Trigger]",
            "Operation = Install",
            "Operation = Upgrade",
            "Type = Package",
            f"Target = {runtime.product.package_name}",
            "",
            "[Action]",
            "Description = Complete HyperFlux Next compatibility activation",
            "When = PostTransaction",
            f"Exec = {runtime.operations.activation_path} post-update",
            "",
        ]
    )


def _arch_install(runtime: LinuxRuntime) -> str:
    activation = runtime.operations.activation_path
    return "\n".join(
        [
            "# Generated by ./hfx package distro. Do not edit manually.",
            "# SPDX-License-Identifier: GPL-2.0-only",
            "",
            "_hyperflux_refresh_system() {",
            "  systemd-sysusers hyperflux-next.conf",
            "  systemd-tmpfiles --create hyperflux-next.conf",
            "  systemctl daemon-reload",
            "  udevadm control --reload",
            "  udevadm trigger --subsystem-match=misc --action=change",
            "}",
            "",
            "post_install() {",
            "  _hyperflux_refresh_system",
            f"  {activation} fresh-install",
            "}",
            "",
            "pre_upgrade() {",
            f"  {activation} pre-update",
            "}",
            "",
            "post_upgrade() {",
            "  _hyperflux_refresh_system",
            "}",
            "",
            "pre_remove() {",
            f"  {activation} pre-remove",
            "}",
            "",
            "post_remove() {",
            "  systemctl daemon-reload",
            "  udevadm control --reload",
            "}",
            "",
        ]
    )


def _shell_word(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def _shell_array(values: tuple[str, ...] | list[str]) -> str:
    return "(" + " ".join(_shell_word(item) for item in values) + ")"


def _arch_version(version: str) -> str:
    value = version.replace("-", "_")
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9.+_]*", value):
        raise ModelError("Arch package version cannot be represented safely")
    return value


def _arch_pkgbuild(
    runtime: LinuxRuntime,
    catalog: DistributionCatalog,
    target: DistributionTarget,
    architecture: str,
    python_version: str,
    payload_sha256: str,
) -> str:
    optional = [
        f"{item.package}: {item.purpose}" for item in target.optional_dependencies
    ]
    return "\n".join(
        [
            "# Generated by ./hfx package distro. Do not edit manually.",
            "# SPDX-License-Identifier: GPL-2.0-only",
            f"pkgname={runtime.product.package_name}",
            f"pkgver={_arch_version(runtime.product.version)}",
            f"pkgrel={runtime.product.package_release}",
            f"pkgdesc={_shell_word(catalog.description)}",
            f"arch={_shell_array([architecture])}",
            "url=''",
            f"license={_shell_array(list(catalog.licenses))}",
            f"depends={_shell_array(list(target.dependencies_for(python_version)))}",
            f"optdepends={_shell_array(optional)}",
            f"conflicts={_shell_array(list(target.conflicts))}",
            "backup=('etc/hyperflux-next/bridge.json')",
            "options=('!strip' '!debug')",
            "install=hyperflux-next.install",
            "source=('payload.tar')",
            "noextract=('payload.tar')",
            f"sha256sums=('{payload_sha256}')",
            "",
            "package() {",
            "  bsdtar -xf \"$srcdir/payload.tar\" -C \"$pkgdir\"",
            "}",
            "",
        ]
    )


def _canonical_arch_buildinfo(content: bytes) -> bytes:
    try:
        lines = content.decode("utf-8").splitlines()
    except UnicodeDecodeError as error:
        raise ModelError("Arch package BUILDINFO is not UTF-8") from error
    replacements = {"builddir": 0, "startdir": 0}
    result = []
    for line in lines:
        key, separator, _value = line.partition(" = ")
        if separator and key in replacements:
            replacements[key] += 1
            result.append(f"{key} = {CANONICAL_ARCH_BUILD_ROOT}")
        else:
            result.append(line)
    if replacements != {"builddir": 1, "startdir": 1}:
        raise ModelError("Arch package BUILDINFO path fields are incomplete")
    return ("\n".join(result) + "\n").encode("utf-8")


def _canonical_arch_mtree(
    entries: list[tuple[tarfile.TarInfo, bytes | None]], epoch: int
) -> bytes:
    lines = ["#mtree"]
    names: set[str] = set()
    for member, content in sorted(
        entries, key=lambda item: PurePosixPath(item[0].name).as_posix()
    ):
        name = PurePosixPath(member.name).as_posix()
        if name == ".MTREE":
            continue
        if (
            name in {"", "."}
            or name in names
            or not re.fullmatch(r"[A-Za-z0-9._+@%/=-]+", name)
        ):
            raise ModelError("Arch package contains a path that cannot be inventoried")
        names.add(name)
        kind = "dir" if member.isdir() else "file"
        fields = [
            f"./{name}",
            f"type={kind}",
            "uid=0",
            "gid=0",
            f"mode={member.mode:o}",
            f"time={epoch}.0",
        ]
        if member.isfile():
            if content is None:
                raise ModelError("Arch package inventory file has no content")
            fields.extend(
                [
                    f"size={len(content)}",
                    f"sha256digest={hashlib.sha256(content).hexdigest()}",
                ]
            )
        elif content is not None:
            raise ModelError("Arch package inventory directory has content")
        lines.append(" ".join(fields))
    uncompressed = ("\n".join(lines) + "\n").encode("utf-8")
    compressed = io.BytesIO()
    with gzip.GzipFile(
        filename="", mode="wb", compresslevel=9, fileobj=compressed, mtime=0
    ) as stream:
        stream.write(uncompressed)
    return compressed.getvalue()


def _canonicalize_arch_package(package: Path, epoch: int) -> None:
    tar_descriptor, tar_name = tempfile.mkstemp(
        prefix="hyperflux-arch-canonical-", suffix=".tar", dir=package.parent
    )
    compressed_descriptor, compressed_name = tempfile.mkstemp(
        prefix="hyperflux-arch-canonical-", suffix=".pkg.tar.zst", dir=package.parent
    )
    os.close(tar_descriptor)
    os.close(compressed_descriptor)
    tar_path = Path(tar_name)
    compressed_path = Path(compressed_name)
    try:
        entries: list[tuple[tarfile.TarInfo, bytes | None]] = []
        names: set[str] = set()
        with tarfile.open(package, "r:*") as source:
            members = source.getmembers()
            if not members or len(members) > 10000:
                raise ModelError("Arch package member count is invalid")
            for original in members:
                path = PurePosixPath(original.name)
                canonical_name = path.as_posix()
                if (
                    path.is_absolute()
                    or ".." in path.parts
                    or canonical_name in names
                ):
                    raise ModelError("Arch package contains an unsafe or duplicate member")
                names.add(canonical_name)
                if not (original.isdir() or original.isfile()):
                    raise ModelError("Arch package contains an unsupported member type")
                member = copy.copy(original)
                member.name = canonical_name + ("/" if original.isdir() else "")
                member.uid = 0
                member.gid = 0
                member.uname = "root"
                member.gname = "root"
                member.mtime = epoch
                member.pax_headers = {}
                if member.isdir():
                    member.size = 0
                    entries.append((member, None))
                    continue
                stream = source.extractfile(original)
                if stream is None:
                    raise ModelError("Arch package regular file has no content")
                content = stream.read()
                if original.name == ".BUILDINFO":
                    content = _canonical_arch_buildinfo(content)
                member.size = len(content)
                entries.append((member, content))
        canonical_mtree = _canonical_arch_mtree(entries, epoch)
        mtree_count = 0
        canonical_entries = []
        for member, content in entries:
            if PurePosixPath(member.name).as_posix() == ".MTREE":
                content = canonical_mtree
                member.size = len(content)
                mtree_count += 1
            canonical_entries.append((member, content))
        if mtree_count != 1:
            raise ModelError("Arch package must contain exactly one MTREE inventory")
        with tarfile.open(tar_path, "w", format=tarfile.GNU_FORMAT) as destination:
            for member, content in sorted(
                canonical_entries,
                key=lambda item: PurePosixPath(item[0].name).as_posix(),
            ):
                if content is None:
                    destination.addfile(member)
                else:
                    destination.addfile(member, io.BytesIO(content))
        result = subprocess.run(
            [
                "zstd",
                "--quiet",
                "--force",
                "--threads=1",
                "-19",
                "-o",
                str(compressed_path),
                str(tar_path),
            ],
            check=False,
            timeout=300,
        )
        if result.returncode != 0:
            raise ModelError(
                "Arch package canonical compression failed "
                f"with exit status {result.returncode}"
            )
        compressed_path.chmod(0o644)
        os.utime(compressed_path, (epoch, epoch))
        os.replace(compressed_path, package)
    except (OSError, subprocess.TimeoutExpired, tarfile.TarError) as error:
        raise ModelError(f"Arch package canonicalization failed: {error}") from error
    finally:
        tar_path.unlink(missing_ok=True)
        compressed_path.unlink(missing_ok=True)


def _arch_metadata(content: bytes, label: str) -> dict[str, tuple[str, ...]]:
    try:
        lines = content.decode("utf-8").splitlines()
    except UnicodeDecodeError as error:
        raise ModelError(f"Arch package {label} is not UTF-8") from error
    values: dict[str, list[str]] = {}
    for line in lines:
        if not line or line.startswith("#"):
            continue
        key, separator, value = line.partition(" = ")
        if not separator or not key:
            raise ModelError(f"Arch package {label} contains a malformed field")
        values.setdefault(key, []).append(value)
    return {key: tuple(items) for key, items in values.items()}


def _one_arch_value(
    metadata: dict[str, tuple[str, ...]], key: str, label: str
) -> str:
    values = metadata.get(key, ())
    if len(values) != 1:
        raise ModelError(f"Arch package {label} must contain exactly one {key}")
    return values[0]


def _verify_arch_package(
    package: Path,
    root: Path,
    runtime: LinuxRuntime,
    catalog: DistributionCatalog,
    target: DistributionTarget,
    artifacts: ArtifactSet,
    architecture: str,
    payload_sha256: str,
    payload_file_count: int,
) -> None:
    metadata_files: dict[str, bytes] = {}
    archive_entries: list[tuple[tarfile.TarInfo, bytes | None]] = []
    digest = hashlib.sha256()
    payload_files = 0
    forbidden = tuple(
        item.encode("utf-8")
        for item in {str(root), str(Path.home()), "/tmp/hyperflux-"}
        if len(item) > 1
    )
    try:
        with tarfile.open(package, "r:*") as archive:
            members = archive.getmembers()
            names = [member.name for member in members]
            if len(names) != len(set(names)):
                raise ModelError("Arch package contains duplicate members")
            if names != sorted(names, key=lambda name: PurePosixPath(name).as_posix()):
                raise ModelError("Arch package members are not in canonical order")
            for member in members:
                path = PurePosixPath(member.name)
                if path.is_absolute() or ".." in path.parts:
                    raise ModelError("Arch package contains an unsafe member path")
                if member.isdir():
                    if (
                        member.uid != 0
                        or member.gid != 0
                        or member.mtime != artifacts.source_date_epoch
                    ):
                        raise ModelError("Arch package directory metadata is not canonical")
                    archive_entries.append((copy.copy(member), None))
                    continue
                if not member.isfile():
                    raise ModelError("Arch package contains an unsupported member type")
                stream = archive.extractfile(member)
                if stream is None:
                    raise ModelError("Arch package regular file has no content")
                content = stream.read()
                if (
                    member.uid != 0
                    or member.gid != 0
                    or member.mtime != artifacts.source_date_epoch
                ):
                    raise ModelError("Arch package file metadata is not canonical")
                archive_entries.append((copy.copy(member), content))
                if any(value in content for value in forbidden):
                    raise ModelError("Arch package contains a private or temporary build path")
                if member.name.startswith("."):
                    metadata_files[member.name] = content
                    continue
                payload_files += 1
                digest.update(member.name.encode("utf-8"))
                digest.update(b"\0")
                digest.update(f"{member.mode:04o}".encode("ascii"))
                digest.update(b"\0")
                digest.update(hashlib.sha256(content).digest())
    except (OSError, tarfile.TarError) as error:
        raise ModelError(f"cannot verify Arch package: {error}") from error
    required_metadata = {".BUILDINFO", ".INSTALL", ".MTREE", ".PKGINFO"}
    if set(metadata_files) != required_metadata:
        raise ModelError("Arch package metadata members are incomplete or unexpected")
    if metadata_files[".MTREE"] != _canonical_arch_mtree(
        archive_entries, artifacts.source_date_epoch
    ):
        raise ModelError("Arch package MTREE does not describe the canonical archive")
    if payload_files != payload_file_count or digest.hexdigest() != payload_sha256:
        raise ModelError("Arch package payload differs from the staged distribution root")
    if metadata_files[".INSTALL"] != _arch_install(runtime).encode("utf-8"):
        raise ModelError("Arch package install script differs from the lifecycle contract")

    package_info = _arch_metadata(metadata_files[".PKGINFO"], "PKGINFO")
    expected_version = f"{_arch_version(runtime.product.version)}-{runtime.product.package_release}"
    singles = {
        "pkgname": runtime.product.package_name,
        "pkgver": expected_version,
        "pkgdesc": catalog.description,
        "arch": architecture,
        "packager": CANONICAL_ARCH_PACKAGER,
        "builddate": str(artifacts.source_date_epoch),
    }
    for key, expected in singles.items():
        if _one_arch_value(package_info, key, "PKGINFO") != expected:
            raise ModelError(f"Arch package PKGINFO {key} does not match its authority")
    repeated = {
        "license": catalog.licenses,
        "depend": target.dependencies_for(artifacts.python),
        "optdepend": tuple(
            f"{item.package}: {item.purpose}" for item in target.optional_dependencies
        ),
        "conflict": target.conflicts,
        "backup": ("etc/hyperflux-next/bridge.json",),
    }
    for key, expected in repeated.items():
        if package_info.get(key, ()) != expected:
            raise ModelError(f"Arch package PKGINFO {key} does not match its authority")

    build_info = _arch_metadata(metadata_files[".BUILDINFO"], "BUILDINFO")
    for key, expected in {
        "pkgname": runtime.product.package_name,
        "pkgver": expected_version,
        "pkgarch": architecture,
        "packager": CANONICAL_ARCH_PACKAGER,
        "builddate": str(artifacts.source_date_epoch),
        "builddir": CANONICAL_ARCH_BUILD_ROOT,
        "startdir": CANONICAL_ARCH_BUILD_ROOT,
    }.items():
        if _one_arch_value(build_info, key, "BUILDINFO") != expected:
            raise ModelError(f"Arch package BUILDINFO {key} does not match its authority")


def _run_makepkg(workspace: Path, packages: Path, epoch: int) -> None:
    environment = os.environ.copy()
    environment.update(
        {
            "SOURCE_DATE_EPOCH": str(epoch),
            "PKGDEST": str(packages),
            "SRCDEST": str(workspace / "source-cache"),
            "BUILDDIR": str(workspace / "makepkg-build"),
            "PACKAGER": CANONICAL_ARCH_PACKAGER,
        }
    )
    try:
        result = subprocess.run(
            ["makepkg", "--cleanbuild", "--force", "--nodeps", "--noconfirm"],
            cwd=workspace,
            env=environment,
            check=False,
            timeout=300,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise ModelError(f"Arch package build failed: {error}") from error
    if result.returncode != 0:
        raise ModelError(f"Arch package build failed with exit status {result.returncode}")


def _build_arch_package(context: NativePackageContext) -> Path:
    workspace = context.workspace_root / "makepkg"
    workspace.mkdir()
    payload = workspace / "payload.tar"
    _tar_payload(context.package_root, payload, context.artifacts.source_date_epoch)
    (workspace / "hyperflux-next.install").write_text(
        _arch_install(context.runtime), encoding="utf-8"
    )
    (workspace / "PKGBUILD").write_text(
        _arch_pkgbuild(
            context.runtime,
            context.catalog,
            context.target,
            context.architecture,
            context.artifacts.python,
            sha256_file(payload),
        ),
        encoding="utf-8",
    )
    for path in (workspace / "PKGBUILD", workspace / "hyperflux-next.install"):
        path.chmod(0o644)
        os.utime(
            path,
            (
                context.artifacts.source_date_epoch,
                context.artifacts.source_date_epoch,
            ),
        )
    _run_makepkg(workspace, context.packages, context.artifacts.source_date_epoch)
    built = sorted(context.packages.glob("*.pkg.tar.*"))
    if len(built) != 1 or not built[0].is_file() or built[0].is_symlink():
        raise ModelError("Arch package build did not produce exactly one package")
    package = built[0]
    _canonicalize_arch_package(package, context.artifacts.source_date_epoch)
    _verify_arch_package(
        package,
        context.repository_root,
        context.runtime,
        context.catalog,
        context.target,
        context.artifacts,
        context.architecture,
        context.payload_sha256,
        context.payload_file_count,
    )
    return package


def _backend_overlays(
    distribution: str, runtime: LinuxRuntime
) -> tuple[tuple[PurePosixPath, str], ...]:
    if distribution == "arch":
        return ((ARCH_POST_TRANSACTION_HOOK, _arch_hook(runtime)),)
    if distribution in {"debian", "rpm"}:
        return ()
    raise ModelError(f"unknown distribution package target {distribution}")


def _build_native_package(
    distribution: str, context: NativePackageContext
) -> Path:
    if distribution == "arch":
        return _build_arch_package(context)
    if distribution == "debian":
        from .distribution_debian import build_debian_package

        return build_debian_package(context)
    if distribution == "rpm":
        from .distribution_rpm import build_rpm_package

        return build_rpm_package(context)
    raise ModelError(f"unknown distribution package target {distribution}")


def build_distribution_package(
    root: Path,
    build_manifest: Path,
    distribution: str,
    output: Path,
) -> DistributionPackageResult:
    root = root.resolve()
    output = _new_output_directory(output)
    runtime = load_linux_runtime(root)
    catalog = load_distribution_catalog(root)
    if distribution not in catalog.targets:
        raise ModelError(f"unknown distribution package target {distribution}")
    target = catalog.targets[distribution]
    artifacts = load_artifact_set(root, build_manifest)
    architecture = target.architecture_for(artifacts.target)
    packages = output / "packages"
    packages.mkdir()

    with tempfile.TemporaryDirectory(
        prefix=f"hyperflux-{distribution}-package-"
    ) as temporary:
        workspace_root = Path(temporary)
        common_root = workspace_root / "common-root"
        common = stage_rootfs(root, build_manifest, common_root)
        package_root = workspace_root / "package-root"
        shutil.copytree(common.root, package_root, symlinks=False)
        overlays = [
            _write_overlay(
                package_root,
                target.python_discovery_for(artifacts.python),
                runtime.operations.python_module_directory + "\n",
            )
        ]
        overlays.extend(
            _write_overlay(package_root, destination, content)
            for destination, content in _backend_overlays(distribution, runtime)
        )
        installed_manifest = _write_overlay(
            package_root,
            INSTALLED_MANIFEST_PATH,
            _installed_distribution_manifest(
                distribution,
                runtime,
                artifacts,
                common,
                target,
                architecture,
                overlays,
                package_root,
            ),
        )
        overlays.append(installed_manifest)
        _normalize(package_root, artifacts.source_date_epoch)
        distribution_files = _tree_files(package_root)
        distribution_digest = _tree_digest(package_root, distribution_files)

        package = _build_native_package(
            distribution,
            NativePackageContext(
                repository_root=root,
                workspace_root=workspace_root,
                package_root=package_root,
                packages=packages,
                runtime=runtime,
                catalog=catalog,
                target=target,
                artifacts=artifacts,
                architecture=architecture,
                payload_sha256=distribution_digest,
                payload_file_count=len(distribution_files),
            ),
        )
    manifest_value = {
        "$schema": "https://hyperflux.dev/schemas/distribution-package-build-v1.json",
        "schema": "hyperflux-distribution-package-build-v1",
        "source": {
            "revision": artifacts.revision,
            "source_date_epoch": artifacts.source_date_epoch,
            "distribution_catalog_sha256": catalog.source_sha256,
        },
        "package": {
            "distribution": distribution,
            "name": runtime.product.package_name,
            "version": runtime.product.version,
            "release": runtime.product.package_release,
            "architecture": architecture,
            "file": package.name,
            "sha256": sha256_file(package),
            "size": package.stat().st_size,
        },
        "payload": {
            "common_sha256": common.payload_sha256,
            "distribution_sha256": distribution_digest,
            "common_files": common.file_count,
            "distribution_files": len(distribution_files),
        },
    }
    manifest = output / BUILD_MANIFEST_NAME
    manifest.write_text(
        json.dumps(manifest_value, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
    )
    manifest.chmod(0o644)
    os.utime(manifest, (artifacts.source_date_epoch, artifacts.source_date_epoch))
    return DistributionPackageResult(
        package=package,
        manifest=manifest,
        distribution=distribution,
        architecture=architecture,
        common_payload_sha256=common.payload_sha256,
        distribution_payload_sha256=distribution_digest,
    )
