# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

from pathlib import Path
from typing import Any

from .errors import load_error_catalog
from .generators.domain import cpp_types, markdown as domain_markdown, python_types, rust_types
from .generators.errors import (
    cpp_catalog as error_cpp_catalog,
    markdown as error_markdown,
    python_catalog as error_python_catalog,
    rust_catalog as error_rust_catalog,
)
from .generators.profiles import (
    compiled_json as profile_compiled_json,
    cpp_catalog as profile_cpp_catalog,
    fixtures_json as profile_fixtures_json,
    kernel_receiver_table,
    markdown as profile_markdown,
    python_catalog as profile_python_catalog,
    rust_catalog as profile_rust_catalog,
)
from .generators.protocol import (
    cpp_types as protocol_cpp_types,
    markdown as protocol_markdown,
    python_types as protocol_python_types,
    rust_types as protocol_rust_types,
    rust_registry as protocol_rust_registry,
)
from .model import load_foundation, load_json
from .profiles import compiled_catalog, composition_fixtures
from .protocol import load_protocol_registry
from .testgraph import load_test_catalog, markdown as testgraph_markdown


GENERATED_NOTICE = "> Generated by `./hfx generate`. Do not edit manually.\n"


def architecture_markdown(constitution: dict[str, Any]) -> str:
    lines = [
        "# Architecture Constitution",
        "",
        GENERATED_NOTICE.rstrip(),
        "",
        f"Product phase: **{constitution['phase']}**",
        "",
        "## Direction Of Responsibility",
        "",
        "```mermaid",
        "flowchart TB",
    ]
    direction = constitution["direction"]
    for component in direction:
        lines.append(f'    {component}["{component.title()}"]')
    for left, right in zip(direction, direction[1:]):
        lines.append(f"    {left} --> {right}")
    lines.extend(["```", "", "## Invariants", ""])
    for invariant in constitution["invariants"]:
        lines.append(f"- `{invariant['id']}` {invariant['statement']}")
    lines.extend(["", "## Component Ownership", ""])
    for component in constitution["components"]:
        owns = ", ".join(component["owns"])
        forbidden = ", ".join(component["must_not_own"])
        lines.extend(
            [
                f"### {component['id'].replace('-', ' ').title()}",
                "",
                f"Owns: {owns}.",
                "",
                f"Must not own: {forbidden}.",
                "",
            ]
        )
    interlock = constitution["publication_interlock"]
    lines.extend(
        [
            "## Publication Interlock",
            "",
            f"Remote repository created: **{str(interlock['remote_repository_created']).lower()}**",
            "",
            f"Publication authorized: **{str(interlock['publication_authorized']).lower()}**",
            "",
            "Required gates:",
            "",
        ]
    )
    lines.extend(f"- `{gate}`" for gate in interlock["required_gate_ids"])
    return "\n".join(lines) + "\n"


def migration_markdown(sources: dict[str, Any], ledger: dict[str, Any]) -> str:
    source_roles = {source["id"]: source["role"] for source in sources["sources"]}
    lines = [
        "# Migration Ledger",
        "",
        GENERATED_NOTICE.rstrip(),
        "",
        f"Default disposition: `{ledger['default_disposition']}`.",
        "",
        "| ID | Component | Decision | Status | Destination |",
        "| --- | --- | --- | --- | --- |",
    ]
    for entry in ledger["entries"]:
        lines.append(
            f"| `{entry['id']}` | {entry['component']} | `{entry['disposition']}` | "
            f"`{entry['status']}` | `{entry['destination_owner']}` |"
        )
    lines.extend(["", "## Decisions", ""])
    for entry in ledger["entries"]:
        roles = "; ".join(f"`{source}`: {source_roles[source]}" for source in entry["sources"])
        lines.extend(
            [
                f"### {entry['id']}: {entry['component'].title()}",
                "",
                entry["rationale"],
                "",
                f"Sources: {roles}.",
                "",
            ]
        )
    return "\n".join(lines) + "\n"


def rendered_files(root: Path) -> dict[Path, str]:
    constitution, sources, ledger = load_foundation(root)
    domain_catalog = load_json(root / "schemas" / "domain-catalog.json")
    profiles = compiled_catalog(root)
    profile_fixtures = composition_fixtures(root)
    protocol_registry = load_protocol_registry(root)
    protocol = protocol_registry.current
    errors = load_error_catalog(root)
    test_catalog = load_test_catalog(root)
    files = {
        root / "docs" / "generated" / "architecture.md": architecture_markdown(constitution),
        root / "docs" / "generated" / "migration-ledger.md": migration_markdown(sources, ledger),
        root / "docs" / "generated" / "domain-types.md": domain_markdown(domain_catalog),
        root / "crates" / "hfx-domain" / "src" / "generated.rs": rust_types(domain_catalog),
        root / "sdk" / "python" / "hyperflux_sdk" / "generated" / "domain_types.py": python_types(domain_catalog),
        root / "sdk" / "cpp" / "include" / "hyperflux" / "generated" / "domain_types.hpp": cpp_types(domain_catalog),
        root / "generated" / "profiles" / "catalog.json": profile_compiled_json(profiles),
        root / "tests" / "fixtures" / "generated" / "profile-compositions.json": profile_fixtures_json(profile_fixtures),
        root / "docs" / "generated" / "supported-hardware.md": profile_markdown(profiles),
        root / "crates" / "hfx-profiles" / "src" / "generated.rs": profile_rust_catalog(profiles),
        root / "sdk" / "python" / "hyperflux_sdk" / "generated" / "profile_catalog.py": profile_python_catalog(profiles),
        root / "sdk" / "cpp" / "include" / "hyperflux" / "generated" / "profile_catalog.hpp": profile_cpp_catalog(profiles),
        root / "driver" / "kernel" / "generated" / "hyperflux_receiver_profiles.inc": kernel_receiver_table(profiles),
        root / "docs" / "generated" / "verification.md": testgraph_markdown(test_catalog),
        root / "docs" / "generated" / "bridge-protocol.md": protocol_markdown(protocol),
        root / "crates" / "hfx-protocol" / "src" / "generated.rs": protocol_rust_types(protocol),
        root / "crates" / "hfx-protocol" / "src" / "generated_versions.rs": protocol_rust_registry(protocol_registry),
        root / "sdk" / "python" / "hyperflux_sdk" / "generated" / "protocol_types.py": protocol_python_types(protocol),
        root / "sdk" / "cpp" / "include" / "hyperflux" / "generated" / "protocol_types.hpp": protocol_cpp_types(protocol),
        root / "docs" / "generated" / "error-catalog.md": error_markdown(errors),
        root / "crates" / "hfx-errors" / "src" / "generated.rs": error_rust_catalog(errors),
        root / "sdk" / "python" / "hyperflux_sdk" / "generated" / "error_catalog.py": error_python_catalog(errors),
        root / "sdk" / "cpp" / "include" / "hyperflux" / "generated" / "error_catalog.hpp": error_cpp_catalog(errors),
    }
    for version in protocol_registry.versions:
        suffix = f"v{version.version}"
        files[root / "crates" / "hfx-protocol" / "src" / f"generated_{suffix}.rs"] = (
            protocol_rust_types(version.catalog)
        )
        files[
            root
            / "sdk"
            / "python"
            / "hyperflux_sdk"
            / "generated"
            / f"protocol_{suffix}_types.py"
        ] = protocol_python_types(version.catalog)
        files[
            root
            / "sdk"
            / "cpp"
            / "include"
            / "hyperflux"
            / "generated"
            / f"protocol_{suffix}_types.hpp"
        ] = protocol_cpp_types(version.catalog, namespace=f"hyperflux::{suffix}")
        files[root / "docs" / "generated" / f"bridge-protocol-{suffix}.md"] = (
            protocol_markdown(version.catalog, title=f"Bridge Protocol {suffix.upper()}")
        )
    return files


def write_generated(root: Path) -> None:
    for path, content in rendered_files(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
