# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

from pathlib import Path
import sys
import unittest


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from hfxdev.atlas import load_repository_atlas
from hfxdev.generators.atlas import folder_readme, impact_summary, markdown
from hfxdev.testgraph import load_test_catalog, select_tests


class RepositoryAtlasTests(unittest.TestCase):
    def test_graph_covers_required_subsystems_with_unique_ownership(self) -> None:
        atlas = load_repository_atlas(ROOT)
        self.assertEqual(len(atlas.nodes), 31)
        self.assertEqual(
            {node.category for node in atlas.nodes},
            {
                "architecture",
                "assurance",
                "runtime",
                "applications",
                "tooling",
                "delivery",
                "governance",
                "documentation",
            },
        )
        canonical_files = [
            path for node in atlas.nodes for path in node.canonical_files
        ]
        self.assertEqual(len(canonical_files), len(set(canonical_files)))

    def test_used_by_is_the_exact_dependency_inverse(self) -> None:
        atlas = load_repository_atlas(ROOT)
        for node in atlas.nodes:
            for dependency in node.depends_on:
                self.assertIn(node.id, atlas.used_by[dependency])
        self.assertEqual(set(atlas.used_by), set(atlas.by_id))

    def test_folder_readmes_expose_the_complete_contract(self) -> None:
        atlas = load_repository_atlas(ROOT)
        required = (
            "## Ownership",
            "## Inputs And Outputs",
            "## Public Contracts",
            "## Source And Generated Files",
            "## Relationships",
            "## Verification",
            "## Limitations",
            "## Safe Change Workflow",
            "## Related Documentation",
        )
        for node in atlas.nodes:
            with self.subTest(node=node.id):
                rendered = folder_readme(atlas, node)
                for heading in required:
                    self.assertIn(heading, rendered)
                self.assertIn(node.purpose, rendered)
                self.assertIn("Generated by `./hfx generate`", rendered)

    def test_generation_and_change_impact_are_deterministic(self) -> None:
        atlas = load_repository_atlas(ROOT)
        self.assertEqual(markdown(atlas), markdown(load_repository_atlas(ROOT)))
        for node in atlas.nodes:
            self.assertEqual(impact_summary(atlas, node), impact_summary(atlas, node))

    def test_atlas_source_change_selects_all_direct_contract_consumers(self) -> None:
        selection = select_tests(
            load_test_catalog(ROOT),
            "fast",
            ("architecture/repository-atlas.json",),
        )
        selected = {node.id for node in selection.nodes}
        self.assertLessEqual(
            {
                "schema-contracts",
                "repository-atlas-contracts",
                "generated-freshness",
                "documentation-portal-contracts",
                "python-unit",
            },
            selected,
        )


if __name__ == "__main__":
    unittest.main()
