/* Generated by ./hfx generate. Do not edit manually. */
/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef HYPERFLUX_NEXT_VERSION_H
#define HYPERFLUX_NEXT_VERSION_H

#define HYPERFLUX_NEXT_MODULE_VERSION "0.0.0-dev.1"
#define HYPERFLUX_NEXT_CONTROL_TRANSFER_TIMEOUT_MS 1000U

#endif
