// Generated by ./hfx generate. Do not edit manually.
// SPDX-License-Identifier: GPL-2.0-only

use serde::{Deserialize, Serialize};
use std::fmt;
use std::str::FromStr;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DomainValueError {
    type_name: &'static str,
    reason: &'static str,
}

impl DomainValueError {
    const fn new(type_name: &'static str, reason: &'static str) -> Self {
        Self { type_name, reason }
    }

    const fn unknown_wire(type_name: &'static str) -> Self {
        Self::new(type_name, "unknown wire value")
    }
}

impl fmt::Display for DomainValueError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "invalid {}: {}", self.type_name, self.reason)
    }
}

impl std::error::Error for DomainValueError {}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct GenerationId(u64);

impl GenerationId {
    pub const MIN: u64 = 1;
    pub const MAX: u64 = 18_446_744_073_709_551_615;

    #[must_use]
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl TryFrom<u64> for GenerationId {
    type Error = DomainValueError;

    fn try_from(value: u64) -> Result<Self, Self::Error> {
        if value < Self::MIN {
            return Err(DomainValueError::new(
                "GenerationId",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<GenerationId> for u64 {
    fn from(value: GenerationId) -> Self {
        value.0
    }
}

impl fmt::Display for GenerationId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

impl TryFrom<String> for GenerationId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        let parsed = value
            .parse::<u64>()
            .map_err(|_| DomainValueError::new("GenerationId", "invalid decimal string"))?;
        if parsed.to_string() != value {
            return Err(DomainValueError::new(
                "GenerationId",
                "non-canonical decimal string",
            ));
        }
        Self::try_from(parsed)
    }
}

impl From<GenerationId> for String {
    fn from(value: GenerationId) -> Self {
        value.0.to_string()
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u16", into = "u16")]
pub struct VendorId(u16);

impl VendorId {
    pub const MIN: u16 = 0;
    pub const MAX: u16 = 65_535;

    #[must_use]
    pub const fn get(self) -> u16 {
        self.0
    }
}

impl TryFrom<u16> for VendorId {
    type Error = DomainValueError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        Ok(Self(value))
    }
}

impl From<VendorId> for u16 {
    fn from(value: VendorId) -> Self {
        value.0
    }
}

impl fmt::Display for VendorId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u16", into = "u16")]
pub struct ProductId(u16);

impl ProductId {
    pub const MIN: u16 = 0;
    pub const MAX: u16 = 65_535;

    #[must_use]
    pub const fn get(self) -> u16 {
        self.0
    }
}

impl TryFrom<u16> for ProductId {
    type Error = DomainValueError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        Ok(Self(value))
    }
}

impl From<ProductId> for u16 {
    fn from(value: ProductId) -> Self {
        value.0
    }
}

impl fmt::Display for ProductId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u32", into = "u32")]
pub struct ProfileRevision(u32);

impl ProfileRevision {
    pub const MIN: u32 = 1;
    pub const MAX: u32 = 4_294_967_295;

    #[must_use]
    pub const fn get(self) -> u32 {
        self.0
    }
}

impl TryFrom<u32> for ProfileRevision {
    type Error = DomainValueError;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        if value < Self::MIN {
            return Err(DomainValueError::new(
                "ProfileRevision",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<ProfileRevision> for u32 {
    fn from(value: ProfileRevision) -> Self {
        value.0
    }
}

impl fmt::Display for ProfileRevision {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u8", into = "u8")]
pub struct BatteryPercent(u8);

impl BatteryPercent {
    pub const MIN: u8 = 0;
    pub const MAX: u8 = 100;

    #[must_use]
    pub const fn get(self) -> u8 {
        self.0
    }
}

impl TryFrom<u8> for BatteryPercent {
    type Error = DomainValueError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        if value > Self::MAX {
            return Err(DomainValueError::new(
                "BatteryPercent",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<BatteryPercent> for u8 {
    fn from(value: BatteryPercent) -> Self {
        value.0
    }
}

impl fmt::Display for BatteryPercent {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u8", into = "u8")]
pub struct Brightness(u8);

impl Brightness {
    pub const MIN: u8 = 0;
    pub const MAX: u8 = 255;

    #[must_use]
    pub const fn get(self) -> u8 {
        self.0
    }
}

impl TryFrom<u8> for Brightness {
    type Error = DomainValueError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Ok(Self(value))
    }
}

impl From<Brightness> for u8 {
    fn from(value: Brightness) -> Self {
        value.0
    }
}

impl fmt::Display for Brightness {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u64", into = "u64")]
pub struct DurationMs(u64);

impl DurationMs {
    pub const MIN: u64 = 0;
    pub const MAX: u64 = 86_400_000;

    #[must_use]
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl TryFrom<u64> for DurationMs {
    type Error = DomainValueError;

    fn try_from(value: u64) -> Result<Self, Self::Error> {
        if value > Self::MAX {
            return Err(DomainValueError::new(
                "DurationMs",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<DurationMs> for u64 {
    fn from(value: DurationMs) -> Self {
        value.0
    }
}

impl fmt::Display for DurationMs {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct SequenceNumber(u64);

impl SequenceNumber {
    pub const MIN: u64 = 0;
    pub const MAX: u64 = 18_446_744_073_709_551_615;

    #[must_use]
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl TryFrom<u64> for SequenceNumber {
    type Error = DomainValueError;

    fn try_from(value: u64) -> Result<Self, Self::Error> {
        Ok(Self(value))
    }
}

impl From<SequenceNumber> for u64 {
    fn from(value: SequenceNumber) -> Self {
        value.0
    }
}

impl fmt::Display for SequenceNumber {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

impl TryFrom<String> for SequenceNumber {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        let parsed = value
            .parse::<u64>()
            .map_err(|_| DomainValueError::new("SequenceNumber", "invalid decimal string"))?;
        if parsed.to_string() != value {
            return Err(DomainValueError::new(
                "SequenceNumber",
                "non-canonical decimal string",
            ));
        }
        Self::try_from(parsed)
    }
}

impl From<SequenceNumber> for String {
    fn from(value: SequenceNumber) -> Self {
        value.0.to_string()
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u16", into = "u16")]
pub struct LedIndex(u16);

impl LedIndex {
    pub const MIN: u16 = 0;
    pub const MAX: u16 = 4_095;

    #[must_use]
    pub const fn get(self) -> u16 {
        self.0
    }
}

impl TryFrom<u16> for LedIndex {
    type Error = DomainValueError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        if value > Self::MAX {
            return Err(DomainValueError::new(
                "LedIndex",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<LedIndex> for u16 {
    fn from(value: LedIndex) -> Self {
        value.0
    }
}

impl fmt::Display for LedIndex {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u16", into = "u16")]
pub struct LedCount(u16);

impl LedCount {
    pub const MIN: u16 = 0;
    pub const MAX: u16 = 4_096;

    #[must_use]
    pub const fn get(self) -> u16 {
        self.0
    }
}

impl TryFrom<u16> for LedCount {
    type Error = DomainValueError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        if value > Self::MAX {
            return Err(DomainValueError::new(
                "LedCount",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<LedCount> for u16 {
    fn from(value: LedCount) -> Self {
        value.0
    }
}

impl fmt::Display for LedCount {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u16", into = "u16")]
pub struct CarrierIndex(u16);

impl CarrierIndex {
    pub const MIN: u16 = 0;
    pub const MAX: u16 = 4_095;

    #[must_use]
    pub const fn get(self) -> u16 {
        self.0
    }
}

impl TryFrom<u16> for CarrierIndex {
    type Error = DomainValueError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        if value > Self::MAX {
            return Err(DomainValueError::new(
                "CarrierIndex",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<CarrierIndex> for u16 {
    fn from(value: CarrierIndex) -> Self {
        value.0
    }
}

impl fmt::Display for CarrierIndex {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u16", into = "u16")]
pub struct ProtocolVersion(u16);

impl ProtocolVersion {
    pub const MIN: u16 = 1;
    pub const MAX: u16 = 65_535;

    #[must_use]
    pub const fn get(self) -> u16 {
        self.0
    }
}

impl TryFrom<u16> for ProtocolVersion {
    type Error = DomainValueError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        if value < Self::MIN {
            return Err(DomainValueError::new(
                "ProtocolVersion",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<ProtocolVersion> for u16 {
    fn from(value: ProtocolVersion) -> Self {
        value.0
    }
}

impl fmt::Display for ProtocolVersion {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct MonotonicMs(u64);

impl MonotonicMs {
    pub const MIN: u64 = 0;
    pub const MAX: u64 = 18_446_744_073_709_551_615;

    #[must_use]
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl TryFrom<u64> for MonotonicMs {
    type Error = DomainValueError;

    fn try_from(value: u64) -> Result<Self, Self::Error> {
        Ok(Self(value))
    }
}

impl From<MonotonicMs> for u64 {
    fn from(value: MonotonicMs) -> Self {
        value.0
    }
}

impl fmt::Display for MonotonicMs {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

impl TryFrom<String> for MonotonicMs {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        let parsed = value
            .parse::<u64>()
            .map_err(|_| DomainValueError::new("MonotonicMs", "invalid decimal string"))?;
        if parsed.to_string() != value {
            return Err(DomainValueError::new(
                "MonotonicMs",
                "non-canonical decimal string",
            ));
        }
        Self::try_from(parsed)
    }
}

impl From<MonotonicMs> for String {
    fn from(value: MonotonicMs) -> Self {
        value.0.to_string()
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u16", into = "u16")]
pub struct QueueCapacity(u16);

impl QueueCapacity {
    pub const MIN: u16 = 1;
    pub const MAX: u16 = 4_096;

    #[must_use]
    pub const fn get(self) -> u16 {
        self.0
    }
}

impl TryFrom<u16> for QueueCapacity {
    type Error = DomainValueError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        if !(Self::MIN..=Self::MAX).contains(&value) {
            return Err(DomainValueError::new(
                "QueueCapacity",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<QueueCapacity> for u16 {
    fn from(value: QueueCapacity) -> Self {
        value.0
    }
}

impl fmt::Display for QueueCapacity {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u32", into = "u32")]
pub struct FrameIndex(u32);

impl FrameIndex {
    pub const MIN: u32 = 0;
    pub const MAX: u32 = 4_294_967_295;

    #[must_use]
    pub const fn get(self) -> u32 {
        self.0
    }
}

impl TryFrom<u32> for FrameIndex {
    type Error = DomainValueError;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        Ok(Self(value))
    }
}

impl From<FrameIndex> for u32 {
    fn from(value: FrameIndex) -> Self {
        value.0
    }
}

impl fmt::Display for FrameIndex {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u16", into = "u16")]
pub struct FrameCount(u16);

impl FrameCount {
    pub const MIN: u16 = 1;
    pub const MAX: u16 = 4_096;

    #[must_use]
    pub const fn get(self) -> u16 {
        self.0
    }
}

impl TryFrom<u16> for FrameCount {
    type Error = DomainValueError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        if !(Self::MIN..=Self::MAX).contains(&value) {
            return Err(DomainValueError::new(
                "FrameCount",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<FrameCount> for u16 {
    fn from(value: FrameCount) -> Self {
        value.0
    }
}

impl fmt::Display for FrameCount {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u8", into = "u8")]
pub struct ColorChannel(u8);

impl ColorChannel {
    pub const MIN: u8 = 0;
    pub const MAX: u8 = 255;

    #[must_use]
    pub const fn get(self) -> u8 {
        self.0
    }
}

impl TryFrom<u8> for ColorChannel {
    type Error = DomainValueError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Ok(Self(value))
    }
}

impl From<ColorChannel> for u8 {
    fn from(value: ColorChannel) -> Self {
        value.0
    }
}

impl fmt::Display for ColorChannel {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u16", into = "u16")]
pub struct DeliveredFrameCount(u16);

impl DeliveredFrameCount {
    pub const MIN: u16 = 0;
    pub const MAX: u16 = 4_096;

    #[must_use]
    pub const fn get(self) -> u16 {
        self.0
    }
}

impl TryFrom<u16> for DeliveredFrameCount {
    type Error = DomainValueError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        if value > Self::MAX {
            return Err(DomainValueError::new(
                "DeliveredFrameCount",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<DeliveredFrameCount> for u16 {
    fn from(value: DeliveredFrameCount) -> Self {
        value.0
    }
}

impl fmt::Display for DeliveredFrameCount {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u32", into = "u32")]
pub struct LeaseDurationMs(u32);

impl LeaseDurationMs {
    pub const MIN: u32 = 1_000;
    pub const MAX: u32 = 3_600_000;

    #[must_use]
    pub const fn get(self) -> u32 {
        self.0
    }
}

impl TryFrom<u32> for LeaseDurationMs {
    type Error = DomainValueError;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        if !(Self::MIN..=Self::MAX).contains(&value) {
            return Err(DomainValueError::new(
                "LeaseDurationMs",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<LeaseDurationMs> for u32 {
    fn from(value: LeaseDurationMs) -> Self {
        value.0
    }
}

impl fmt::Display for LeaseDurationMs {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct StreamEpoch(u64);

impl StreamEpoch {
    pub const MIN: u64 = 1;
    pub const MAX: u64 = 18_446_744_073_709_551_615;

    #[must_use]
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl TryFrom<u64> for StreamEpoch {
    type Error = DomainValueError;

    fn try_from(value: u64) -> Result<Self, Self::Error> {
        if value < Self::MIN {
            return Err(DomainValueError::new(
                "StreamEpoch",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<StreamEpoch> for u64 {
    fn from(value: StreamEpoch) -> Self {
        value.0
    }
}

impl fmt::Display for StreamEpoch {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

impl TryFrom<String> for StreamEpoch {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        let parsed = value
            .parse::<u64>()
            .map_err(|_| DomainValueError::new("StreamEpoch", "invalid decimal string"))?;
        if parsed.to_string() != value {
            return Err(DomainValueError::new(
                "StreamEpoch",
                "non-canonical decimal string",
            ));
        }
        Self::try_from(parsed)
    }
}

impl From<StreamEpoch> for String {
    fn from(value: StreamEpoch) -> Self {
        value.0.to_string()
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct DroppedEventCount(u64);

impl DroppedEventCount {
    pub const MIN: u64 = 0;
    pub const MAX: u64 = 18_446_744_073_709_551_615;

    #[must_use]
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl TryFrom<u64> for DroppedEventCount {
    type Error = DomainValueError;

    fn try_from(value: u64) -> Result<Self, Self::Error> {
        Ok(Self(value))
    }
}

impl From<DroppedEventCount> for u64 {
    fn from(value: DroppedEventCount) -> Self {
        value.0
    }
}

impl fmt::Display for DroppedEventCount {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

impl TryFrom<String> for DroppedEventCount {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        let parsed = value
            .parse::<u64>()
            .map_err(|_| DomainValueError::new("DroppedEventCount", "invalid decimal string"))?;
        if parsed.to_string() != value {
            return Err(DomainValueError::new(
                "DroppedEventCount",
                "non-canonical decimal string",
            ));
        }
        Self::try_from(parsed)
    }
}

impl From<DroppedEventCount> for String {
    fn from(value: DroppedEventCount) -> Self {
        value.0.to_string()
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "u32", into = "u32")]
pub struct ProjectionRevision(u32);

impl ProjectionRevision {
    pub const MIN: u32 = 1;
    pub const MAX: u32 = 4_294_967_295;

    #[must_use]
    pub const fn get(self) -> u32 {
        self.0
    }
}

impl TryFrom<u32> for ProjectionRevision {
    type Error = DomainValueError;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        if value < Self::MIN {
            return Err(DomainValueError::new(
                "ProjectionRevision",
                "outside the canonical range",
            ));
        }
        Ok(Self(value))
    }
}

impl From<ProjectionRevision> for u32 {
    fn from(value: ProjectionRevision) -> Self {
        value.0
    }
}

impl fmt::Display for ProjectionRevision {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct ReceiverId(String);

impl ReceiverId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for ReceiverId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "ReceiverId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for ReceiverId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<ReceiverId> for String {
    fn from(value: ReceiverId) -> Self {
        value.0
    }
}

impl fmt::Display for ReceiverId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct LogicalDeviceId(String);

impl LogicalDeviceId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for LogicalDeviceId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "LogicalDeviceId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for LogicalDeviceId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<LogicalDeviceId> for String {
    fn from(value: LogicalDeviceId) -> Self {
        value.0
    }
}

impl fmt::Display for LogicalDeviceId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct EndpointId(String);

impl EndpointId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for EndpointId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "EndpointId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for EndpointId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<EndpointId> for String {
    fn from(value: EndpointId) -> Self {
        value.0
    }
}

impl fmt::Display for EndpointId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct LeaseId(String);

impl LeaseId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for LeaseId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "LeaseId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for LeaseId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<LeaseId> for String {
    fn from(value: LeaseId) -> Self {
        value.0
    }
}

impl fmt::Display for LeaseId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct TransactionId(String);

impl TransactionId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for TransactionId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "TransactionId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for TransactionId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<TransactionId> for String {
    fn from(value: TransactionId) -> Self {
        value.0
    }
}

impl fmt::Display for TransactionId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct ProfileId(String);

impl ProfileId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for ProfileId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "ProfileId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for ProfileId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<ProfileId> for String {
    fn from(value: ProfileId) -> Self {
        value.0
    }
}

impl fmt::Display for ProfileId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct CapabilityId(String);

impl CapabilityId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for CapabilityId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "CapabilityId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for CapabilityId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<CapabilityId> for String {
    fn from(value: CapabilityId) -> Self {
        value.0
    }
}

impl fmt::Display for CapabilityId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct EvidenceClaimId(String);

impl EvidenceClaimId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 160;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for EvidenceClaimId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "EvidenceClaimId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for EvidenceClaimId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<EvidenceClaimId> for String {
    fn from(value: EvidenceClaimId) -> Self {
        value.0
    }
}

impl fmt::Display for EvidenceClaimId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct ScenarioId(String);

impl ScenarioId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for ScenarioId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "ScenarioId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for ScenarioId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<ScenarioId> for String {
    fn from(value: ScenarioId) -> Self {
        value.0
    }
}

impl fmt::Display for ScenarioId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct RestoreId(String);

impl RestoreId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for RestoreId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "RestoreId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for RestoreId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<RestoreId> for String {
    fn from(value: RestoreId) -> Self {
        value.0
    }
}

impl fmt::Display for RestoreId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct ClientId(String);

impl ClientId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for ClientId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "ClientId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for ClientId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<ClientId> for String {
    fn from(value: ClientId) -> Self {
        value.0
    }
}

impl fmt::Display for ClientId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct RequestId(String);

impl RequestId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for RequestId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "RequestId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for RequestId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<RequestId> for String {
    fn from(value: RequestId) -> Self {
        value.0
    }
}

impl fmt::Display for RequestId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct SubscriptionId(String);

impl SubscriptionId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for SubscriptionId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "SubscriptionId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for SubscriptionId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<SubscriptionId> for String {
    fn from(value: SubscriptionId) -> Self {
        value.0
    }
}

impl fmt::Display for SubscriptionId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct FindingId(String);

impl FindingId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for FindingId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "FindingId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for FindingId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<FindingId> for String {
    fn from(value: FindingId) -> Self {
        value.0
    }
}

impl fmt::Display for FindingId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct ComponentVersion(String);

impl ComponentVersion {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 64;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for ComponentVersion {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "ComponentVersion",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for ComponentVersion {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<ComponentVersion> for String {
    fn from(value: ComponentVersion) -> Self {
        value.0
    }
}

impl fmt::Display for ComponentVersion {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct ClientName(String);

impl ClientName {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for ClientName {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "ClientName",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for ClientName {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<ClientName> for String {
    fn from(value: ClientName) -> Self {
        value.0
    }
}

impl fmt::Display for ClientName {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct HumanMessage(String);

impl HumanMessage {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 512;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for HumanMessage {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "HumanMessage",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for HumanMessage {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<HumanMessage> for String {
    fn from(value: HumanMessage) -> Self {
        value.0
    }
}

impl fmt::Display for HumanMessage {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct DocumentationPath(String);

impl DocumentationPath {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 256;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for DocumentationPath {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "DocumentationPath",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for DocumentationPath {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<DocumentationPath> for String {
    fn from(value: DocumentationPath) -> Self {
        value.0
    }
}

impl fmt::Display for DocumentationPath {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "String", into = "String")]
pub struct StreamId(String);

impl StreamId {
    pub const MIN_LENGTH: usize = 1;
    pub const MAX_LENGTH: usize = 128;

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for StreamId {
    type Error = DomainValueError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {
            return Err(DomainValueError::new(
                "StreamId",
                "outside the canonical length",
            ));
        }
        Ok(Self(value))
    }
}

impl TryFrom<&str> for StreamId {
    type Error = DomainValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::try_from(value.to_owned())
    }
}

impl From<StreamId> for String {
    fn from(value: StreamId) -> Self {
        value.0
    }
}

impl fmt::Display for StreamId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum DeviceKind {
    #[serde(rename = "receiver")]
    Receiver,
    #[serde(rename = "mat")]
    Mat,
    #[serde(rename = "mouse")]
    Mouse,
    #[serde(rename = "keyboard")]
    Keyboard,
    #[serde(rename = "unknown")]
    Unknown,
}

impl DeviceKind {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Receiver => "receiver",
            Self::Mat => "mat",
            Self::Mouse => "mouse",
            Self::Keyboard => "keyboard",
            Self::Unknown => "unknown",
        }
    }
}

impl FromStr for DeviceKind {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "receiver" => Ok(Self::Receiver),
            "mat" => Ok(Self::Mat),
            "mouse" => Ok(Self::Mouse),
            "keyboard" => Ok(Self::Keyboard),
            "unknown" => Ok(Self::Unknown),
            _ => Err(DomainValueError::unknown_wire("DeviceKind")),
        }
    }
}

impl fmt::Display for DeviceKind {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum ProfileKind {
    #[serde(rename = "receiver")]
    Receiver,
    #[serde(rename = "child")]
    Child,
    #[serde(rename = "surface")]
    Surface,
}

impl ProfileKind {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Receiver => "receiver",
            Self::Child => "child",
            Self::Surface => "surface",
        }
    }
}

impl FromStr for ProfileKind {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "receiver" => Ok(Self::Receiver),
            "child" => Ok(Self::Child),
            "surface" => Ok(Self::Surface),
            _ => Err(DomainValueError::unknown_wire("ProfileKind")),
        }
    }
}

impl fmt::Display for ProfileKind {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum RouteKind {
    #[serde(rename = "hyperflux-wireless")]
    HyperfluxWireless,
    #[serde(rename = "direct-usb")]
    DirectUsb,
    #[serde(rename = "bluetooth")]
    Bluetooth,
}

impl RouteKind {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::HyperfluxWireless => "hyperflux-wireless",
            Self::DirectUsb => "direct-usb",
            Self::Bluetooth => "bluetooth",
        }
    }
}

impl FromStr for RouteKind {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "hyperflux-wireless" => Ok(Self::HyperfluxWireless),
            "direct-usb" => Ok(Self::DirectUsb),
            "bluetooth" => Ok(Self::Bluetooth),
            _ => Err(DomainValueError::unknown_wire("RouteKind")),
        }
    }
}

impl fmt::Display for RouteKind {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum PairingState {
    #[serde(rename = "paired")]
    Paired,
    #[serde(rename = "unpaired")]
    Unpaired,
    #[serde(rename = "unknown")]
    Unknown,
}

impl PairingState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Paired => "paired",
            Self::Unpaired => "unpaired",
            Self::Unknown => "unknown",
        }
    }
}

impl FromStr for PairingState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "paired" => Ok(Self::Paired),
            "unpaired" => Ok(Self::Unpaired),
            "unknown" => Ok(Self::Unknown),
            _ => Err(DomainValueError::unknown_wire("PairingState")),
        }
    }
}

impl fmt::Display for PairingState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum PresenceState {
    #[serde(rename = "available")]
    Available,
    #[serde(rename = "sleeping")]
    Sleeping,
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "unknown")]
    Unknown,
}

impl PresenceState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Available => "available",
            Self::Sleeping => "sleeping",
            Self::Unavailable => "unavailable",
            Self::Unknown => "unknown",
        }
    }
}

impl FromStr for PresenceState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "available" => Ok(Self::Available),
            "sleeping" => Ok(Self::Sleeping),
            "unavailable" => Ok(Self::Unavailable),
            "unknown" => Ok(Self::Unknown),
            _ => Err(DomainValueError::unknown_wire("PresenceState")),
        }
    }
}

impl fmt::Display for PresenceState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum ConnectionMode {
    #[serde(rename = "hyperflux-2.4ghz")]
    Hyperflux24ghz,
    #[serde(rename = "direct-usb")]
    DirectUsb,
    #[serde(rename = "bluetooth")]
    Bluetooth,
    #[serde(rename = "unknown")]
    Unknown,
}

impl ConnectionMode {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Hyperflux24ghz => "hyperflux-2.4ghz",
            Self::DirectUsb => "direct-usb",
            Self::Bluetooth => "bluetooth",
            Self::Unknown => "unknown",
        }
    }
}

impl FromStr for ConnectionMode {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "hyperflux-2.4ghz" => Ok(Self::Hyperflux24ghz),
            "direct-usb" => Ok(Self::DirectUsb),
            "bluetooth" => Ok(Self::Bluetooth),
            "unknown" => Ok(Self::Unknown),
            _ => Err(DomainValueError::unknown_wire("ConnectionMode")),
        }
    }
}

impl fmt::Display for ConnectionMode {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum RouteState {
    #[serde(rename = "available")]
    Available,
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "stale")]
    Stale,
    #[serde(rename = "unknown")]
    Unknown,
}

impl RouteState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Available => "available",
            Self::Unavailable => "unavailable",
            Self::Stale => "stale",
            Self::Unknown => "unknown",
        }
    }
}

impl FromStr for RouteState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "available" => Ok(Self::Available),
            "unavailable" => Ok(Self::Unavailable),
            "stale" => Ok(Self::Stale),
            "unknown" => Ok(Self::Unknown),
            _ => Err(DomainValueError::unknown_wire("RouteState")),
        }
    }
}

impl fmt::Display for RouteState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum PowerState {
    #[serde(rename = "on")]
    On,
    #[serde(rename = "off")]
    Off,
    #[serde(rename = "unknown")]
    Unknown,
}

impl PowerState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::On => "on",
            Self::Off => "off",
            Self::Unknown => "unknown",
        }
    }
}

impl FromStr for PowerState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "on" => Ok(Self::On),
            "off" => Ok(Self::Off),
            "unknown" => Ok(Self::Unknown),
            _ => Err(DomainValueError::unknown_wire("PowerState")),
        }
    }
}

impl fmt::Display for PowerState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum SleepState {
    #[serde(rename = "awake")]
    Awake,
    #[serde(rename = "asleep")]
    Asleep,
    #[serde(rename = "unknown")]
    Unknown,
}

impl SleepState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Awake => "awake",
            Self::Asleep => "asleep",
            Self::Unknown => "unknown",
        }
    }
}

impl FromStr for SleepState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "awake" => Ok(Self::Awake),
            "asleep" => Ok(Self::Asleep),
            "unknown" => Ok(Self::Unknown),
            _ => Err(DomainValueError::unknown_wire("SleepState")),
        }
    }
}

impl fmt::Display for SleepState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum ContactState {
    #[serde(rename = "on-mat")]
    OnMat,
    #[serde(rename = "off-mat")]
    OffMat,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "not-applicable")]
    NotApplicable,
}

impl ContactState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::OnMat => "on-mat",
            Self::OffMat => "off-mat",
            Self::Unknown => "unknown",
            Self::NotApplicable => "not-applicable",
        }
    }
}

impl FromStr for ContactState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "on-mat" => Ok(Self::OnMat),
            "off-mat" => Ok(Self::OffMat),
            "unknown" => Ok(Self::Unknown),
            "not-applicable" => Ok(Self::NotApplicable),
            _ => Err(DomainValueError::unknown_wire("ContactState")),
        }
    }
}

impl fmt::Display for ContactState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum ActivityState {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "unknown")]
    Unknown,
}

impl ActivityState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Idle => "idle",
            Self::Unknown => "unknown",
        }
    }
}

impl FromStr for ActivityState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "active" => Ok(Self::Active),
            "idle" => Ok(Self::Idle),
            "unknown" => Ok(Self::Unknown),
            _ => Err(DomainValueError::unknown_wire("ActivityState")),
        }
    }
}

impl fmt::Display for ActivityState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum FreshnessState {
    #[serde(rename = "fresh")]
    Fresh,
    #[serde(rename = "stale")]
    Stale,
    #[serde(rename = "unknown")]
    Unknown,
}

impl FreshnessState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Fresh => "fresh",
            Self::Stale => "stale",
            Self::Unknown => "unknown",
        }
    }
}

impl FromStr for FreshnessState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "fresh" => Ok(Self::Fresh),
            "stale" => Ok(Self::Stale),
            "unknown" => Ok(Self::Unknown),
            _ => Err(DomainValueError::unknown_wire("FreshnessState")),
        }
    }
}

impl fmt::Display for FreshnessState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum ReceiverLifecycleState {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "suspended")]
    Suspended,
    #[serde(rename = "partially-suspended")]
    PartiallySuspended,
    #[serde(rename = "disconnecting")]
    Disconnecting,
    #[serde(rename = "unknown")]
    Unknown,
}

impl ReceiverLifecycleState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Suspended => "suspended",
            Self::PartiallySuspended => "partially-suspended",
            Self::Disconnecting => "disconnecting",
            Self::Unknown => "unknown",
        }
    }
}

impl FromStr for ReceiverLifecycleState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "active" => Ok(Self::Active),
            "suspended" => Ok(Self::Suspended),
            "partially-suspended" => Ok(Self::PartiallySuspended),
            "disconnecting" => Ok(Self::Disconnecting),
            "unknown" => Ok(Self::Unknown),
            _ => Err(DomainValueError::unknown_wire("ReceiverLifecycleState")),
        }
    }
}

impl fmt::Display for ReceiverLifecycleState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum FixtureSource {
    #[serde(rename = "deterministic-simulator")]
    DeterministicSimulator,
    #[serde(rename = "sanitized-replay")]
    SanitizedReplay,
}

impl FixtureSource {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::DeterministicSimulator => "deterministic-simulator",
            Self::SanitizedReplay => "sanitized-replay",
        }
    }
}

impl FromStr for FixtureSource {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "deterministic-simulator" => Ok(Self::DeterministicSimulator),
            "sanitized-replay" => Ok(Self::SanitizedReplay),
            _ => Err(DomainValueError::unknown_wire("FixtureSource")),
        }
    }
}

impl fmt::Display for FixtureSource {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum TransportOutcome {
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "failed")]
    Failed,
}

impl TransportOutcome {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Delivered => "delivered",
            Self::Failed => "failed",
        }
    }
}

impl FromStr for TransportOutcome {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "delivered" => Ok(Self::Delivered),
            "failed" => Ok(Self::Failed),
            _ => Err(DomainValueError::unknown_wire("TransportOutcome")),
        }
    }
}

impl fmt::Display for TransportOutcome {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum ApplyOutcome {
    #[serde(rename = "applied")]
    Applied,
    #[serde(rename = "ignored-older-observation")]
    IgnoredOlderObservation,
    #[serde(rename = "rejected-stale-generation")]
    RejectedStaleGeneration,
    #[serde(rename = "rejected-receiver-absent")]
    RejectedReceiverAbsent,
    #[serde(rename = "rejected-unknown-device")]
    RejectedUnknownDevice,
    #[serde(rename = "rejected-unavailable-route")]
    RejectedUnavailableRoute,
    #[serde(rename = "rejected-unqualified-write")]
    RejectedUnqualifiedWrite,
    #[serde(rename = "rejected-invalid-transition")]
    RejectedInvalidTransition,
    #[serde(rename = "rejected-transport-failure")]
    RejectedTransportFailure,
    #[serde(rename = "recorded-malformed-observation")]
    RecordedMalformedObservation,
}

impl ApplyOutcome {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Applied => "applied",
            Self::IgnoredOlderObservation => "ignored-older-observation",
            Self::RejectedStaleGeneration => "rejected-stale-generation",
            Self::RejectedReceiverAbsent => "rejected-receiver-absent",
            Self::RejectedUnknownDevice => "rejected-unknown-device",
            Self::RejectedUnavailableRoute => "rejected-unavailable-route",
            Self::RejectedUnqualifiedWrite => "rejected-unqualified-write",
            Self::RejectedInvalidTransition => "rejected-invalid-transition",
            Self::RejectedTransportFailure => "rejected-transport-failure",
            Self::RecordedMalformedObservation => "recorded-malformed-observation",
        }
    }
}

impl FromStr for ApplyOutcome {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "applied" => Ok(Self::Applied),
            "ignored-older-observation" => Ok(Self::IgnoredOlderObservation),
            "rejected-stale-generation" => Ok(Self::RejectedStaleGeneration),
            "rejected-receiver-absent" => Ok(Self::RejectedReceiverAbsent),
            "rejected-unknown-device" => Ok(Self::RejectedUnknownDevice),
            "rejected-unavailable-route" => Ok(Self::RejectedUnavailableRoute),
            "rejected-unqualified-write" => Ok(Self::RejectedUnqualifiedWrite),
            "rejected-invalid-transition" => Ok(Self::RejectedInvalidTransition),
            "rejected-transport-failure" => Ok(Self::RejectedTransportFailure),
            "recorded-malformed-observation" => Ok(Self::RecordedMalformedObservation),
            _ => Err(DomainValueError::unknown_wire("ApplyOutcome")),
        }
    }
}

impl fmt::Display for ApplyOutcome {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum EvidenceConfidence {
    #[serde(rename = "observed")]
    Observed,
    #[serde(rename = "derived")]
    Derived,
    #[serde(rename = "inferred")]
    Inferred,
    #[serde(rename = "unknown")]
    Unknown,
}

impl EvidenceConfidence {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Observed => "observed",
            Self::Derived => "derived",
            Self::Inferred => "inferred",
            Self::Unknown => "unknown",
        }
    }
}

impl FromStr for EvidenceConfidence {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "observed" => Ok(Self::Observed),
            "derived" => Ok(Self::Derived),
            "inferred" => Ok(Self::Inferred),
            "unknown" => Ok(Self::Unknown),
            _ => Err(DomainValueError::unknown_wire("EvidenceConfidence")),
        }
    }
}

impl fmt::Display for EvidenceConfidence {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum EvidenceLevel {
    #[serde(rename = "requirement")]
    Requirement,
    #[serde(rename = "source-reviewed")]
    SourceReviewed,
    #[serde(rename = "simulation-proven")]
    SimulationProven,
    #[serde(rename = "hardware-observed")]
    HardwareObserved,
    #[serde(rename = "hardware-qualified")]
    HardwareQualified,
    #[serde(rename = "production-qualified")]
    ProductionQualified,
}

impl EvidenceLevel {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Requirement => "requirement",
            Self::SourceReviewed => "source-reviewed",
            Self::SimulationProven => "simulation-proven",
            Self::HardwareObserved => "hardware-observed",
            Self::HardwareQualified => "hardware-qualified",
            Self::ProductionQualified => "production-qualified",
        }
    }
}

impl FromStr for EvidenceLevel {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "requirement" => Ok(Self::Requirement),
            "source-reviewed" => Ok(Self::SourceReviewed),
            "simulation-proven" => Ok(Self::SimulationProven),
            "hardware-observed" => Ok(Self::HardwareObserved),
            "hardware-qualified" => Ok(Self::HardwareQualified),
            "production-qualified" => Ok(Self::ProductionQualified),
            _ => Err(DomainValueError::unknown_wire("EvidenceLevel")),
        }
    }
}

impl fmt::Display for EvidenceLevel {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum PrivacyClass {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "public-summary")]
    PublicSummary,
    #[serde(rename = "sensitive")]
    Sensitive,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "forbidden")]
    Forbidden,
}

impl PrivacyClass {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Public => "public",
            Self::PublicSummary => "public-summary",
            Self::Sensitive => "sensitive",
            Self::Private => "private",
            Self::Forbidden => "forbidden",
        }
    }
}

impl FromStr for PrivacyClass {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "public" => Ok(Self::Public),
            "public-summary" => Ok(Self::PublicSummary),
            "sensitive" => Ok(Self::Sensitive),
            "private" => Ok(Self::Private),
            "forbidden" => Ok(Self::Forbidden),
            _ => Err(DomainValueError::unknown_wire("PrivacyClass")),
        }
    }
}

impl fmt::Display for PrivacyClass {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum SupportLevel {
    #[serde(rename = "candidate")]
    Candidate,
    #[serde(rename = "identified")]
    Identified,
    #[serde(rename = "read-only")]
    ReadOnly,
    #[serde(rename = "telemetry-qualified")]
    TelemetryQualified,
    #[serde(rename = "lighting-qualified")]
    LightingQualified,
    #[serde(rename = "settings-qualified")]
    SettingsQualified,
    #[serde(rename = "pairing-qualified")]
    PairingQualified,
    #[serde(rename = "production-qualified")]
    ProductionQualified,
}

impl SupportLevel {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Candidate => "candidate",
            Self::Identified => "identified",
            Self::ReadOnly => "read-only",
            Self::TelemetryQualified => "telemetry-qualified",
            Self::LightingQualified => "lighting-qualified",
            Self::SettingsQualified => "settings-qualified",
            Self::PairingQualified => "pairing-qualified",
            Self::ProductionQualified => "production-qualified",
        }
    }
}

impl FromStr for SupportLevel {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "candidate" => Ok(Self::Candidate),
            "identified" => Ok(Self::Identified),
            "read-only" => Ok(Self::ReadOnly),
            "telemetry-qualified" => Ok(Self::TelemetryQualified),
            "lighting-qualified" => Ok(Self::LightingQualified),
            "settings-qualified" => Ok(Self::SettingsQualified),
            "pairing-qualified" => Ok(Self::PairingQualified),
            "production-qualified" => Ok(Self::ProductionQualified),
            _ => Err(DomainValueError::unknown_wire("SupportLevel")),
        }
    }
}

impl fmt::Display for SupportLevel {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum ReceiverState {
    #[serde(rename = "absent")]
    Absent,
    #[serde(rename = "discovered-read-only")]
    DiscoveredReadOnly,
    #[serde(rename = "observed")]
    Observed,
    #[serde(rename = "profile-qualified")]
    ProfileQualified,
    #[serde(rename = "session-authorized")]
    SessionAuthorized,
    #[serde(rename = "degraded-read-only")]
    DegradedReadOnly,
}

impl ReceiverState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Absent => "absent",
            Self::DiscoveredReadOnly => "discovered-read-only",
            Self::Observed => "observed",
            Self::ProfileQualified => "profile-qualified",
            Self::SessionAuthorized => "session-authorized",
            Self::DegradedReadOnly => "degraded-read-only",
        }
    }
}

impl FromStr for ReceiverState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "absent" => Ok(Self::Absent),
            "discovered-read-only" => Ok(Self::DiscoveredReadOnly),
            "observed" => Ok(Self::Observed),
            "profile-qualified" => Ok(Self::ProfileQualified),
            "session-authorized" => Ok(Self::SessionAuthorized),
            "degraded-read-only" => Ok(Self::DegradedReadOnly),
            _ => Err(DomainValueError::unknown_wire("ReceiverState")),
        }
    }
}

impl fmt::Display for ReceiverState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum TransactionState {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "validated")]
    Validated,
    #[serde(rename = "ownership-bound")]
    OwnershipBound,
    #[serde(rename = "generation-bound")]
    GenerationBound,
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "sent")]
    Sent,
    #[serde(rename = "health-pending")]
    HealthPending,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "revoked")]
    Revoked,
}

impl TransactionState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Created => "created",
            Self::Validated => "validated",
            Self::OwnershipBound => "ownership-bound",
            Self::GenerationBound => "generation-bound",
            Self::Queued => "queued",
            Self::Sent => "sent",
            Self::HealthPending => "health-pending",
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::Revoked => "revoked",
        }
    }
}

impl FromStr for TransactionState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "created" => Ok(Self::Created),
            "validated" => Ok(Self::Validated),
            "ownership-bound" => Ok(Self::OwnershipBound),
            "generation-bound" => Ok(Self::GenerationBound),
            "queued" => Ok(Self::Queued),
            "sent" => Ok(Self::Sent),
            "health-pending" => Ok(Self::HealthPending),
            "succeeded" => Ok(Self::Succeeded),
            "failed" => Ok(Self::Failed),
            "revoked" => Ok(Self::Revoked),
            _ => Err(DomainValueError::unknown_wire("TransactionState")),
        }
    }
}

impl fmt::Display for TransactionState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum LeaseState {
    #[serde(rename = "requested")]
    Requested,
    #[serde(rename = "granted")]
    Granted,
    #[serde(rename = "renewed")]
    Renewed,
    #[serde(rename = "released")]
    Released,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "revoked")]
    Revoked,
}

impl LeaseState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Requested => "requested",
            Self::Granted => "granted",
            Self::Renewed => "renewed",
            Self::Released => "released",
            Self::Expired => "expired",
            Self::Revoked => "revoked",
        }
    }
}

impl FromStr for LeaseState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "requested" => Ok(Self::Requested),
            "granted" => Ok(Self::Granted),
            "renewed" => Ok(Self::Renewed),
            "released" => Ok(Self::Released),
            "expired" => Ok(Self::Expired),
            "revoked" => Ok(Self::Revoked),
            _ => Err(DomainValueError::unknown_wire("LeaseState")),
        }
    }
}

impl fmt::Display for LeaseState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum ResourceKind {
    #[serde(rename = "lighting")]
    Lighting,
    #[serde(rename = "settings")]
    Settings,
    #[serde(rename = "pairing")]
    Pairing,
}

impl ResourceKind {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Lighting => "lighting",
            Self::Settings => "settings",
            Self::Pairing => "pairing",
        }
    }
}

impl FromStr for ResourceKind {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "lighting" => Ok(Self::Lighting),
            "settings" => Ok(Self::Settings),
            "pairing" => Ok(Self::Pairing),
            _ => Err(DomainValueError::unknown_wire("ResourceKind")),
        }
    }
}

impl fmt::Display for ResourceKind {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum TransactionClass {
    #[serde(rename = "effect-frame")]
    EffectFrame,
    #[serde(rename = "static-lighting")]
    StaticLighting,
    #[serde(rename = "device-setting")]
    DeviceSetting,
    #[serde(rename = "restore")]
    Restore,
    #[serde(rename = "pairing")]
    Pairing,
}

impl TransactionClass {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::EffectFrame => "effect-frame",
            Self::StaticLighting => "static-lighting",
            Self::DeviceSetting => "device-setting",
            Self::Restore => "restore",
            Self::Pairing => "pairing",
        }
    }
}

impl FromStr for TransactionClass {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "effect-frame" => Ok(Self::EffectFrame),
            "static-lighting" => Ok(Self::StaticLighting),
            "device-setting" => Ok(Self::DeviceSetting),
            "restore" => Ok(Self::Restore),
            "pairing" => Ok(Self::Pairing),
            _ => Err(DomainValueError::unknown_wire("TransactionClass")),
        }
    }
}

impl fmt::Display for TransactionClass {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum QueueAdmission {
    #[serde(rename = "enqueued")]
    Enqueued,
    #[serde(rename = "coalesced")]
    Coalesced,
    #[serde(rename = "rejected-full")]
    RejectedFull,
    #[serde(rename = "rejected-deadline")]
    RejectedDeadline,
    #[serde(rename = "rejected-invalid")]
    RejectedInvalid,
}

impl QueueAdmission {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Enqueued => "enqueued",
            Self::Coalesced => "coalesced",
            Self::RejectedFull => "rejected-full",
            Self::RejectedDeadline => "rejected-deadline",
            Self::RejectedInvalid => "rejected-invalid",
        }
    }
}

impl FromStr for QueueAdmission {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "enqueued" => Ok(Self::Enqueued),
            "coalesced" => Ok(Self::Coalesced),
            "rejected-full" => Ok(Self::RejectedFull),
            "rejected-deadline" => Ok(Self::RejectedDeadline),
            "rejected-invalid" => Ok(Self::RejectedInvalid),
            _ => Err(DomainValueError::unknown_wire("QueueAdmission")),
        }
    }
}

impl fmt::Display for QueueAdmission {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum RestoreState {
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "planned")]
    Planned,
    #[serde(rename = "ownership-bound")]
    OwnershipBound,
    #[serde(rename = "generation-bound")]
    GenerationBound,
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "applying")]
    Applying,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "invalidated")]
    Invalidated,
}

impl RestoreState {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Idle => "idle",
            Self::Planned => "planned",
            Self::OwnershipBound => "ownership-bound",
            Self::GenerationBound => "generation-bound",
            Self::Queued => "queued",
            Self::Applying => "applying",
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::Invalidated => "invalidated",
        }
    }
}

impl FromStr for RestoreState {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "idle" => Ok(Self::Idle),
            "planned" => Ok(Self::Planned),
            "ownership-bound" => Ok(Self::OwnershipBound),
            "generation-bound" => Ok(Self::GenerationBound),
            "queued" => Ok(Self::Queued),
            "applying" => Ok(Self::Applying),
            "succeeded" => Ok(Self::Succeeded),
            "failed" => Ok(Self::Failed),
            "invalidated" => Ok(Self::Invalidated),
            _ => Err(DomainValueError::unknown_wire("RestoreState")),
        }
    }
}

impl fmt::Display for RestoreState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum EventKind {
    #[serde(rename = "device-available")]
    DeviceAvailable,
    #[serde(rename = "device-sleeping")]
    DeviceSleeping,
    #[serde(rename = "device-unavailable")]
    DeviceUnavailable,
    #[serde(rename = "battery-updated")]
    BatteryUpdated,
    #[serde(rename = "ownership-changed")]
    OwnershipChanged,
    #[serde(rename = "generation-replaced")]
    GenerationReplaced,
    #[serde(rename = "transaction-completed")]
    TransactionCompleted,
    #[serde(rename = "restore-completed")]
    RestoreCompleted,
    #[serde(rename = "diagnostic-raised")]
    DiagnosticRaised,
}

impl EventKind {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::DeviceAvailable => "device-available",
            Self::DeviceSleeping => "device-sleeping",
            Self::DeviceUnavailable => "device-unavailable",
            Self::BatteryUpdated => "battery-updated",
            Self::OwnershipChanged => "ownership-changed",
            Self::GenerationReplaced => "generation-replaced",
            Self::TransactionCompleted => "transaction-completed",
            Self::RestoreCompleted => "restore-completed",
            Self::DiagnosticRaised => "diagnostic-raised",
        }
    }
}

impl FromStr for EventKind {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "device-available" => Ok(Self::DeviceAvailable),
            "device-sleeping" => Ok(Self::DeviceSleeping),
            "device-unavailable" => Ok(Self::DeviceUnavailable),
            "battery-updated" => Ok(Self::BatteryUpdated),
            "ownership-changed" => Ok(Self::OwnershipChanged),
            "generation-replaced" => Ok(Self::GenerationReplaced),
            "transaction-completed" => Ok(Self::TransactionCompleted),
            "restore-completed" => Ok(Self::RestoreCompleted),
            "diagnostic-raised" => Ok(Self::DiagnosticRaised),
            _ => Err(DomainValueError::unknown_wire("EventKind")),
        }
    }
}

impl fmt::Display for EventKind {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum ProtocolErrorKind {
    #[serde(rename = "incompatible-version")]
    IncompatibleVersion,
    #[serde(rename = "unsupported-feature")]
    UnsupportedFeature,
    #[serde(rename = "invalid-request")]
    InvalidRequest,
    #[serde(rename = "ownership-conflict")]
    OwnershipConflict,
    #[serde(rename = "stale-generation")]
    StaleGeneration,
    #[serde(rename = "deadline-exceeded")]
    DeadlineExceeded,
    #[serde(rename = "queue-full")]
    QueueFull,
    #[serde(rename = "transport-failure")]
    TransportFailure,
    #[serde(rename = "internal-failure")]
    InternalFailure,
}

impl ProtocolErrorKind {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::IncompatibleVersion => "incompatible-version",
            Self::UnsupportedFeature => "unsupported-feature",
            Self::InvalidRequest => "invalid-request",
            Self::OwnershipConflict => "ownership-conflict",
            Self::StaleGeneration => "stale-generation",
            Self::DeadlineExceeded => "deadline-exceeded",
            Self::QueueFull => "queue-full",
            Self::TransportFailure => "transport-failure",
            Self::InternalFailure => "internal-failure",
        }
    }
}

impl FromStr for ProtocolErrorKind {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "incompatible-version" => Ok(Self::IncompatibleVersion),
            "unsupported-feature" => Ok(Self::UnsupportedFeature),
            "invalid-request" => Ok(Self::InvalidRequest),
            "ownership-conflict" => Ok(Self::OwnershipConflict),
            "stale-generation" => Ok(Self::StaleGeneration),
            "deadline-exceeded" => Ok(Self::DeadlineExceeded),
            "queue-full" => Ok(Self::QueueFull),
            "transport-failure" => Ok(Self::TransportFailure),
            "internal-failure" => Ok(Self::InternalFailure),
            _ => Err(DomainValueError::unknown_wire("ProtocolErrorKind")),
        }
    }
}

impl fmt::Display for ProtocolErrorKind {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum SideEffectCertainty {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "possible")]
    Possible,
    #[serde(rename = "partial")]
    Partial,
    #[serde(rename = "committed")]
    Committed,
}

impl SideEffectCertainty {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Possible => "possible",
            Self::Partial => "partial",
            Self::Committed => "committed",
        }
    }
}

impl FromStr for SideEffectCertainty {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "none" => Ok(Self::None),
            "possible" => Ok(Self::Possible),
            "partial" => Ok(Self::Partial),
            "committed" => Ok(Self::Committed),
            _ => Err(DomainValueError::unknown_wire("SideEffectCertainty")),
        }
    }
}

impl fmt::Display for SideEffectCertainty {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum LeaseOutcome {
    #[serde(rename = "granted")]
    Granted,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "rejected")]
    Rejected,
}

impl LeaseOutcome {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Granted => "granted",
            Self::Conflict => "conflict",
            Self::Rejected => "rejected",
        }
    }
}

impl FromStr for LeaseOutcome {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "granted" => Ok(Self::Granted),
            "conflict" => Ok(Self::Conflict),
            "rejected" => Ok(Self::Rejected),
            _ => Err(DomainValueError::unknown_wire("LeaseOutcome")),
        }
    }
}

impl fmt::Display for LeaseOutcome {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum ErrorSeverity {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "critical")]
    Critical,
}

impl ErrorSeverity {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Info => "info",
            Self::Warning => "warning",
            Self::Error => "error",
            Self::Critical => "critical",
        }
    }
}

impl FromStr for ErrorSeverity {
    type Err = DomainValueError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "info" => Ok(Self::Info),
            "warning" => Ok(Self::Warning),
            "error" => Ok(Self::Error),
            "critical" => Ok(Self::Critical),
            _ => Err(DomainValueError::unknown_wire("ErrorSeverity")),
        }
    }
}

impl fmt::Display for ErrorSeverity {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}
