# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

from collections import Counter

from ..assurance import DesignCoverageEntry


def design_coverage_markdown(entries: tuple[DesignCoverageEntry, ...]) -> str:
    counts = Counter(entry.status for entry in entries)
    lines = [
        "# Design Coverage",
        "",
        "> Generated by `./hfx generate`. Do not edit manually.",
        "",
        "This ledger maps every section of the governing Design Book to current repository evidence.",
        "Software verification never substitutes for required physical evidence or publication authorization.",
        "",
        "## Summary",
        "",
    ]
    for status in sorted(counts):
        lines.append(f"- `{status}`: {counts[status]}")
    lines.extend(
        [
            "",
            "| Section | Subject | Status | Owner | Physical proof | Release block |",
            "| ---: | --- | --- | --- | --- | --- |",
        ]
    )
    for entry in entries:
        lines.append(
            f"| {entry.section} | {entry.title} | `{entry.status}` | `{entry.owner}` | "
            f"{'required' if entry.physical_evidence_required else 'no'} | "
            f"{'yes' if entry.release_blocking else 'no'} |"
        )
    lines.extend(["", "## Remaining Work And Evidence", ""])
    for entry in entries:
        evidence = ", ".join(f"[`{path}`](../../{path})" for path in entry.evidence)
        lines.extend([f"### {entry.section}. {entry.title}", "", f"Evidence: {evidence}.", ""])
        if entry.remaining:
            lines.extend(f"- {item}" for item in entry.remaining)
        else:
            lines.append("- No remaining gap in the current software scope.")
        lines.append("")
    return "\n".join(lines) + "\n"
