# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

import posixpath

from ..atlas import AtlasNode, RepositoryAtlas


GENERATED_NOTICE = "> Generated by `./hfx generate` from `architecture/repository-atlas.json`. Do not edit manually."


def _link(from_directory: str, target: str, label: str | None = None) -> str:
    relative = posixpath.relpath(target, from_directory)
    return f"[{label or target}]({relative})"


def _bullets(values: tuple[str, ...]) -> list[str]:
    return [f"- {value}" for value in values] or ["- None."]


def _file_bullets(from_directory: str, values: tuple[str, ...]) -> list[str]:
    return [f"- {_link(from_directory, value, f'`{value}`')}" for value in values] or ["- None."]


def _node_links(
    atlas: RepositoryAtlas,
    from_directory: str,
    node_ids: tuple[str, ...],
) -> list[str]:
    by_id = atlas.by_id
    return [
        f"- {_link(from_directory, by_id[item].path + '/README.md', by_id[item].title)}"
        for item in node_ids
    ] or ["- None."]


def impact_summary(atlas: RepositoryAtlas, node: AtlasNode) -> tuple[str, ...]:
    consumers = atlas.used_by[node.id]
    values = [
        f"Regenerate {len(node.generated_files)} declared projection(s).",
        f"Run {', '.join(f'`{item}`' for item in node.verification)}.",
    ]
    if consumers:
        titles = ", ".join(atlas.by_id[item].title for item in consumers)
        values.append(f"Review direct consumers: {titles}.")
    else:
        values.append("No direct subsystem consumer is declared; verify repository-facing outputs.")
    return tuple(values)


def folder_readme(atlas: RepositoryAtlas, node: AtlasNode) -> str:
    used_by = atlas.used_by[node.id]
    lines = [
        f"# {node.title}",
        "",
        GENERATED_NOTICE,
        "",
        node.purpose,
        "",
        f"**Status:** `{node.status}`  ",
        f"**Category:** `{node.category}`  ",
        f"**Atlas ID:** `{node.id}`",
        "",
        "## Ownership",
        "",
        "This subsystem owns:",
        "",
        *_bullets(node.owns),
        "",
        "It must never own:",
        "",
        *_bullets(node.must_not_own),
        "",
        "## Inputs And Outputs",
        "",
        "Inputs:",
        "",
        *_bullets(node.inputs),
        "",
        "Outputs:",
        "",
        *_bullets(node.outputs),
        "",
        "## Public Contracts",
        "",
        *_bullets(node.public_contracts),
        "",
        "## Source And Generated Files",
        "",
        "Canonical files:",
        "",
        *_file_bullets(node.path, node.canonical_files),
        "",
        "Generated projections:",
        "",
        *_file_bullets(node.path, node.generated_files),
        "",
        "## Relationships",
        "",
        "Depends on:",
        "",
        *_node_links(atlas, node.path, node.depends_on),
        "",
        "Used by:",
        "",
        *_node_links(atlas, node.path, used_by),
        "",
        "## Verification",
        "",
        *_bullets(tuple(f"`{item}`" for item in node.verification)),
        "",
        "Change impact:",
        "",
        *_bullets(impact_summary(atlas, node)),
        "",
        "## Limitations",
        "",
        *_bullets(node.limitations),
        "",
        "## Safe Change Workflow",
        "",
    ]
    lines.extend(f"{index}. {item}" for index, item in enumerate(node.safe_change_workflow, 1))
    lines.extend(
        [
            "",
            "## Related Documentation",
            "",
            *_file_bullets(node.path, node.related_docs),
            "",
            f"Return to the {_link(node.path, 'docs/generated/repository-atlas.md', 'Repository Atlas')}.",
        ]
    )
    return "\n".join(lines) + "\n"


def _mermaid_id(identifier: str) -> str:
    return "n_" + identifier.replace("-", "_")


def markdown(atlas: RepositoryAtlas) -> str:
    by_id = atlas.by_id
    categories = sorted({node.category for node in atlas.nodes})
    lines = [
        "# Repository Atlas",
        "",
        GENERATED_NOTICE,
        "",
        "The Atlas is a projection of one canonical repository graph. Folder READMEs, dependency views, source-to-generated relationships, and change-impact guidance are generated from the same nodes.",
        "",
        f"**Subsystems:** {len(atlas.nodes)}  ",
        f"**Categories:** {len(categories)}  ",
        f"**Publication state:** `{atlas.publication_state}`",
        "",
        "## Architecture Map",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for category in categories:
        lines.append(f'    subgraph c_{category.replace("-", "_")}["{category.title()}"]')
        for node in atlas.nodes:
            if node.category == category:
                lines.append(f'        {_mermaid_id(node.id)}["{node.title}"]')
        lines.append("    end")
    for node in atlas.nodes:
        for dependency in node.depends_on:
            lines.append(f"    {_mermaid_id(dependency)} --> {_mermaid_id(node.id)}")
    lines.extend(
        [
            "```",
            "",
            "Arrows run from a dependency to its direct consumer. They describe responsibility and change impact, not runtime calls in every case.",
            "",
            "## Subsystem Index",
            "",
            "| Subsystem | Category | Status | Depends on | Used by | Verification |",
            "| --- | --- | --- | ---: | ---: | --- |",
        ]
    )
    for node in atlas.nodes:
        lines.append(
            f"| [{node.title}](#{node.id}) | `{node.category}` | `{node.status}` | "
            f"{len(node.depends_on)} | {len(atlas.used_by[node.id])} | "
            f"{', '.join(f'`{item}`' for item in node.verification)} |"
        )
    lines.extend(["", "## Subsystems", ""])
    for node in atlas.nodes:
        used_by = atlas.used_by[node.id]
        lines.extend(
            [
                f'<a id="{node.id}"></a>',
                f"### {node.title}",
                "",
                f"`{node.path}` · `{node.category}` · `{node.status}`",
                "",
                node.purpose,
                "",
                f"**Owns:** {'; '.join(node.owns)}.",
                "",
                f"**Must never own:** {'; '.join(node.must_not_own)}.",
                "",
                "**Depends on:** "
                + (", ".join(f"[{by_id[item].title}](#{item})" for item in node.depends_on) or "None"),
                "",
                "**Used by:** "
                + (", ".join(f"[{by_id[item].title}](#{item})" for item in used_by) or "None"),
                "",
                "**Canonical sources:** " + ", ".join(f"`{item}`" for item in node.canonical_files) + ".",
                "",
                "**Generated projections:** "
                + (", ".join(f"`{item}`" for item in node.generated_files) or "None")
                + ".",
                "",
                "**Change impact:** " + " ".join(impact_summary(atlas, node)),
                "",
            ]
        )
    return "\n".join(lines) + "\n"
