# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

import posixpath

from ..atlas import AtlasNode, RepositoryAtlas


GENERATED_NOTICE = "> Generated by `./hfx generate` from `architecture/repository-atlas.json`. Do not edit manually."


def _link(from_directory: str, target: str, label: str | None = None) -> str:
    relative = posixpath.relpath(target, from_directory)
    return f"[{label or target}]({relative})"


def _bullets(values: tuple[str, ...]) -> list[str]:
    return [f"- {value}" for value in values] or ["- None."]


def _file_bullets(from_directory: str, values: tuple[str, ...]) -> list[str]:
    return [f"- {_link(from_directory, value, f'`{value}`')}" for value in values] or ["- None."]


def _node_links(
    atlas: RepositoryAtlas,
    from_directory: str,
    node_ids: tuple[str, ...],
) -> list[str]:
    by_id = atlas.by_id
    return [
        f"- {_link(from_directory, by_id[item].path + '/README.md', by_id[item].title)}"
        for item in node_ids
    ] or ["- None."]


def impact_summary(atlas: RepositoryAtlas, node: AtlasNode) -> tuple[str, ...]:
    consumers = atlas.used_by[node.id]
    values = [
        f"Regenerate {len(node.generated_files)} declared projection(s).",
        f"Run {', '.join(f'`{item}`' for item in node.verification)}.",
    ]
    if consumers:
        titles = ", ".join(atlas.by_id[item].title for item in consumers)
        values.append(f"Review direct consumers: {titles}.")
    else:
        values.append("No direct subsystem consumer is declared; verify repository-facing outputs.")
    return tuple(values)


def folder_readme(atlas: RepositoryAtlas, node: AtlasNode) -> str:
    used_by = atlas.used_by[node.id]
    verification = " ".join(f"`{item}`" for item in node.verification)
    dependencies = ", ".join(
        _link(node.path, atlas.by_id[item].path + "/README.md", atlas.by_id[item].title)
        for item in node.depends_on
    ) or "None"
    consumers = ", ".join(
        _link(node.path, atlas.by_id[item].path + "/README.md", atlas.by_id[item].title)
        for item in used_by
    ) or "None"
    lines = [
        f"# {node.title}",
        "",
        GENERATED_NOTICE,
        "",
        node.purpose,
        "",
        f"`{node.status}` | `{node.category}` | Atlas: `{node.id}`",
        "",
    ]
    if node.id == "documentation":
        lines.extend(
            [
                "## Browse By Need",
                "",
                "| Need | Document |",
                "| --- | --- |",
                "| Project overview | [What HyperFlux Next is](user/overview.md) |",
                "| Installation | [Current package status](generated/installation.md) |",
                "| Troubleshooting | [Safe diagnostic steps](user/troubleshooting.md) |",
                "| Privacy | [Local data boundaries](user/privacy.md) |",
                "| Architecture | [System design](generated/architecture.md) |",
                "| Hardware | [Evidence-backed support](generated/supported-hardware.md) |",
                "| Applications | [Integration status](generated/integrations.md) |",
                "| Readiness | [Release gates](generated/release-gates.md) |",
                "| Repository ownership | [Repository Atlas](generated/repository-atlas.md) |",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "## Start Here",
                "",
                *_file_bullets(node.path, node.related_docs),
                "",
            ]
        )
    if node.id == "device-qualification-console":
        lines.extend(
            [
                "## Run The Installed Console",
                "",
                "```sh",
                "hyperfluxctl doctor",
                "hyperfluxctl qualification serve",
                "```",
                "",
                "Open the loopback URL printed by the second command and leave that terminal running. The console reads the installed Next stack only, never uploads data, and identifies an active HyperFlux V2 installation instead of reporting it as a broken Next bridge.",
                "",
            ]
        )
    lines.extend(
        [
        "## Scope",
        "",
        "**Owns**",
        *_bullets(node.owns),
        "",
        "**Does not own**",
        *_bullets(node.must_not_own),
        "",
        "## Change Here",
        "",
        *_file_bullets(node.path, node.canonical_files),
        "",
        "## Verification",
        "",
        f"Run {verification} after changing this area.",
        "",
        "Before opening a pull request:",
        "",
        *_bullets(impact_summary(atlas, node)),
        "",
        "## Relationships",
        "",
        f"- **Depends on:** {dependencies}",
        f"- **Used by:** {consumers}",
        "",
        f"See the {_link(node.path, 'docs/generated/repository-atlas.md', 'Repository Atlas')} for files, generated projections, contracts, and limitations.",
        ]
    )
    return "\n".join(lines) + "\n"


COLLECTION_TITLES = {
    ".devcontainer": "Development Container",
    ".github": "GitHub Automation",
    "LICENSES": "License Texts",
    "apps": "Installed Applications",
    "generated": "Generated Catalogs",
    "sdk": "Language SDKs",
    "uapi": "Userspace ABI",
}


def collection_readme(atlas: RepositoryAtlas, path: str) -> str:
    children = tuple(node for node in atlas.nodes if node.path.startswith(path + "/"))
    owners: dict[str, tuple[int, int]] = {}
    for node in atlas.nodes:
        canonical = sum(item.startswith(path + "/") for item in node.canonical_files)
        generated = sum(
            item.startswith(path + "/") and item != f"{path}/README.md"
            for item in node.generated_files
        )
        if canonical or generated:
            owners[node.id] = (canonical, generated)
    if path == "LICENSES" and "governance" not in owners:
        owners["governance"] = (1, 0)

    lines = [
        f"# {COLLECTION_TITLES.get(path, path.title())}",
        "",
        GENERATED_NOTICE,
        "",
        "This is a structural collection, not a second source of truth. Follow the authority links below before changing a file.",
        "",
    ]
    if children:
        lines.extend(
            [
                "## Subsystems",
                "",
                "| Area | Purpose |",
                "| --- | --- |",
            ]
        )
        for node in children:
            lines.append(
                f"| {_link(path, node.path + '/README.md', node.title)} | {node.purpose} |"
            )
        lines.append("")
    if owners:
        lines.extend(
            [
                "## Authorities",
                "",
                "| Owner | Canonical inputs | Generated outputs |",
                "| --- | ---: | ---: |",
            ]
        )
        for identifier, (canonical, generated) in sorted(owners.items()):
            node = atlas.by_id[identifier]
            lines.append(
                f"| {_link(path, node.path + '/README.md', node.title)} | {canonical} | {generated} |"
            )
        lines.append("")
    lines.extend(
        [
            "## Safe Changes",
            "",
            "1. Open the owning subsystem above.",
            "2. Change its declared canonical source, not a generated projection.",
            "3. Run `./hfx generate` from the repository root.",
            "4. Run the verification named by that subsystem.",
            "",
            f"See the {_link(path, 'docs/generated/repository-atlas.md', 'Repository Atlas')} for the complete ownership graph.",
        ]
    )
    return "\n".join(lines) + "\n"


def _mermaid_id(identifier: str) -> str:
    return "n_" + identifier.replace("-", "_")


def markdown(atlas: RepositoryAtlas) -> str:
    by_id = atlas.by_id
    categories = sorted({node.category for node in atlas.nodes})
    lines = [
        "# Repository Atlas",
        "",
        GENERATED_NOTICE,
        "",
        "The Atlas is a projection of one canonical repository graph. Folder READMEs, dependency views, source-to-generated relationships, and change-impact guidance are generated from the same nodes.",
        "",
        f"- **Subsystems:** {len(atlas.nodes)}",
        f"- **Categories:** {len(categories)}",
        f"- **Publication state:** `{atlas.publication_state}`",
        "",
        "## Architecture Map",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for category in categories:
        lines.append(f'    subgraph c_{category.replace("-", "_")}["{category.title()}"]')
        for node in atlas.nodes:
            if node.category == category:
                lines.append(f'        {_mermaid_id(node.id)}["{node.title}"]')
        lines.append("    end")
    for node in atlas.nodes:
        for dependency in node.depends_on:
            lines.append(f"    {_mermaid_id(dependency)} --> {_mermaid_id(node.id)}")
    lines.extend(
        [
            "```",
            "",
            "Arrows run from a dependency to its direct consumer. They describe responsibility and change impact, not runtime calls in every case.",
            "",
            "## Subsystem Index",
            "",
            "| Subsystem | Category | Status | Depends on | Used by | Verification |",
            "| --- | --- | --- | ---: | ---: | --- |",
        ]
    )
    for node in atlas.nodes:
        lines.append(
            f"| [{node.title}](#{node.id}) | `{node.category}` | `{node.status}` | "
            f"{len(node.depends_on)} | {len(atlas.used_by[node.id])} | "
            f"{', '.join(f'`{item}`' for item in node.verification)} |"
        )
    lines.extend(["", "## Subsystems", ""])
    for node in atlas.nodes:
        used_by = atlas.used_by[node.id]
        lines.extend(
            [
                f'<a id="{node.id}"></a>',
                "<details>",
                f"<summary><strong>{node.title}</strong> · {node.category} · {node.status}</summary>",
                "",
                f"### {node.title}",
                "",
                f"`{node.path}` · `{node.category}` · `{node.status}`",
                "",
                node.purpose,
                "",
                f"**Owns:** {'; '.join(node.owns)}.",
                "",
                f"**Must never own:** {'; '.join(node.must_not_own)}.",
                "",
                "**Depends on:** "
                + (", ".join(f"[{by_id[item].title}](#{item})" for item in node.depends_on) or "None"),
                "",
                "**Used by:** "
                + (", ".join(f"[{by_id[item].title}](#{item})" for item in used_by) or "None"),
                "",
                "**Canonical sources:** " + ", ".join(f"`{item}`" for item in node.canonical_files) + ".",
                "",
                "**Generated projections:** "
                + (", ".join(f"`{item}`" for item in node.generated_files) or "None")
                + ".",
                "",
                "**Change impact:** " + " ".join(impact_summary(atlas, node)),
                "",
                "</details>",
                "",
            ]
        )
    return "\n".join(lines) + "\n"
