# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

from ..distributions import DistributionCatalog
from ..linux_runtime import LinuxRuntime


def markdown(catalog: DistributionCatalog, runtime: LinuxRuntime) -> str:
    lines = [
        "# Distribution Packages",
        "",
        "> Generated by `./hfx generate`. Do not edit manually.",
        "",
        f"Canonical distribution digest: `{catalog.source_sha256}`.",
        "",
        f"Every target packages the same `{runtime.product.package_name}` canonical staged payload. "
        "Distribution wrappers add only native metadata, lifecycle hooks, and Python discovery.",
        "",
        "| Target | Architectures | Required packages | Optional integrations |",
        "| --- | --- | --- | --- |",
    ]
    for target in catalog.targets.values():
        architectures = ", ".join(
            f"`{source}` to `{destination}`"
            for source, destination in target.architectures.items()
        )
        dependencies = ", ".join(f"`{item}`" for item in target.dependencies)
        optional = ", ".join(
            f"`{item.package}`" for item in target.optional_dependencies
        )
        lines.append(
            f"| `{target.id}` | {architectures} | {dependencies} | {optional} |"
        )
    lines.extend(
        [
            "",
            "## Lifecycle Contract",
            "",
            "- Fresh installation creates conservative read-only configuration and does not enable the bridge.",
            "- Reinstall and compatible update preserve configuration and resume only a previously active bridge.",
            "- A changed in-use kernel module keeps the bridge stopped and reports reboot or explicit receiver-disconnect activation.",
            "- Start preparation validates the installed module and migrates configuration before the bridge.",
            "- Start confirmation removes rollback state only after the bridge has started successfully.",
            "- Uninstall stops the bridge but leaves package-manager-managed configuration policy explicit.",
            "",
            "## Python Integration",
            "",
            f"Pure Python modules live at `{runtime.operations.python_module_directory}`. "
            "Each distribution adds one native `.pth` file so application entry-point discovery works without binding the common payload to a Python minor version.",
            "Targets whose discovery path contains the Python minor version declare a matching lower bound and exclusive upper bound. A package manager therefore cannot accept an artifact whose `.pth` file its interpreter cannot discover.",
            "",
            "## Kernel Headers",
            "",
            "DKMS requires headers matching the installed kernel. Header package names are intentionally not guessed in package metadata because they vary by kernel flavor, architecture, and distribution.",
            "",
        ]
    )
    return "\n".join(lines)
