# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

from typing import Any


HEADER_RUST = "// Generated by ./hfx generate. Do not edit manually.\n// SPDX-License-Identifier: GPL-2.0-only\n"
HEADER_CPP = "// Generated by ./hfx generate. Do not edit manually.\n// SPDX-License-Identifier: GPL-2.0-only\n"
HEADER_PYTHON = '"""Generated by ./hfx generate. Do not edit manually."""\n\n'

RUST_MAXIMUM = {
    "u8": 255,
    "u16": 65_535,
    "u32": 4_294_967_295,
    "u64": 18_446_744_073_709_551_615,
}


def _variant(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in value.replace(".", "-").split("-"))


def rust_types(catalog: dict[str, Any]) -> str:
    lines = [
        HEADER_RUST.rstrip(),
        "",
        "use serde::{Deserialize, Serialize};",
        "use std::fmt;",
        "use std::str::FromStr;",
        "",
        "#[derive(Clone, Debug, Eq, PartialEq)]",
        "pub struct DomainValueError {",
        "    type_name: &'static str,",
        "    reason: &'static str,",
        "}",
        "",
        "impl DomainValueError {",
        "    const fn new(type_name: &'static str, reason: &'static str) -> Self {",
        "        Self { type_name, reason }",
        "    }",
        "",
        "    const fn unknown_wire(type_name: &'static str) -> Self {",
        '        Self::new(type_name, "unknown wire value")',
        "    }",
        "}",
        "",
        "impl fmt::Display for DomainValueError {",
        "    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {",
        '        write!(formatter, "invalid {}: {}", self.type_name, self.reason)',
        "    }",
        "}",
        "",
        "impl std::error::Error for DomainValueError {}",
        "",
    ]
    for item in catalog["numeric_types"]:
        name = item["name"]
        rust = item["rust"]
        minimum = item["minimum"]
        maximum = item["maximum"]
        bounds = []
        if minimum > 0:
            bounds.append("value < Self::MIN")
        if maximum < RUST_MAXIMUM[rust]:
            bounds.append("value > Self::MAX")
        lines.extend(
            [
                "#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]",
                f"#[serde(try_from = \"{rust}\", into = \"{rust}\")]",
                f"pub struct {name}({rust});",
                "",
                f"impl {name} {{",
                f"    pub const MIN: {rust} = {minimum:_};",
                f"    pub const MAX: {rust} = {maximum:_};",
                "",
                "    #[must_use]",
                f"    pub const fn get(self) -> {rust} {{",
                "        self.0",
                "    }",
                "}",
                "",
                f"impl TryFrom<{rust}> for {name} {{",
                "    type Error = DomainValueError;",
                "",
                f"    fn try_from(value: {rust}) -> Result<Self, Self::Error> {{",
            ]
        )
        if bounds:
            lines.extend(
                [
                    f"        if {' || '.join(bounds)} {{",
                    "            return Err(DomainValueError::new(",
                    f'                "{name}",',
                    '                "outside the canonical range",',
                    "            ));",
                    "        }",
                ]
            )
        lines.extend(
            [
                "        Ok(Self(value))",
                "    }",
                "}",
                "",
                f"impl From<{name}> for {rust} {{",
                f"    fn from(value: {name}) -> Self {{",
                "        value.0",
                "    }",
                "}",
                "",
                f"impl fmt::Display for {name} {{",
                "    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {",
                "        self.0.fmt(formatter)",
                "    }",
                "}",
                "",
            ]
        )
    for item in catalog["string_types"]:
        name = item["name"]
        minimum = item["minimum_length"]
        maximum = item["maximum_length"]
        lines.extend(
            [
                "#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]",
                "#[serde(try_from = \"String\", into = \"String\")]",
                f"pub struct {name}(String);",
                "",
                f"impl {name} {{",
                f"    pub const MIN_LENGTH: usize = {minimum};",
                f"    pub const MAX_LENGTH: usize = {maximum};",
                "",
                "    #[must_use]",
                "    pub fn as_str(&self) -> &str {",
                "        &self.0",
                "    }",
                "}",
                "",
                f"impl TryFrom<String> for {name} {{",
                "    type Error = DomainValueError;",
                "",
                "    fn try_from(value: String) -> Result<Self, Self::Error> {",
                "        if value.len() < Self::MIN_LENGTH || value.len() > Self::MAX_LENGTH {",
                "            return Err(DomainValueError::new(",
                f'                "{name}",',
                '                "outside the canonical length",',
                "            ));",
                "        }",
                "        Ok(Self(value))",
                "    }",
                "}",
                "",
                f"impl TryFrom<&str> for {name} {{",
                "    type Error = DomainValueError;",
                "",
                "    fn try_from(value: &str) -> Result<Self, Self::Error> {",
                "        Self::try_from(value.to_owned())",
                "    }",
                "}",
                "",
                f"impl From<{name}> for String {{",
                f"    fn from(value: {name}) -> Self {{",
                "        value.0",
                "    }",
                "}",
                "",
                f"impl fmt::Display for {name} {{",
                "    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {",
                "        self.0.fmt(formatter)",
                "    }",
                "}",
                "",
            ]
        )
    for enum in catalog["enums"]:
        name = enum["name"]
        lines.extend(
            [
                "#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]",
                f"pub enum {name} {{",
            ]
        )
        for value in enum["values"]:
            lines.extend([f'    #[serde(rename = "{value}")]', f"    {_variant(value)},"])
        lines.extend(["}", "", f"impl {name} {{", "    #[must_use]", "    pub const fn as_str(self) -> &'static str {", "        match self {"])
        lines.extend(f'            Self::{_variant(value)} => "{value}",' for value in enum["values"])
        lines.extend(["        }", "    }", "}", "", f"impl FromStr for {name} {{", "    type Err = DomainValueError;", "", "    fn from_str(value: &str) -> Result<Self, Self::Err> {", "        match value {"])
        lines.extend(f'            "{value}" => Ok(Self::{_variant(value)}),' for value in enum["values"])
        lines.extend(
            [
                f'            _ => Err(DomainValueError::unknown_wire("{name}")),',
                "        }",
                "    }",
                "}",
                "",
                f"impl fmt::Display for {name} {{",
                "    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {",
                "        formatter.write_str(self.as_str())",
                "    }",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def python_types(catalog: dict[str, Any]) -> str:
    lines = [
        HEADER_PYTHON.rstrip(),
        "",
        "from dataclasses import dataclass",
        "from enum import Enum",
        "",
    ]
    exports: list[str] = []
    for item in catalog["numeric_types"]:
        name = item["name"]
        exports.append(name)
        lines.extend(
            [
                "@dataclass(frozen=True, slots=True)",
                f"class {name}:",
                "    value: int",
                "",
                "    def __post_init__(self) -> None:",
                "        if isinstance(self.value, bool) or not isinstance(self.value, int):",
                f'            raise TypeError("{name} requires an integer")',
                f"        if not {item['minimum']} <= self.value <= {item['maximum']}:",
                f'            raise ValueError("{name} is outside the canonical range")',
                "",
                "",
            ]
        )
    for item in catalog["string_types"]:
        name = item["name"]
        exports.append(name)
        lines.extend(
            [
                "@dataclass(frozen=True, slots=True)",
                f"class {name}:",
                "    value: str",
                "",
                "    def __post_init__(self) -> None:",
                "        if not isinstance(self.value, str):",
                f'            raise TypeError("{name} requires a string")',
                f"        if not {item['minimum_length']} <= len(self.value) <= {item['maximum_length']}:",
                f'            raise ValueError("{name} is outside the canonical length")',
                "",
                "",
            ]
        )
    for enum in catalog["enums"]:
        name = enum["name"]
        exports.append(name)
        lines.append(f"class {name}(str, Enum):")
        for value in enum["values"]:
            lines.append(f'    {value.replace("-", "_").replace(".", "_").upper()} = "{value}"')
        lines.extend(["", ""])
    lines.append("__all__ = [")
    lines.extend(f'    "{name}",' for name in exports)
    lines.extend(["]", ""])
    return "\n".join(lines)


def cpp_types(catalog: dict[str, Any]) -> str:
    lines = [
        HEADER_CPP.rstrip(),
        "",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <optional>",
        "#include <string>",
        "#include <string_view>",
        "#include <utility>",
        "",
        "namespace hyperflux",
        "{",
        "",
    ]
    for item in catalog["numeric_types"]:
        name = item["name"]
        cpp = item["cpp"]
        rust_equivalent = {
            "std::uint8_t": "u8",
            "std::uint16_t": "u16",
            "std::uint32_t": "u32",
            "std::uint64_t": "u64",
        }[cpp]
        bounds = []
        if item["minimum"] > 0:
            bounds.append("value < minimum")
        if item["maximum"] < RUST_MAXIMUM[rust_equivalent]:
            bounds.append("value > maximum")
        maximum = f"{item['maximum']}ULL" if cpp == "std::uint64_t" else str(item["maximum"])
        lines.extend(
            [
                f"class {name}",
                "{",
                "public:",
                f"    using value_type = {cpp};",
                f"    static constexpr value_type minimum = {item['minimum']};",
                f"    static constexpr value_type maximum = {maximum};",
                "",
                f"    [[nodiscard]] static constexpr std::optional<{name}> from(value_type value)",
                "    {",
            ]
        )
        if bounds:
            lines.extend(
                [
                    f"        if({' || '.join(bounds)})",
                    "        {",
                    "            return std::nullopt;",
                    "        }",
                ]
            )
        lines.extend(
            [
                f"        return {name}(value);",
                "    }",
                "",
                "    [[nodiscard]] constexpr value_type value() const { return value_; }",
                f"    friend constexpr bool operator==(const {name}&, const {name}&) = default;",
                "",
                "private:",
                f"    explicit constexpr {name}(value_type value) : value_(value) {{}}",
                "    value_type value_;",
                "};",
                "",
            ]
        )
    for item in catalog["string_types"]:
        name = item["name"]
        lines.extend(
            [
                f"class {name}",
                "{",
                "public:",
                f"    static constexpr std::size_t minimum_length = {item['minimum_length']};",
                f"    static constexpr std::size_t maximum_length = {item['maximum_length']};",
                "",
                f"    [[nodiscard]] static std::optional<{name}> from(std::string_view value)",
                "    {",
                "        if(value.size() < minimum_length || value.size() > maximum_length)",
                "        {",
                "            return std::nullopt;",
                "        }",
                f"        return {name}(std::string(value));",
                "    }",
                "",
                "    [[nodiscard]] std::string_view value() const { return value_; }",
                f"    friend bool operator==(const {name}&, const {name}&) = default;",
                "",
                "private:",
                f"    explicit {name}(std::string value) : value_(std::move(value)) {{}}",
                "    std::string value_;",
                "};",
                "",
            ]
        )
    for enum in catalog["enums"]:
        name = enum["name"]
        lines.append(f"enum class {name}")
        lines.append("{")
        lines.extend(f"    {_variant(value)}," for value in enum["values"])
        lines.extend(["};", "", f"[[nodiscard]] constexpr std::string_view to_string({name} value)", "{", "    switch(value)", "    {"])
        lines.extend(f'        case {name}::{_variant(value)}: return "{value}";' for value in enum["values"])
        lines.extend(["    }", '    return "unknown";', "}", ""])
    lines.extend(["} // namespace hyperflux", ""])
    return "\n".join(lines)


def markdown(catalog: dict[str, Any]) -> str:
    lines = [
        "# Domain Types",
        "",
        "> Generated by `./hfx generate`. Do not edit manually.",
        "",
        "These types prevent semantically different values from being passed interchangeably.",
        "",
        "## Bounded Numeric Types",
        "",
        "| Type | Wire name | Range |",
        "| --- | --- | --- |",
    ]
    lines.extend(f"| `{item['name']}` | `{item['wire']}` | {item['minimum']} to {item['maximum']} |" for item in catalog["numeric_types"])
    lines.extend(["", "## Opaque String Types", "", "| Type | Wire name | Length |", "| --- | --- | --- |"])
    lines.extend(f"| `{item['name']}` | `{item['wire']}` | {item['minimum_length']} to {item['maximum_length']} bytes |" for item in catalog["string_types"])
    lines.extend(["", "## Enumerations", ""])
    for enum in catalog["enums"]:
        values = ", ".join(f"`{value}`" for value in enum["values"])
        lines.append(f"- `{enum['name']}`: {values}")
    return "\n".join(lines) + "\n"
