# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

import json
from typing import Any

import yaml

from ..governance import GitHubGovernance


NOTICE = "# Generated by ./hfx generate. Do not edit manually.\n"


class _ReadableDumper(yaml.SafeDumper):
    def ignore_aliases(self, data: Any) -> bool:
        return True


def _represent_string(dumper: yaml.SafeDumper, value: str) -> yaml.ScalarNode:
    style = "|" if "\n" in value else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)


_ReadableDumper.add_representer(str, _represent_string)


def _yaml(value: dict[str, Any], governance: GitHubGovernance) -> str:
    rendered = yaml.dump(
        value,
        Dumper=_ReadableDumper,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=False,
        width=1000,
    )
    for action in governance.actions:
        rendered = rendered.replace(
            f"uses: {action.uses}\n",
            f"uses: {action.uses} # {action.version}\n",
        )
    return NOTICE + rendered


def _checkout(governance: GitHubGovernance) -> dict[str, Any]:
    return {
        "name": "Check out exact source",
        "uses": governance.actions_by_id["checkout"].uses,
        "with": {"fetch-depth": 0, "persist-credentials": False},
    }


def _cache(governance: GitHubGovernance) -> dict[str, Any]:
    return {
        "name": "Restore verified software caches",
        "uses": governance.actions_by_id["cache"].uses,
        "with": {
            "path": ".hfx/upstreams\ntarget\n",
            "key": "hfx-${{ runner.os }}-${{ hashFiles('Cargo.lock', 'toolchains/development-environment.json', 'integrations/catalog.json') }}",
            "restore-keys": "hfx-${{ runner.os }}-\n",
        },
    }


def _build_environment(governance: GitHubGovernance) -> list[dict[str, Any]]:
    return [
        {
            "name": "Set up Buildx",
            "uses": governance.actions_by_id["setup-buildx"].uses,
        },
        {
            "name": "Build the pinned development environment",
            "uses": governance.actions_by_id["build-push"].uses,
            "with": {
                "context": ".",
                "file": ".devcontainer/Containerfile",
                "load": True,
                "push": False,
                "tags": "${{ env.HFX_CI_IMAGE }}",
                "cache-from": "type=gha,scope=hyperflux-next-development",
                "cache-to": "type=gha,mode=max,scope=hyperflux-next-development,ignore-error=true",
            },
        },
    ]


def _upload(
    governance: GitHubGovernance,
    *,
    name: str,
    path: str,
    retention_days: int,
) -> dict[str, Any]:
    return {
        "name": f"Upload {name}",
        "if": "${{ always() }}",
        "uses": governance.actions_by_id["upload-artifact"].uses,
        "with": {
            "name": name,
            "path": path,
            "if-no-files-found": "error",
            "retention-days": retention_days,
        },
    }


def _verification_summary(output: str) -> dict[str, Any]:
    return {
        "name": "Publish bounded verification summary",
        "if": "${{ always() }}",
        "env": {"HFX_SOURCE_REVISION": "${{ github.sha }}"},
        "run": (
            f'./hfx ci summary --result {output}/result.json '
            '--output "$GITHUB_STEP_SUMMARY" --source-revision "$HFX_SOURCE_REVISION"'
        ),
    }


def verification_workflow(governance: GitHubGovernance) -> str:
    steps = [_checkout(governance), _cache(governance), *_build_environment(governance)]
    steps.extend(
        [
            {
                "name": "Prepare exact upstream sources",
                "run": './hfx ci prepare --image "$HFX_CI_IMAGE"',
            },
            {
                "name": "Run fail-closed changed-path verification",
                "env": {
                    "HFX_CHANGED_FROM": "${{ github.event.pull_request.base.sha || github.event.before || '' }}"
                },
                "run": './hfx ci verify --image "$HFX_CI_IMAGE" --lane fast --output build/ci/fast --changed-from "$HFX_CHANGED_FROM"',
            },
            _verification_summary("build/ci/fast"),
            _upload(
                governance,
                name="hyperflux-fast-evidence",
                path="build/ci/fast",
                retention_days=14,
            ),
        ]
    )
    value = {
        "name": "Verification",
        "on": {
            "pull_request": {},
            "push": {"branches": [governance.default_branch]},
            "workflow_dispatch": {},
        },
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "verification-${{ github.workflow }}-${{ github.ref }}",
            "cancel-in-progress": True,
        },
        "env": {"HFX_CI_IMAGE": governance.development_image},
        "jobs": {
            "fast-software": {
                "name": "Fast software",
                "runs-on": governance.runner,
                "timeout-minutes": 45,
                "steps": steps,
            }
        },
    }
    return _yaml(value, governance)


def full_verification_workflow(governance: GitHubGovernance) -> str:
    steps = [_checkout(governance), _cache(governance), *_build_environment(governance)]
    steps.extend(
        [
            {
                "name": "Prepare exact upstream sources",
                "run": './hfx ci prepare --image "$HFX_CI_IMAGE"',
            },
            {
                "name": "Run the complete software graph",
                "run": './hfx ci verify --image "$HFX_CI_IMAGE" --lane full --output build/ci/full',
            },
            _verification_summary("build/ci/full"),
            _upload(
                governance,
                name="hyperflux-full-evidence",
                path="build/ci/full",
                retention_days=30,
            ),
        ]
    )
    value = {
        "name": "Full verification",
        "on": {
            "workflow_dispatch": {},
            "schedule": [{"cron": governance.full_verification_cron}],
        },
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "full-verification-${{ github.ref }}",
            "cancel-in-progress": False,
        },
        "env": {"HFX_CI_IMAGE": governance.development_image},
        "jobs": {
            "full-software": {
                "name": "Full software",
                "runs-on": governance.runner,
                "timeout-minutes": 90,
                "steps": steps,
            }
        },
    }
    return _yaml(value, governance)


def documentation_workflow(governance: GitHubGovernance) -> str:
    steps = [_checkout(governance), *_build_environment(governance)]
    steps.extend(
        [
            {
                "name": "Build and verify the offline portal",
                "run": './hfx ci docs --image "$HFX_CI_IMAGE" --output build/ci/portal',
            },
            _upload(
                governance,
                name="hyperflux-documentation-portal",
                path="build/ci/portal",
                retention_days=14,
            ),
        ]
    )
    value = {
        "name": "Documentation",
        "on": {
            "workflow_dispatch": {},
            "push": {
                "branches": [governance.default_branch],
                "paths": [
                    "docs/**",
                    "schemas/documentation-portal.schema.json",
                    "tools/hfxdev/portal*.py",
                    "tools/hfxdev/generators/**",
                    "governance/github.json",
                ],
            },
        },
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "documentation-${{ github.ref }}",
            "cancel-in-progress": True,
        },
        "env": {"HFX_CI_IMAGE": governance.development_image},
        "jobs": {
            "portal-artifact": {
                "name": "Offline portal artifact",
                "runs-on": governance.runner,
                "timeout-minutes": 30,
                "steps": steps,
            }
        },
    }
    return _yaml(value, governance)


def codeql_workflow(governance: GitHubGovernance) -> str:
    codeql = governance.actions_by_id["codeql"]
    value = {
        "name": "CodeQL",
        "on": {
            "pull_request": {},
            "push": {"branches": [governance.default_branch]},
            "schedule": [{"cron": "43 2 * * 4"}],
        },
        "permissions": {"contents": "read", "security-events": "write"},
        "concurrency": {
            "group": "codeql-${{ github.workflow }}-${{ github.ref }}",
            "cancel-in-progress": True,
        },
        "jobs": {
            "analyze": {
                "name": "Analyze (${{ matrix.language }})",
                "runs-on": governance.runner,
                "timeout-minutes": 45,
                "strategy": {
                    "fail-fast": False,
                    "matrix": {"language": ["c-cpp", "python"]},
                },
                "steps": [
                    _checkout(governance),
                    {
                        "name": "Initialize CodeQL",
                        "uses": f"{codeql.repository}/init@{codeql.commit}",
                        "with": {
                            "languages": "${{ matrix.language }}",
                            "build-mode": "none",
                        },
                    },
                    {
                        "name": "Analyze source",
                        "uses": f"{codeql.repository}/analyze@{codeql.commit}",
                        "with": {"category": "/language:${{ matrix.language }}"},
                    },
                ],
            }
        },
    }
    rendered = _yaml(value, governance)
    rendered = rendered.replace(
        f"uses: {codeql.repository}/init@{codeql.commit}\n",
        f"uses: {codeql.repository}/init@{codeql.commit} # {codeql.version}\n",
    ).replace(
        f"uses: {codeql.repository}/analyze@{codeql.commit}\n",
        f"uses: {codeql.repository}/analyze@{codeql.commit} # {codeql.version}\n",
    )
    return rendered


def dependency_review_workflow(governance: GitHubGovernance) -> str:
    value = {
        "name": "Dependency review",
        "on": {"pull_request": {}},
        "permissions": {"contents": "read"},
        "jobs": {
            "dependency-review": {
                "name": "Dependency review",
                "runs-on": governance.runner,
                "timeout-minutes": 15,
                "steps": [
                    _checkout(governance),
                    {
                        "name": "Review dependency changes",
                        "uses": governance.actions_by_id["dependency-review"].uses,
                        "with": {
                            "fail-on-severity": "moderate",
                            "license-check": "true",
                            "vulnerability-check": "true",
                        },
                    },
                ],
            }
        },
    }
    return _yaml(value, governance)


def dependabot(governance: GitHubGovernance) -> str:
    schedule = {"interval": "weekly", "day": governance.dependency_update_day}
    value = {
        "version": 2,
        "updates": [
            {
                "package-ecosystem": "github-actions",
                "directory": "/",
                "schedule": schedule,
                "open-pull-requests-limit": 5,
                "groups": {"github-actions": {"patterns": ["*"]}},
                "labels": ["area: security"],
            },
            {
                "package-ecosystem": "cargo",
                "directory": "/",
                "schedule": schedule,
                "open-pull-requests-limit": 5,
                "groups": {"rust-dependencies": {"patterns": ["*"]}},
                "labels": ["area: security"],
            },
            *[
                {
                    "package-ecosystem": "pip",
                    "directory": directory,
                    "schedule": schedule,
                    "open-pull-requests-limit": 3,
                    "groups": {"python-dependencies": {"patterns": ["*"]}},
                    "labels": ["area: integration", "area: security"],
                }
                for directory in (
                    "/sdk/python",
                    "/integrations/openrazer/compatibility",
                    "/integrations/polychromatic",
                )
            ],
        ],
    }
    return _yaml(value, governance)


def codeowners(governance: GitHubGovernance) -> str:
    lines = [NOTICE.rstrip(), "", f"* {' '.join(governance.default_owners)}"]
    for rule in governance.ownership_rules:
        lines.extend(f"{path} {' '.join(rule.owners)}" for path in rule.paths)
    return "\n".join(lines) + "\n"


def pull_request_template() -> str:
    return """<!-- Generated by ./hfx generate. Do not edit manually. -->

## Outcome

<!-- Describe the user-visible or engineering outcome, not only the changed files. -->

## Affected Domains

- [ ] Kernel transport or UAPI
- [ ] Bridge, protocol, or SDK
- [ ] Hardware profiles or application integrations
- [ ] Packaging or lifecycle
- [ ] Verification, assurance, or governance
- [ ] Documentation only

## Contract Impact

- Canonical authority changed:
- Generated outputs refreshed:
- Schema or protocol compatibility:
- Package or activation behavior:
- Performance budget impact:
- Privacy or support-bundle impact:
- Release-gate impact:
- Evidence level: proposal / software / lifecycle / physical
- Qualification state: unknown / candidate / route qualified / fully qualified / blocked

## Evidence

- Source revision:
- Selected verification nodes and timings:
- Generated freshness:
- Fast verification evidence:
- Full software evidence, when required:
- Physical evidence, when separately authorized:

## Interlocks

- [ ] This change performs no hardware writes unless separately authorized and recorded.
- [ ] This change does not create a release, tag, Pages deployment, or publication authorization.
- [ ] User-facing documentation contains no internal engineering mission identifiers.
"""


def _issue_form(
    governance: GitHubGovernance,
    *,
    name: str,
    description: str,
    title: str,
    labels: list[str],
    body: list[dict[str, Any]],
) -> str:
    return _yaml(
        {
            "name": name,
            "description": description,
            "title": title,
            "labels": labels,
            "body": body,
        },
        governance,
    )


def bug_report(governance: GitHubGovernance) -> str:
    return _issue_form(
        governance,
        name="Bug report",
        description="Report incorrect behavior with privacy-safe diagnostic context.",
        title="[Bug]: ",
        labels=["kind: bug"],
        body=[
            {
                "type": "markdown",
                "attributes": {
                    "value": "Run `hyperfluxctl doctor` first. Never attach hardware serials, raw HID or USB payloads, private paths, captures, or memory dumps."
                },
            },
            {
                "type": "textarea",
                "id": "outcome",
                "attributes": {
                    "label": "What happened?",
                    "description": "Describe the observed result and the result you expected.",
                    "placeholder": "Observed:\nExpected:",
                },
                "validations": {"required": True},
            },
            {
                "type": "input",
                "id": "environment",
                "attributes": {
                    "label": "Environment",
                    "description": "Distribution, kernel, package version, and application adapter.",
                    "placeholder": "Arch Linux; 6.x; 0.x; OpenRGB",
                },
                "validations": {"required": True},
            },
            {
                "type": "input",
                "id": "doctor-reference",
                "attributes": {
                    "label": "Doctor reference",
                    "description": "The privacy-safe hfx reference printed by hyperfluxctl doctor.",
                    "placeholder": "hfx-...",
                },
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "support-preview",
                "attributes": {
                    "label": "Support preview",
                    "description": "Paste `hyperfluxctl support-bundle --preview`. This previews bounded contents and performs no upload.",
                    "render": "json",
                },
            },
            {
                "type": "checkboxes",
                "id": "privacy",
                "attributes": {
                    "label": "Privacy confirmation",
                    "options": [
                        {
                            "label": "I removed serials, stable host identifiers, private paths, and raw transport payloads.",
                            "required": True,
                        }
                    ],
                },
            },
        ],
    )


def hardware_qualification(governance: GitHubGovernance) -> str:
    return _issue_form(
        governance,
        name="Hardware qualification",
        description="Propose evidence for a device or receiver path without authorizing writes.",
        title="[Hardware]: ",
        labels=["evidence: hardware"],
        body=[
            {
                "type": "markdown",
                "attributes": {
                    "value": "Opening this issue does not authorize receiver queries, RGB writes, suspend, or any other physical test. A separate bounded approval is always required."
                },
            },
            {
                "type": "input",
                "id": "model",
                "attributes": {"label": "Exact marketed model", "placeholder": "Vendor and model"},
                "validations": {"required": True},
            },
            {
                "type": "input",
                "id": "pid",
                "attributes": {"label": "Public product ID", "placeholder": "0x0000"},
                "validations": {"required": True},
            },
            {
                "type": "dropdown",
                "id": "route",
                "attributes": {
                    "label": "Connection route",
                    "options": ["HyperFlux receiver", "Direct wireless", "Direct wired", "Unknown"],
                },
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "capabilities",
                "attributes": {
                    "label": "Observed capabilities",
                    "description": "Identity, lighting zones, battery, connection, controls, lifecycle, or other bounded observations.",
                },
                "validations": {"required": True},
            },
            {
                "type": "input",
                "id": "doctor-reference",
                "attributes": {
                    "label": "Doctor reference, when available",
                    "description": "The privacy-safe hfx reference printed by hyperfluxctl doctor.",
                    "placeholder": "hfx-...",
                },
            },
            {
                "type": "textarea",
                "id": "support-preview",
                "attributes": {
                    "label": "Support preview, when available",
                    "description": "Paste `hyperfluxctl support-bundle --preview`. This performs no upload or active receiver query.",
                    "render": "json",
                },
            },
            {
                "type": "dropdown",
                "id": "evidence-class",
                "attributes": {
                    "label": "Available evidence",
                    "options": ["Read-only software evidence", "Watched physical evidence", "Public upstream metadata", "Proposal only"],
                },
                "validations": {"required": True},
            },
            {
                "type": "checkboxes",
                "id": "privacy",
                "attributes": {
                    "label": "Privacy confirmation",
                    "options": [
                        {
                            "label": "No serial, stable host identifier, raw transport payload, or private path is included.",
                            "required": True,
                        }
                    ],
                },
            },
        ],
    )


def feature_request(governance: GitHubGovernance) -> str:
    return _issue_form(
        governance,
        name="Feature request",
        description="Describe a universal user workflow or capability gap.",
        title="[Feature]: ",
        labels=["kind: feature"],
        body=[
            {
                "type": "dropdown",
                "id": "area",
                "attributes": {
                    "label": "Primary area",
                    "options": [
                        "Applications and integrations",
                        "Device knowledge and qualification",
                        "Kernel, bridge, or SDK",
                        "Packaging and lifecycle",
                        "Documentation and diagnostics",
                        "Governance and tooling",
                    ],
                },
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "workflow",
                "attributes": {
                    "label": "User workflow",
                    "description": "What should a normal user be able to accomplish?",
                },
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "gap",
                "attributes": {
                    "label": "Current gap",
                    "description": "What is missing, confusing, or unnecessarily device-specific today?",
                },
                "validations": {"required": True},
            },
            {
                "type": "checkboxes",
                "id": "universality",
                "attributes": {
                    "label": "Universality",
                    "options": [
                        {
                            "label": "The proposal is not tied only to one host, serial, receiver generation, or private device state.",
                            "required": True,
                        }
                    ],
                },
            },
            {
                "type": "textarea",
                "id": "evidence-boundary",
                "attributes": {
                    "label": "Evidence needed",
                    "description": "Which software, lifecycle, or physical evidence would make this proposal safe to ship?",
                },
            },
        ],
    )


def issue_config(governance: GitHubGovernance) -> str:
    value = {
        "blank_issues_enabled": False,
        "contact_links": [
            {
                "name": "Report a security vulnerability privately",
                "url": f"https://github.com/{governance.owner}/{governance.repository}/security/advisories/new",
                "about": "Do not disclose vulnerabilities or sensitive diagnostics in a public issue.",
            }
        ],
    }
    return _yaml(value, governance)


def protection_plan(governance: GitHubGovernance) -> str:
    value = {
        "schema": "hyperflux-github-protection-plan-v1",
        "repository": f"{governance.owner}/{governance.repository}",
        "remote_state": governance.remote_state,
        "apply_authorized": False,
        "default_branch": governance.default_branch,
        "ruleset": {
            "enforcement": "active-after-explicit-remote-authorization",
            "required_approvals": governance.required_approvals,
            "dismiss_stale_reviews": True,
            "require_code_owner_reviews": True,
            "require_conversation_resolution": True,
            "require_linear_history": True,
            "required_status_checks": list(governance.required_checks),
        },
        "excluded_components": [
            "pages-deployment",
            "release-tags",
            "release-publication",
            "hardware-ci",
        ],
    }
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def labels_plan(governance: GitHubGovernance) -> str:
    value = {
        "schema": "hyperflux-github-label-plan-v1",
        "repository": f"{governance.owner}/{governance.repository}",
        "remote_state": governance.remote_state,
        "apply_authorized": False,
        "labels": [
            {
                "name": label.name,
                "color": label.color,
                "description": label.description,
            }
            for label in governance.labels
        ],
    }
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def experience_plan(governance: GitHubGovernance) -> str:
    value = {
        "schema": "hyperflux-github-experience-plan-v1",
        "repository": f"{governance.owner}/{governance.repository}",
        "remote_state": governance.remote_state,
        "apply_authorized": False,
        "discussions": {
            "apply_authorized": False,
            "categories": [
                {
                    "id": category.id,
                    "name": category.name,
                    "format": category.format,
                    "description": category.description,
                }
                for category in governance.discussions
            ],
        },
        "project": {
            "apply_authorized": False,
            "title": governance.project_title,
            "views": [
                {
                    "id": view.id,
                    "name": view.name,
                    "layout": view.layout,
                    "group_by": view.group_by,
                    "date_field": view.date_field,
                }
                for view in governance.project_views
            ],
            "fields": [
                {
                    "id": field.id,
                    "name": field.name,
                    "data_type": field.data_type,
                    "options": list(field.options),
                }
                for field in governance.project_fields
            ],
        },
        "security_posture": {
            identifier: {
                "state": plan.state,
                "activation_boundary": plan.activation_boundary,
                "data_boundary": plan.data_boundary,
            }
            for identifier, plan in governance.security_posture
        },
        "service_evaluations": [
            {
                "id": evaluation.id,
                "service": evaluation.service,
                "decision": evaluation.decision,
                "benefits": list(evaluation.benefits),
                "required_permissions": list(evaluation.required_permissions),
                "privacy": evaluation.privacy,
                "maintenance_cost": evaluation.maintenance_cost,
                "rationale": evaluation.rationale,
            }
            for evaluation in governance.service_evaluations
        ],
        "external_apps_installed": [],
        "publication_authorized": False,
    }
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def markdown(governance: GitHubGovernance) -> str:
    lines = [
        "# GitHub Governance",
        "",
        "> Generated by `./hfx generate`. Do not edit manually.",
        "",
        "This repository experience is fully modeled locally. No remote repository, Pages deployment, release workflow, tag, or hardware CI is authorized by this configuration.",
        "",
        "## Current Interlock",
        "",
        f"- Planned repository: `{governance.owner}/{governance.repository}`",
        f"- Remote state: `{governance.remote_state}`",
        "- Publication: `locked`",
        "- Pages deployment: `locked`",
        "- Release workflows: `locked`",
        "- Hardware CI: `locked`",
        "",
        "## Software Workflows",
        "",
        "| Workflow | Trigger | Network during verification | Hardware access | Output |",
        "| --- | --- | --- | --- | --- |",
        "| Verification | Pull requests, main, manual | None | None | Source-bound fast evidence |",
        "| Full verification | Weekly or manual | None | None | Source-bound full evidence |",
        "| Documentation | Main documentation changes or manual | None | None | Offline portal artifact |",
        "| CodeQL | Pull requests, main, weekly | GitHub service only | None | C/C++ and Python analysis |",
        "| Dependency review | Pull requests | GitHub service only | None | Dependency policy decision |",
        "",
        "The development image may use the exact snapshot and toolchain network boundary while it is built. Exact application upstreams are prepared before verification. Every verification command then runs in the pinned image with `--network none`, no devices, no privileges, dropped capabilities, and a read/write mount limited to the checkout.",
        "",
        "## Required Check Plan",
        "",
    ]
    lines.extend(f"- `{check}`" for check in governance.required_checks)
    lines.extend(
        [
            "",
            "The plan is generated with `apply_authorized: false`. It can be reviewed now but may be applied only after remote creation is separately authorized and the first hosted runs establish these exact check names.",
            "",
            "## Immutable Workflow Dependencies",
            "",
            "| Action | Reviewed version | Commit | License |",
            "| --- | --- | --- | --- |",
        ]
    )
    for action in governance.actions:
        lines.append(
            f"| `{action.repository}` | `{action.version}` | `{action.commit}` | `{action.license_expression}` |"
        )
    lines.extend(
        [
            "",
            "## Repository Experience",
            "",
            "- CODEOWNERS derives from component ownership boundaries.",
            "- Issue forms request bounded, privacy-safe evidence and never imply hardware-write approval.",
            "- Pull requests surface canonical authority, schema, package, performance, privacy, and evidence impact.",
            "- Dependency updates are grouped by GitHub Actions, Cargo, and each Python integration root.",
            "- Labels and branch protection are reviewable generated plans, not hidden remote state.",
            "",
            "## Actions Job Summaries",
            "",
            "Fast and full verification jobs render `result.json` into the native GitHub Actions summary. The renderer reports structured facts and deliberately omits raw error text that could expose runner paths.",
            "",
        ]
    )
    lines.extend(f"- `{section}`" for section in governance.job_summary_sections)
    lines.extend(
        [
            "",
            "A missing result remains visible as unavailable, source-revision mismatches fail closed, and the release-gate section states that CI validates but cannot mutate gate state.",
            "",
            "## Discussions Plan",
            "",
            "| Category | Format | Purpose |",
            "| --- | --- | --- |",
        ]
    )
    for category in governance.discussions:
        lines.append(
            f"| {category.name} | `{category.format}` | {category.description} |"
        )
    lines.extend(
        [
            "",
            "The category plan has `apply_authorized: false`; it does not enable Discussions on a remote.",
            "",
            "## Project Plan",
            "",
            f"Planned project: **{governance.project_title}**",
            "",
            "| View | Layout | Grouping | Date field |",
            "| --- | --- | --- | --- |",
        ]
    )
    for view in governance.project_views:
        lines.append(
            f"| {view.name} | `{view.layout}` | `{view.group_by}` | `{view.date_field}` |"
        )
    lines.extend(
        [
            "",
            "| Field | Type | Options |",
            "| --- | --- | --- |",
        ]
    )
    for field in governance.project_fields:
        options = ", ".join(field.options) if field.options else "Date value"
        lines.append(f"| {field.name} | `{field.data_type}` | {options} |")
    lines.extend(
        [
            "",
            "The project plan has `apply_authorized: false`; no Project or field is created by generation.",
            "",
            "## Security Preparation",
            "",
            "| Capability | State | Activation boundary | Data boundary |",
            "| --- | --- | --- | --- |",
        ]
    )
    for identifier, plan in governance.security_posture:
        lines.append(
            f"| `{identifier}` | `{plan.state}` | `{plan.activation_boundary}` | {plan.data_boundary} |"
        )
    lines.extend(
        [
            "",
            "## External Service Evaluation",
            "",
            "| Service | Decision | Permissions or data access | Privacy | Maintenance |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for evaluation in governance.service_evaluations:
        permissions = ", ".join(f"`{item}`" for item in evaluation.required_permissions)
        lines.append(
            f"| {evaluation.service} | `{evaluation.decision}` | {permissions} | {evaluation.privacy} | `{evaluation.maintenance_cost}` |"
        )
    lines.extend(["", "No external app or service is installed by this plan.", ""])
    return "\n".join(lines)
