# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

import json
from typing import Any

import yaml

from ..development import CARGO_CACHE_PATH, UPSTREAM_CACHE_PATH
from ..governance import GitHubGovernance


NOTICE = "# Generated by ./hfx generate. Do not edit manually.\n"


class _ReadableDumper(yaml.SafeDumper):
    def ignore_aliases(self, data: Any) -> bool:
        return True


def _represent_string(dumper: yaml.SafeDumper, value: str) -> yaml.ScalarNode:
    style = "|" if "\n" in value else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)


_ReadableDumper.add_representer(str, _represent_string)


def _yaml(value: dict[str, Any], governance: GitHubGovernance) -> str:
    rendered = yaml.dump(
        value,
        Dumper=_ReadableDumper,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=False,
        width=1000,
    )
    for action in governance.actions:
        rendered = rendered.replace(
            f"uses: {action.uses}\n",
            f"uses: {action.uses} # {action.version}\n",
        )
    return NOTICE + rendered


def _checkout(governance: GitHubGovernance) -> dict[str, Any]:
    return {
        "name": "Check out exact source",
        "uses": governance.actions_by_id["checkout"].uses,
        "with": {"fetch-depth": 0, "persist-credentials": False},
    }


def _cache(governance: GitHubGovernance) -> dict[str, Any]:
    return {
        "name": "Restore verified software caches",
        "uses": governance.actions_by_id["cache"].uses,
        "with": {
            "path": f"{UPSTREAM_CACHE_PATH}\n{CARGO_CACHE_PATH}\ntarget\n",
            "key": "hfx-${{ runner.os }}-${{ hashFiles('Cargo.lock', 'toolchains/development-environment.json', 'integrations/catalog.json') }}",
            "restore-keys": "hfx-${{ runner.os }}-\n",
        },
    }


def _build_environment(governance: GitHubGovernance) -> list[dict[str, Any]]:
    return [
        {
            "name": "Set up Buildx",
            "uses": governance.actions_by_id["setup-buildx"].uses,
        },
        {
            "name": "Build the pinned development environment",
            "uses": governance.actions_by_id["build-push"].uses,
            "with": {
                "context": ".",
                "file": ".devcontainer/Containerfile",
                "load": True,
                "push": False,
                "tags": "${{ env.HFX_CI_IMAGE }}",
                "cache-from": "type=gha,scope=hyperflux-next-development",
                "cache-to": "type=gha,mode=max,scope=hyperflux-next-development,ignore-error=true",
            },
        },
    ]


def _upload(
    governance: GitHubGovernance,
    *,
    name: str,
    path: str,
    retention_days: int,
) -> dict[str, Any]:
    return {
        "name": f"Upload {name}",
        "if": "${{ always() }}",
        "uses": governance.actions_by_id["upload-artifact"].uses,
        "with": {
            "name": name,
            "path": path,
            "if-no-files-found": "error",
            "retention-days": retention_days,
        },
    }


def _verification_summary(output: str) -> dict[str, Any]:
    return {
        "name": "Publish bounded verification summary",
        "if": "${{ always() }}",
        "env": {"HFX_SOURCE_REVISION": "${{ github.sha }}"},
        "run": (
            f'./hfx ci summary --result {output}/result.json '
            '--output "$GITHUB_STEP_SUMMARY" --source-revision "$HFX_SOURCE_REVISION"'
        ),
    }


def _portal_summary(output: str) -> dict[str, Any]:
    return {
        "name": "Publish generated portal summary",
        "if": "${{ always() }}",
        "env": {"HFX_SOURCE_REVISION": "${{ github.sha }}"},
        "run": (
            f"./hfx ci pages-summary --manifest {output}/portal-build-manifest.json "
            '--output "$GITHUB_STEP_SUMMARY" --source-revision "$HFX_SOURCE_REVISION"'
        ),
    }


def verification_workflow(governance: GitHubGovernance) -> str:
    steps = [_checkout(governance), _cache(governance), *_build_environment(governance)]
    steps.extend(
        [
            {
                "name": "Prepare exact upstream sources",
                "run": './hfx ci prepare --image "$HFX_CI_IMAGE"',
            },
            {
                "name": "Run fail-closed changed-path verification",
                "env": {
                    "HFX_CHANGED_FROM": "${{ github.event.pull_request.base.sha || github.event.before || '' }}"
                },
                "run": './hfx ci verify --image "$HFX_CI_IMAGE" --lane fast --output build/ci/fast --changed-from "$HFX_CHANGED_FROM"',
            },
            _verification_summary("build/ci/fast"),
            _upload(
                governance,
                name="hyperflux-fast-evidence",
                path="build/ci/fast",
                retention_days=14,
            ),
        ]
    )
    value = {
        "name": "Verification",
        "on": {
            "pull_request": {},
            "push": {"branches": [governance.default_branch]},
            "workflow_dispatch": {},
        },
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "verification-${{ github.workflow }}-${{ github.ref }}",
            "cancel-in-progress": True,
        },
        "env": {"HFX_CI_IMAGE": governance.development_image},
        "jobs": {
            "fast-software": {
                "name": "Fast software",
                "runs-on": governance.runner,
                "timeout-minutes": 45,
                "steps": steps,
            }
        },
    }
    return _yaml(value, governance)


def full_verification_workflow(governance: GitHubGovernance) -> str:
    steps = [_checkout(governance), _cache(governance), *_build_environment(governance)]
    steps.extend(
        [
            {
                "name": "Prepare exact upstream sources",
                "run": './hfx ci prepare --image "$HFX_CI_IMAGE"',
            },
            {
                "name": "Run the complete software graph",
                "run": './hfx ci verify --image "$HFX_CI_IMAGE" --lane full --output build/ci/full',
            },
            _verification_summary("build/ci/full"),
            _upload(
                governance,
                name="hyperflux-full-evidence",
                path="build/ci/full",
                retention_days=30,
            ),
        ]
    )
    value = {
        "name": "Full verification",
        "on": {
            "pull_request": {},
            "workflow_dispatch": {},
            "schedule": [{"cron": governance.full_verification_cron}],
        },
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "full-verification-${{ github.ref }}",
            "cancel-in-progress": False,
        },
        "env": {"HFX_CI_IMAGE": governance.development_image},
        "jobs": {
            "full-software": {
                "name": "Full software",
                "runs-on": governance.runner,
                "timeout-minutes": 90,
                "steps": steps,
            }
        },
    }
    return _yaml(value, governance)


def documentation_workflow(governance: GitHubGovernance) -> str:
    steps = [_checkout(governance), *_build_environment(governance)]
    steps.extend(
        [
            {
                "name": "Build and verify the offline portal",
                "run": './hfx ci docs --image "$HFX_CI_IMAGE" --output build/ci/portal',
            },
            _portal_summary("build/ci/portal"),
            _upload(
                governance,
                name="hyperflux-documentation-portal",
                path="build/ci/portal",
                retention_days=14,
            ),
        ]
    )
    value = {
        "name": "Documentation",
        "on": {
            "pull_request": {},
            "workflow_dispatch": {},
            "push": {
                "branches": [governance.default_branch],
                "paths": [
                    "docs/**",
                    "schemas/documentation-portal.schema.json",
                    "tools/hfxdev/portal*.py",
                    "tools/hfxdev/generators/**",
                    "governance/github.json",
                ],
            },
        },
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "documentation-${{ github.ref }}",
            "cancel-in-progress": True,
        },
        "env": {"HFX_CI_IMAGE": governance.development_image},
        "jobs": {
            "portal-artifact": {
                "name": "Portal contracts",
                "runs-on": governance.runner,
                "timeout-minutes": 30,
                "steps": steps,
            }
        },
    }
    return _yaml(value, governance)


def repository_experience_workflow(governance: GitHubGovernance) -> str:
    def job(name: str, output: str, artifact: str) -> dict[str, Any]:
        steps = [_checkout(governance), *_build_environment(governance)]
        steps.extend(
            [
                {
                    "name": f"Build and verify {name.lower()}",
                    "run": f'./hfx ci docs --image "$HFX_CI_IMAGE" --output {output}',
                },
                _portal_summary(output),
                _upload(
                    governance,
                    name=artifact,
                    path=output,
                    retention_days=14,
                ),
            ]
        )
        return {
            "name": name,
            "runs-on": governance.runner,
            "timeout-minutes": 30,
            "steps": steps,
        }

    value = {
        "name": "Repository experience",
        "on": {"pull_request": {}, "workflow_dispatch": {}},
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "repository-experience-${{ github.ref }}",
            "cancel-in-progress": True,
        },
        "env": {"HFX_CI_IMAGE": governance.development_image},
        "jobs": {
            "link-checks": job(
                "Link checks", "build/ci/links", "hyperflux-link-evidence"
            ),
            "pages-preview": job(
                "Pages preview", "build/ci/pages-preview", "hyperflux-pages-preview"
            ),
        },
    }
    return _yaml(value, governance)


def pages_workflow(governance: GitHubGovernance) -> str:
    build_steps = [_checkout(governance), *_build_environment(governance)]
    build_steps.extend(
        [
            {
                "name": "Build and verify the generated portal",
                "run": './hfx ci docs --image "$HFX_CI_IMAGE" --output build/ci/portal',
            },
            {
                "name": "Configure GitHub Pages",
                "uses": governance.actions_by_id["configure-pages"].uses,
            },
            _portal_summary("build/ci/portal"),
            {
                "name": "Upload the verified Pages artifact",
                "uses": governance.actions_by_id["upload-pages-artifact"].uses,
                "with": {"path": "build/ci/portal"},
            },
        ]
    )
    value = {
        "name": "Pages",
        "on": {
            "push": {"branches": [governance.default_branch]},
            "workflow_dispatch": {},
        },
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "pages",
            "cancel-in-progress": False,
        },
        "env": {"HFX_CI_IMAGE": governance.development_image},
        "jobs": {
            "build": {
                "name": "Build verified portal",
                "runs-on": governance.runner,
                "timeout-minutes": 30,
                "permissions": {"contents": "read", "pages": "write", "id-token": "write"},
                "steps": build_steps,
            },
            "deploy": {
                "name": "Deploy protected Pages",
                "needs": "build",
                "runs-on": governance.runner,
                "timeout-minutes": 15,
                "permissions": {"pages": "write", "id-token": "write"},
                "environment": {
                    "name": "github-pages",
                    "url": "${{ steps.deployment.outputs.page_url }}",
                },
                "steps": [
                    {
                        "name": "Deploy generated documentation",
                        "id": "deployment",
                        "uses": governance.actions_by_id["deploy-pages"].uses,
                    },
                    {
                        "name": "Publish deployment status",
                        "env": {
                            "HFX_PAGE_URL": "${{ steps.deployment.outputs.page_url }}",
                            "HFX_SOURCE_REVISION": "${{ github.sha }}",
                        },
                        "run": (
                            "printf '# Pages deployment\\n\\n"
                            "| Field | Result |\\n| --- | --- |\\n"
                            "| Status | **DEPLOYED** |\\n"
                            "| Source revision | `%s` |\\n"
                            "| Environment | `github-pages` |\\n"
                            "| URL | %s |\\n"
                            "| Product release authority | Locked |\\n' "
                            '"$HFX_SOURCE_REVISION" "$HFX_PAGE_URL" >> "$GITHUB_STEP_SUMMARY"'
                        ),
                    },
                ],
            },
        },
    }
    return _yaml(value, governance)


def codeql_workflow(governance: GitHubGovernance) -> str:
    codeql = governance.actions_by_id["codeql"]
    value = {
        "name": "CodeQL",
        "on": {
            "pull_request": {},
            "push": {"branches": [governance.default_branch]},
            "schedule": [{"cron": "43 2 * * 4"}],
        },
        "permissions": {"contents": "read", "security-events": "write"},
        "concurrency": {
            "group": "codeql-${{ github.workflow }}-${{ github.ref }}",
            "cancel-in-progress": True,
        },
        "jobs": {
            "analyze": {
                "name": "Analyze (${{ matrix.language }})",
                "runs-on": governance.runner,
                "timeout-minutes": 45,
                "strategy": {
                    "fail-fast": False,
                    "matrix": {"language": ["c-cpp", "python"]},
                },
                "steps": [
                    _checkout(governance),
                    {
                        "name": "Initialize CodeQL",
                        "uses": f"{codeql.repository}/init@{codeql.commit}",
                        "with": {
                            "languages": "${{ matrix.language }}",
                            "build-mode": "none",
                        },
                    },
                    {
                        "name": "Analyze source",
                        "uses": f"{codeql.repository}/analyze@{codeql.commit}",
                        "with": {"category": "/language:${{ matrix.language }}"},
                    },
                ],
            }
        },
    }
    rendered = _yaml(value, governance)
    rendered = rendered.replace(
        f"uses: {codeql.repository}/init@{codeql.commit}\n",
        f"uses: {codeql.repository}/init@{codeql.commit} # {codeql.version}\n",
    ).replace(
        f"uses: {codeql.repository}/analyze@{codeql.commit}\n",
        f"uses: {codeql.repository}/analyze@{codeql.commit} # {codeql.version}\n",
    )
    return rendered


def dependency_review_workflow(governance: GitHubGovernance) -> str:
    value = {
        "name": "Dependency review",
        "on": {"pull_request": {}},
        "permissions": {"contents": "read"},
        "jobs": {
            "dependency-review": {
                "name": "Dependency review",
                "runs-on": governance.runner,
                "timeout-minutes": 15,
                "steps": [
                    _checkout(governance),
                    {
                        "name": "Review dependency changes",
                        "uses": governance.actions_by_id["dependency-review"].uses,
                        "with": {
                            "fail-on-severity": "moderate",
                            "license-check": "true",
                            "vulnerability-check": "true",
                        },
                    },
                ],
            }
        },
    }
    return _yaml(value, governance)


def dependabot(governance: GitHubGovernance) -> str:
    schedule = {"interval": "weekly", "day": governance.dependency_update_day}
    value = {
        "version": 2,
        "updates": [
            {
                "package-ecosystem": "github-actions",
                "directory": "/",
                "schedule": schedule,
                "open-pull-requests-limit": 5,
                "groups": {"github-actions": {"patterns": ["*"]}},
                "labels": ["area: security"],
            },
            {
                "package-ecosystem": "cargo",
                "directory": "/",
                "schedule": schedule,
                "open-pull-requests-limit": 5,
                "groups": {"rust-dependencies": {"patterns": ["*"]}},
                "labels": ["area: security"],
            },
            *[
                {
                    "package-ecosystem": "pip",
                    "directory": directory,
                    "schedule": schedule,
                    "open-pull-requests-limit": 3,
                    "groups": {"python-dependencies": {"patterns": ["*"]}},
                    "labels": ["area: integration", "area: security"],
                }
                for directory in (
                    "/sdk/python",
                    "/integrations/openrazer/compatibility",
                    "/integrations/polychromatic",
                )
            ],
        ],
    }
    return _yaml(value, governance)


def codeowners(governance: GitHubGovernance) -> str:
    lines = [NOTICE.rstrip(), "", f"* {' '.join(governance.default_owners)}"]
    for rule in governance.ownership_rules:
        lines.extend(f"{path} {' '.join(rule.owners)}" for path in rule.paths)
    return "\n".join(lines) + "\n"


def pull_request_template() -> str:
    return """<!-- Generated by ./hfx generate. Do not edit manually. -->

## Outcome

<!-- Describe the user-visible or engineering outcome, not only the changed files. -->

## Affected Domains

- [ ] Kernel transport or UAPI
- [ ] Bridge, protocol, or SDK
- [ ] Hardware profiles or application integrations
- [ ] Packaging or lifecycle
- [ ] Verification, assurance, or governance
- [ ] Documentation only

## Contract Impact

- Canonical authority changed:
- Generated outputs refreshed:
- Schema, protocol, UAPI, or ABI compatibility:
- Package or activation behavior:
- Performance budget impact:
- Privacy or support-bundle impact:
- Release-gate impact:
- Evidence level: proposal / software / lifecycle / physical
- Qualification state: unknown / candidate / route qualified / fully qualified / blocked

## Evidence

- Source revision:
- Verification commands, selected nodes, and timings:
- Generated freshness:
- Fast verification evidence:
- Full software evidence, when required:
- Physical evidence, when separately authorized:

## Interlocks

- [ ] Hardware authority is `none`, or a separate bounded authorization and evidence record is linked above.
- [ ] This change does not create a release, tag, package channel, or supported-product claim.
- [ ] Any Pages change is generated from canonical repository data; no deployed HTML was hand-edited.
- [ ] User-facing documentation contains no internal engineering mission identifiers.
"""


def _issue_form(
    governance: GitHubGovernance,
    *,
    name: str,
    description: str,
    title: str,
    labels: list[str],
    body: list[dict[str, Any]],
) -> str:
    return _yaml(
        {
            "name": name,
            "description": description,
            "title": title,
            "labels": labels,
            "body": body,
        },
        governance,
    )


def bug_report(governance: GitHubGovernance) -> str:
    return _issue_form(
        governance,
        name="Bug report",
        description="Report incorrect behavior with privacy-safe diagnostic context.",
        title="[Bug]: ",
        labels=["kind: bug"],
        body=[
            {
                "type": "markdown",
                "attributes": {
                    "value": "Run `hyperfluxctl doctor` first. Never attach hardware serials, raw HID or USB payloads, private paths, captures, or memory dumps."
                },
            },
            {
                "type": "textarea",
                "id": "outcome",
                "attributes": {
                    "label": "What happened?",
                    "description": "Describe the observed result and the result you expected.",
                    "placeholder": "Observed:\nExpected:",
                },
                "validations": {"required": True},
            },
            {
                "type": "input",
                "id": "environment",
                "attributes": {
                    "label": "Environment",
                    "description": "Distribution, kernel, package version, and application adapter.",
                    "placeholder": "Arch Linux; 6.x; 0.x; OpenRGB",
                },
                "validations": {"required": True},
            },
            {
                "type": "input",
                "id": "doctor-reference",
                "attributes": {
                    "label": "Doctor reference",
                    "description": "The privacy-safe hfx reference printed by hyperfluxctl doctor.",
                    "placeholder": "hfx-...",
                },
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "support-preview",
                "attributes": {
                    "label": "Support preview",
                    "description": "Paste `hyperfluxctl support-bundle --preview`. This previews bounded contents and performs no upload.",
                    "render": "json",
                },
            },
            {
                "type": "checkboxes",
                "id": "privacy",
                "attributes": {
                    "label": "Privacy confirmation",
                    "options": [
                        {
                            "label": "I removed serials, stable host identifiers, private paths, and raw transport payloads.",
                            "required": True,
                        }
                    ],
                },
            },
        ],
    )


def hardware_qualification(governance: GitHubGovernance) -> str:
    return _issue_form(
        governance,
        name="Device qualification",
        description="Propose bounded evidence for one exact device route without authorizing writes.",
        title="[Qualification]: ",
        labels=["evidence: hardware", "kind: qualification"],
        body=[
            {
                "type": "markdown",
                "attributes": {
                    "value": "Opening this issue does not authorize receiver queries, RGB writes, suspend, or any other physical test. A separate bounded approval is always required."
                },
            },
            {
                "type": "input",
                "id": "model",
                "attributes": {"label": "Exact marketed model", "placeholder": "Vendor and model"},
                "validations": {"required": True},
            },
            {
                "type": "input",
                "id": "pid",
                "attributes": {"label": "Public product ID", "placeholder": "0x0000"},
                "validations": {"required": True},
            },
            {
                "type": "dropdown",
                "id": "route",
                "attributes": {
                    "label": "Connection route",
                    "options": ["HyperFlux receiver", "Direct wireless", "Direct wired", "Unknown"],
                },
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "capabilities",
                "attributes": {
                    "label": "Observed capabilities",
                    "description": "Identity, lighting zones, battery, connection, controls, lifecycle, or other bounded observations.",
                },
                "validations": {"required": True},
            },
            {
                "type": "input",
                "id": "doctor-reference",
                "attributes": {
                    "label": "Doctor reference, when available",
                    "description": "The privacy-safe hfx reference printed by hyperfluxctl doctor.",
                    "placeholder": "hfx-...",
                },
            },
            {
                "type": "textarea",
                "id": "support-preview",
                "attributes": {
                    "label": "Support preview, when available",
                    "description": "Paste `hyperfluxctl support-bundle --preview`. This performs no upload or active receiver query.",
                    "render": "json",
                },
            },
            {
                "type": "dropdown",
                "id": "evidence-class",
                "attributes": {
                    "label": "Available evidence",
                    "options": ["Read-only software evidence", "Watched physical evidence", "Public upstream metadata", "Proposal only"],
                },
                "validations": {"required": True},
            },
            {
                "type": "checkboxes",
                "id": "privacy",
                "attributes": {
                    "label": "Privacy confirmation",
                    "options": [
                        {
                            "label": "No serial, stable host identifier, raw transport payload, or private path is included.",
                            "required": True,
                        }
                    ],
                },
            },
        ],
    )


def hardware_research(governance: GitHubGovernance) -> str:
    return _issue_form(
        governance,
        name="Hardware research",
        description="Record public device knowledge, conflicts, and unknowns without claiming support.",
        title="[Research]: ",
        labels=["area: profiles", "kind: hardware-research"],
        body=[
            {
                "type": "markdown",
                "attributes": {
                    "value": "Research identifies candidates; it does not qualify a route or authorize hardware access. Link public sources and describe uncertainty explicitly."
                },
            },
            {
                "type": "input",
                "id": "model",
                "attributes": {"label": "Device or family", "placeholder": "Exact marketed name when known"},
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "sources",
                "attributes": {
                    "label": "Public sources",
                    "description": "Official product/support pages, manuals, and pinned upstream registry locations.",
                    "placeholder": "One URL or repository path per line",
                },
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "facts",
                "attributes": {
                    "label": "Facts and conflicts",
                    "description": "Separate directly stated facts, cross-source conflicts, and inferences.",
                },
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "unknowns",
                "attributes": {
                    "label": "What remains unknown?",
                    "description": "Name the gaps that prevent route qualification or a capability claim.",
                },
                "validations": {"required": True},
            },
            {
                "type": "checkboxes",
                "id": "boundary",
                "attributes": {
                    "label": "Evidence boundary",
                    "options": [
                        {
                            "label": "This report contains no private capture, serial, stable host identifier, raw payload, or support claim.",
                            "required": True,
                        }
                    ],
                },
            },
        ],
    )


def documentation_report(governance: GitHubGovernance) -> str:
    return _issue_form(
        governance,
        name="Documentation",
        description="Report unclear, stale, inaccessible, or misrouted repository guidance.",
        title="[Docs]: ",
        labels=["area: documentation", "kind: documentation"],
        body=[
            {
                "type": "dropdown",
                "id": "audience",
                "attributes": {
                    "label": "Audience",
                    "options": ["First-time user", "Developer", "Contributor", "Hardware tester", "Maintainer", "Security reporter"],
                },
                "validations": {"required": True},
            },
            {
                "type": "input",
                "id": "location",
                "attributes": {
                    "label": "Page or link",
                    "placeholder": "Repository path or public URL",
                },
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "problem",
                "attributes": {
                    "label": "What prevented the next action?",
                    "description": "Describe what you expected to learn or do and what was missing or confusing.",
                },
                "validations": {"required": True},
            },
            {
                "type": "dropdown",
                "id": "source-kind",
                "attributes": {
                    "label": "Content type",
                    "options": ["Hand-written canonical source", "Generated portal page", "README navigation", "Unknown"],
                },
                "validations": {"required": True},
            },
        ],
    )


def feature_request(governance: GitHubGovernance) -> str:
    return _issue_form(
        governance,
        name="Feature request",
        description="Describe a universal user workflow or capability gap.",
        title="[Feature]: ",
        labels=["kind: feature"],
        body=[
            {
                "type": "dropdown",
                "id": "area",
                "attributes": {
                    "label": "Primary area",
                    "options": [
                        "Applications and integrations",
                        "Device knowledge and qualification",
                        "Kernel, bridge, or SDK",
                        "Packaging and lifecycle",
                        "Documentation and diagnostics",
                        "Governance and tooling",
                    ],
                },
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "workflow",
                "attributes": {
                    "label": "User workflow",
                    "description": "What should a normal user be able to accomplish?",
                },
                "validations": {"required": True},
            },
            {
                "type": "textarea",
                "id": "gap",
                "attributes": {
                    "label": "Current gap",
                    "description": "What is missing, confusing, or unnecessarily device-specific today?",
                },
                "validations": {"required": True},
            },
            {
                "type": "checkboxes",
                "id": "universality",
                "attributes": {
                    "label": "Universality",
                    "options": [
                        {
                            "label": "The proposal is not tied only to one host, serial, receiver generation, or private device state.",
                            "required": True,
                        }
                    ],
                },
            },
            {
                "type": "textarea",
                "id": "evidence-boundary",
                "attributes": {
                    "label": "Evidence needed",
                    "description": "Which software, lifecycle, or physical evidence would make this proposal safe to ship?",
                },
            },
        ],
    )


def issue_config(governance: GitHubGovernance) -> str:
    value = {
        "blank_issues_enabled": False,
        "contact_links": [
            {
                "name": "Ask for help",
                "url": f"https://github.com/{governance.owner}/{governance.repository}/discussions/categories/help",
                "about": "Use Discussions after checking the documentation and privacy-safe support steps.",
            },
            {
                "name": "Discuss an idea",
                "url": f"https://github.com/{governance.owner}/{governance.repository}/discussions/categories/ideas",
                "about": "Explore a universal workflow before committing it to an issue.",
            },
            {
                "name": "Report a security vulnerability privately",
                "url": f"https://github.com/{governance.owner}/{governance.repository}/security/advisories/new",
                "about": "Do not disclose vulnerabilities or sensitive diagnostics in a public issue.",
            }
        ],
    }
    return _yaml(value, governance)


def release_notes(governance: GitHubGovernance) -> str:
    value = {
        "changelog": {
            "exclude": {"labels": ["skip-changelog"]},
            "categories": [
                {"title": "User-facing changes", "labels": ["kind: feature", "kind: bug"]},
                {"title": "Device knowledge and qualification", "labels": ["kind: hardware-research", "kind: qualification"]},
                {"title": "Integrations", "labels": ["area: integration"]},
                {"title": "Kernel and runtime", "labels": ["area: kernel", "area: runtime"]},
                {"title": "Packaging", "labels": ["area: packaging"]},
                {"title": "Documentation", "labels": ["area: documentation", "kind: documentation"]},
                {"title": "Assurance, security, and tooling", "labels": ["area: assurance", "area: governance", "area: security", "area: tooling"]},
                {"title": "Other changes", "labels": ["*"]},
            ],
        }
    }
    return _yaml(value, governance)


def protection_plan(governance: GitHubGovernance) -> str:
    value = {
        "schema": "hyperflux-github-protection-plan-v1",
        "repository": f"{governance.owner}/{governance.repository}",
        "remote_state": governance.remote_state,
        "apply_authorized": True,
        "default_branch": governance.default_branch,
        "ruleset": {
            "profile": governance.protection_profile,
            "trusted_maintainers": governance.trusted_maintainers,
            "enforcement": "active",
            "bypass_actors": [],
            "required_approvals": governance.required_approvals,
            "dismiss_stale_reviews": True,
            "require_code_owner_reviews": governance.require_code_owner_reviews,
            "require_conversation_resolution": True,
            "require_linear_history": True,
            "prevent_deletions": True,
            "prevent_force_pushes": True,
            "strict_required_status_checks": governance.strict_required_status_checks,
            "required_status_checks": list(governance.required_checks),
        },
        "excluded_components": [
            "package-publication",
            "release-tags",
            "release-publication",
            "hardware-ci",
        ],
    }
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def labels_plan(governance: GitHubGovernance) -> str:
    value = {
        "schema": "hyperflux-github-label-plan-v1",
        "repository": f"{governance.owner}/{governance.repository}",
        "remote_state": governance.remote_state,
        "apply_authorized": True,
        "labels": [
            {
                "name": label.name,
                "color": label.color,
                "description": label.description,
            }
            for label in governance.labels
        ],
    }
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def experience_plan(governance: GitHubGovernance) -> str:
    value = {
        "schema": "hyperflux-github-experience-plan-v1",
        "repository": f"{governance.owner}/{governance.repository}",
        "remote_state": governance.remote_state,
        "apply_authorized": True,
        "discussions": {
            "apply_authorized": True,
            "categories": [
                {
                    "id": category.id,
                    "name": category.name,
                    "format": category.format,
                    "description": category.description,
                }
                for category in governance.discussions
            ],
        },
        "project": {
            "apply_authorized": True,
            "number": governance.project_number,
            "title": governance.project_title,
            "url": governance.project_url,
            "views": [
                {
                    "id": view.id,
                    "name": view.name,
                    "layout": view.layout,
                    "group_by": view.group_by,
                    "date_field": view.date_field,
                }
                for view in governance.project_views
            ],
            "fields": [
                {
                    "id": field.id,
                    "name": field.name,
                    "data_type": field.data_type,
                    "options": list(field.options),
                }
                for field in governance.project_fields
            ],
        },
        "security_posture": {
            identifier: {
                "state": plan.state,
                "activation_boundary": plan.activation_boundary,
                "data_boundary": plan.data_boundary,
            }
            for identifier, plan in governance.security_posture
        },
        "service_evaluations": [
            {
                "id": evaluation.id,
                "service": evaluation.service,
                "decision": evaluation.decision,
                "benefits": list(evaluation.benefits),
                "required_permissions": list(evaluation.required_permissions),
                "privacy": evaluation.privacy,
                "maintenance_cost": evaluation.maintenance_cost,
                "rationale": evaluation.rationale,
            }
            for evaluation in governance.service_evaluations
        ],
        "external_apps_installed": [],
        "source_repository_authorized": governance.source_repository_authorized,
        "pages_deployment_authorized": governance.pages_deployment_authorized,
        "product_publication_authorized": governance.product_publication_authorized,
        "repository_metadata": {
            "description": governance.description,
            "homepage": governance.homepage,
            "visibility": governance.visibility,
            "topics": list(governance.topics),
            "social_preview_asset": governance.social_preview_asset,
        },
    }
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def markdown(governance: GitHubGovernance) -> str:
    lines = [
        "# GitHub Governance",
        "",
        "> Generated by `./hfx generate`. Do not edit manually.",
        "",
        "The public repository, generated Pages portal, Discussions, roadmap, and native security controls are authorized by this configuration. Product releases, package publication, tags, and hardware-writing CI remain locked.",
        "",
        "## Current Interlock",
        "",
        f"- Planned repository: `{governance.owner}/{governance.repository}`",
        f"- Remote state: `{governance.remote_state}`",
        "- Public source: `authorized`",
        "- Pages deployment: `authorized from generated portal only`",
        "- Product publication: `locked`",
        "- Package publication: `locked`",
        "- Tag creation: `locked`",
        "- Release workflows: `locked`",
        "- Hardware CI: `locked`",
        "",
        "## Software Workflows",
        "",
        "| Workflow | Trigger | Network during verification | Hardware access | Output |",
        "| --- | --- | --- | --- | --- |",
        "| Verification | Pull requests, main, manual | None | None | Source-bound fast evidence |",
        "| Full verification | Pull request, weekly, or manual | None | None | Source-bound full evidence |",
        "| Documentation | Pull requests, main documentation changes, manual | None | None | Verified portal artifact |",
        "| Pages | Main or manual | None after image build | None | Protected generated portal deployment |",
        "| CodeQL | Pull requests, main, weekly | GitHub service only | None | C/C++ and Python analysis |",
        "| Dependency review | Pull requests | GitHub service only | None | Dependency policy decision |",
        "",
        "The development image may use the exact snapshot and toolchain network boundary while it is built. Exact application upstreams are prepared before verification. Every verification command then runs in the pinned image with `--network none`, no devices, no privileges, dropped capabilities, and a read/write mount limited to the checkout.",
        "",
        "## Required Check Plan",
        "",
    ]
    lines.extend(f"- `{check}`" for check in governance.required_checks)
    lines.extend(
        [
            "",
            f"Protection profile: `{governance.protection_profile}` with {governance.trusted_maintainers} trusted maintainer. Required human approvals: `{governance.required_approvals}`; CODEOWNER review required: `{str(governance.require_code_owner_reviews).lower()}`.",
            "",
            "The solo profile avoids impossible self-approval while every required check remains strict on the current branch. Independent review becomes required only after a second trusted maintainer is configured. There are no ruleset bypass actors; release and hardware gates remain independent canonical interlocks.",
            "",
            "## Immutable Workflow Dependencies",
            "",
            "| Action | Reviewed version | Commit | License |",
            "| --- | --- | --- | --- |",
        ]
    )
    for action in governance.actions:
        lines.append(
            f"| `{action.repository}` | `{action.version}` | `{action.commit}` | `{action.license_expression}` |"
        )
    lines.extend(
        [
            "",
            "## Repository Experience",
            "",
            "- CODEOWNERS derives from component ownership boundaries.",
            "- Issue forms request bounded, privacy-safe evidence and never imply hardware-write approval.",
            "- Pull requests surface canonical authority, schema, package, performance, privacy, and evidence impact.",
            "- Dependency updates are grouped by GitHub Actions, Cargo, and each Python integration root.",
            "- Labels and protected-main policy are reviewable generated plans and are verified against remote state.",
            "",
            "## Actions Job Summaries",
            "",
            "Fast and full verification jobs render `result.json` into the native GitHub Actions summary. The renderer reports structured facts and deliberately omits raw error text that could expose runner paths.",
            "",
        ]
    )
    lines.extend(f"- `{section}`" for section in governance.job_summary_sections)
    lines.extend(
        [
            "",
            "A missing result remains visible as unavailable, source-revision mismatches fail closed, and the release-gate section states that CI validates but cannot mutate gate state.",
            "",
            "## Discussions Plan",
            "",
            "| Category | Format | Purpose |",
            "| --- | --- | --- |",
        ]
    )
    for category in governance.discussions:
        lines.append(
            f"| {category.name} | `{category.format}` | {category.description} |"
        )
    lines.extend(
        [
            "",
            "The category plan is authorized only with `SUPPORT.md`, the code of conduct, privacy guidance, and explicit category boundaries present.",
            "",
            "## Project Plan",
            "",
            f"Planned project: [**{governance.project_title}**]({governance.project_url})",
            "",
            "| View | Layout | Grouping | Date field |",
            "| --- | --- | --- | --- |",
        ]
    )
    for view in governance.project_views:
        lines.append(
            f"| {view.name} | `{view.layout}` | `{view.group_by}` | `{view.date_field}` |"
        )
    lines.extend(
        [
            "",
            "| Field | Type | Options |",
            "| --- | --- | --- |",
        ]
    )
    for field in governance.project_fields:
        options = ", ".join(field.options) if field.options else "Date value"
        lines.append(f"| {field.name} | `{field.data_type}` | {options} |")
    lines.extend(
        [
            "",
            "The project is authorized as a typed roadmap driven by labeled issues. It does not represent release approval.",
            "",
            "## Security Preparation",
            "",
            "| Capability | State | Activation boundary | Data boundary |",
            "| --- | --- | --- | --- |",
        ]
    )
    for identifier, plan in governance.security_posture:
        lines.append(
            f"| `{identifier}` | `{plan.state}` | `{plan.activation_boundary}` | {plan.data_boundary} |"
        )
    lines.extend(
        [
            "",
            "## External Service Evaluation",
            "",
            "| Service | Decision | Permissions or data access | Privacy | Maintenance |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for evaluation in governance.service_evaluations:
        permissions = ", ".join(f"`{item}`" for item in evaluation.required_permissions)
        lines.append(
            f"| {evaluation.service} | `{evaluation.decision}` | {permissions} | {evaluation.privacy} | `{evaluation.maintenance_cost}` |"
        )
    lines.extend(["", "No external app or tracking service is required by this plan.", ""])
    return "\n".join(lines)
