# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

import json

from ..install import InstallManifest
from ..linux_runtime import LinuxRuntime


def compiled_plan(manifest: InstallManifest, runtime: LinuxRuntime) -> str:
    value = {
        "schema": "hyperflux-compiled-install-plan-v1",
        "install_manifest_sha256": manifest.source_sha256,
        "product": {
            "name": runtime.product.package_name,
            "version": runtime.product.version,
            "release": runtime.product.package_release,
        },
        "policy": {
            "hardware_writes_on_install": manifest.policy.hardware_writes_on_install,
            "start_service_on_install": manifest.policy.start_service_on_install,
            "enable_service_on_install": manifest.policy.enable_service_on_install,
            "preserve_configuration": manifest.policy.preserve_configuration,
        },
        "builds": [
            {
                "id": build.id,
                "kind": build.kind,
                "required": build.required,
                **({"source": build.source} if build.source is not None else {}),
                **({"package": build.package} if build.package is not None else {}),
                **({"target": build.target} if build.target is not None else {}),
                **({"output": build.output} if build.output is not None else {}),
                **(
                    {"destination": build.destination}
                    if build.destination is not None
                    else {}
                ),
                **({"mode": f"{build.mode:04o}"} if build.mode is not None else {}),
                **(
                    {"distribution": build.distribution}
                    if build.distribution is not None
                    else {}
                ),
                **(
                    {"capability": build.capability}
                    if build.capability is not None
                    else {}
                ),
            }
            for build in manifest.builds
        ],
        "payloads": [
            {
                "component": file.component,
                "source": file.source.relative_to(manifest.root).as_posix(),
                "destination": str(file.destination),
                "mode": f"{file.mode:04o}",
                "preserve": file.preserve,
            }
            for file in manifest.files
        ],
    }
    return json.dumps(value, indent=2, sort_keys=False, ensure_ascii=True) + "\n"


def markdown(manifest: InstallManifest, runtime: LinuxRuntime) -> str:
    required = sum(1 for build in manifest.builds if build.required)
    optional = len(manifest.builds) - required
    preserved = [file for file in manifest.files if file.preserve]
    lines = [
        "# Installation Contract",
        "",
        "> Generated by `./hfx generate`. Do not edit manually.",
        "",
        f"Canonical manifest digest: `{manifest.source_sha256}`.",
        "",
        f"Package: `{runtime.product.package_name}` `{runtime.product.version}` release "
        f"`{runtime.product.package_release}`.",
        "",
        "## Safety Policy",
        "",
        "| Action | Package behavior |",
        "| --- | --- |",
        "| Hardware writes during installation | Never |",
        "| Start bridge during installation | No |",
        "| Enable bridge during installation | No |",
        "| Existing configuration | Preserve |",
        "",
        "Package hooks prepare system metadata and delegate compatibility decisions to the "
        "tested activation utility. They do not contain receiver logic.",
        "",
        "## Build Products",
        "",
        f"The canonical plan contains `{required}` required and `{optional}` optional build products.",
        "",
        "| Component | Kind | Required | Destination or distribution |",
        "| --- | --- | --- | --- |",
    ]
    for build in manifest.builds:
        output = build.destination or build.distribution or "-"
        lines.append(
            f"| `{build.id}` | `{build.kind}` | "
            f"{'yes' if build.required else 'no'} | `{output}` |"
        )
    lines.extend(
        [
            "",
            "## Static Payload",
            "",
            f"The expanded source payload contains `{len(manifest.files)}` files. "
            "Every destination is normalized below `/etc` or `/usr` and checked for collisions.",
            "",
            "| Component | Files | Preserved destination |",
            "| --- | ---: | --- |",
        ]
    )
    for payload in manifest.payloads:
        files = [file for file in manifest.files if file.component == payload.id]
        preserve = payload.destination if payload.preserve else "-"
        lines.append(f"| `{payload.id}` | {len(files)} | `{preserve}` |")
    lines.extend(["", "## Configuration", ""])
    if preserved:
        lines.extend(
            f"- `{file.destination}` is package-manager preserved." for file in preserved
        )
    else:
        lines.append("No mutable configuration was declared, which is an invalid release state.")
    lines.extend(
        [
            "",
            "Arch, Debian, and RPM packaging must consume the same deterministic staged root "
            "instead of maintaining independent file lists.",
            "",
        ]
    )
    return "\n".join(lines)
