# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

import json
from pprint import pformat
from typing import Any


def _rust_string_slice(field: str, values: list[str], *, indent: str = "        ") -> list[str]:
    rendered = ", ".join(json.dumps(value) for value in values)
    line = f"{indent}{field}: &[{rendered}],"
    if len(line) <= 80:
        return [line]
    return [
        f"{indent}{field}: &[",
        *(f"{indent}    {json.dumps(value)}," for value in values),
        f"{indent}],",
    ]


def compiled_json(catalog: dict[str, Any]) -> str:
    return json.dumps(catalog, indent=2, sort_keys=True, ensure_ascii=True) + "\n"


def markdown(catalog: dict[str, Any]) -> str:
    lines = [
        "# Application Integrations",
        "",
        "> Generated by `./hfx generate`. Do not edit manually.",
        "",
        f"Integration source: `{catalog['source_sha256']}`",
        "",
        "Every adapter uses only the versioned HyperFlux SDK, preserves unrelated application devices, and owns no receiver encoding.",
        "",
        "## Upstream Contracts",
        "",
        "| Project | Version | Commit | Contract | Build network |",
        "| --- | --- | --- | --- | --- |",
    ]
    for upstream in catalog["upstreams"]:
        lines.append(
            f"| [{upstream['name']}]({upstream['repository'][:-4]}) | `{upstream['version']}` | "
            f"`{upstream['commit'][:12]}` | {upstream['api_contract']} | disabled |"
        )
    lines.extend(
        [
            "",
            "## Adapter Boundaries",
            "",
            "| Adapter | Delivery | Status | Coexistence | Protocols |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for adapter in catalog["adapters"]:
        versions = ", ".join(f"v{value}" for value in adapter["sdk_protocol_versions"])
        lines.append(
            f"| `{adapter['id']}` | {adapter['kind']} | {adapter['status']} | "
            f"{adapter['coexistence_policy']} | {versions} |"
        )
    lines.extend(
        [
            "",
            "## Non-Negotiable Rules",
            "",
            "- Integrations never open HID, USB, sysfs, or receiver session endpoints.",
            "- OpenRGB owns its model layouts, LED labels, profiles, and effect engine.",
            "- HyperFlux never suppresses unrelated OpenRGB, OpenRazer, or Polychromatic devices.",
            "- The optional OpenRazer compatibility service never claims the official daemon identity by default.",
            "- Upstream source revisions are reviewed inputs; builds never fetch mutable network state.",
            "",
        ]
    )
    return "\n".join(lines)


def rust_catalog(catalog: dict[str, Any]) -> str:
    lines = [
        "// Generated by ./hfx generate. Do not edit manually.",
        "// SPDX-License-Identifier: GPL-2.0-only",
        "",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub struct UpstreamRecord {",
        "    pub id: &'static str,",
        "    pub name: &'static str,",
        "    pub repository: &'static str,",
        "    pub version: &'static str,",
        "    pub commit: &'static str,",
        "    pub license_expression: &'static str,",
        "    pub api_contract: &'static str,",
        "    pub uses: &'static [&'static str],",
        "}",
        "",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub struct AdapterRecord {",
        "    pub id: &'static str,",
        "    pub application: &'static str,",
        "    pub kind: &'static str,",
        "    pub status: &'static str,",
        "    pub upstream_ids: &'static [&'static str],",
        "    pub sdk_protocol_versions: &'static [u16],",
        "    pub feature_families: &'static [&'static str],",
        "    pub coexistence_policy: &'static str,",
        "}",
        "",
        "pub const INTEGRATION_SOURCE_SHA256: &str =",
        f"    {json.dumps(catalog['source_sha256'])};",
        "",
        "pub const UPSTREAMS: &[UpstreamRecord] = &[",
    ]
    for value in catalog["upstreams"]:
        lines.extend(
            [
                "    UpstreamRecord {",
                f"        id: {json.dumps(value['id'])},",
                f"        name: {json.dumps(value['name'])},",
                f"        repository: {json.dumps(value['repository'])},",
                f"        version: {json.dumps(value['version'])},",
                f"        commit: {json.dumps(value['commit'])},",
                f"        license_expression: {json.dumps(value['license_expression'])},",
                f"        api_contract: {json.dumps(value['api_contract'])},",
                *_rust_string_slice("uses", value["uses"]),
                "    },",
            ]
        )
    lines.extend(["];", "", "pub const ADAPTERS: &[AdapterRecord] = &["])
    for value in catalog["adapters"]:
        versions = ", ".join(str(item) for item in value["sdk_protocol_versions"])
        lines.extend(
            [
                "    AdapterRecord {",
                f"        id: {json.dumps(value['id'])},",
                f"        application: {json.dumps(value['application'])},",
                f"        kind: {json.dumps(value['kind'])},",
                f"        status: {json.dumps(value['status'])},",
                *_rust_string_slice("upstream_ids", value["upstream_ids"]),
                f"        sdk_protocol_versions: &[{versions}],",
                *_rust_string_slice("feature_families", value["feature_families"]),
                f"        coexistence_policy: {json.dumps(value['coexistence_policy'])},",
                "    },",
            ]
        )
    lines.extend(
        [
            "];",
            "",
            "#[must_use]",
            "pub fn upstream_by_id(id: &str) -> Option<&'static UpstreamRecord> {",
            "    UPSTREAMS.iter().find(|value| value.id == id)",
            "}",
            "",
            "#[must_use]",
            "pub fn adapter_by_id(id: &str) -> Option<&'static AdapterRecord> {",
            "    ADAPTERS.iter().find(|value| value.id == id)",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def cpp_catalog(catalog: dict[str, Any]) -> str:
    lines = [
        "// Generated by ./hfx generate. Do not edit manually.",
        "// SPDX-License-Identifier: GPL-2.0-only",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <span>",
        "#include <string_view>",
        "",
        "namespace hyperflux::integrations",
        "{",
        "struct UpstreamRecord",
        "{",
        "    std::string_view id;",
        "    std::string_view name;",
        "    std::string_view repository;",
        "    std::string_view version;",
        "    std::string_view commit;",
        "    std::string_view license_expression;",
        "    std::string_view api_contract;",
        "    std::span<const std::string_view> uses;",
        "};",
        "",
        "struct AdapterRecord",
        "{",
        "    std::string_view id;",
        "    std::string_view application;",
        "    std::string_view kind;",
        "    std::string_view status;",
        "    std::span<const std::string_view> upstream_ids;",
        "    std::span<const std::uint16_t> sdk_protocol_versions;",
        "    std::span<const std::string_view> feature_families;",
        "    std::string_view coexistence_policy;",
        "};",
        "",
        f"inline constexpr std::string_view integration_source_sha256 = {json.dumps(catalog['source_sha256'])};",
        "",
    ]
    for index, value in enumerate(catalog["upstreams"]):
        uses = ", ".join(json.dumps(item) for item in value["uses"])
        lines.append(
            f"inline constexpr std::array<std::string_view, {len(value['uses'])}> upstream_uses_{index} {{{{{uses}}}}};"
        )
    for index, value in enumerate(catalog["adapters"]):
        upstreams = ", ".join(json.dumps(item) for item in value["upstream_ids"])
        versions = ", ".join(str(item) for item in value["sdk_protocol_versions"])
        features = ", ".join(json.dumps(item) for item in value["feature_families"])
        lines.extend(
            [
                f"inline constexpr std::array<std::string_view, {len(value['upstream_ids'])}> adapter_upstreams_{index} {{{{{upstreams}}}}};",
                f"inline constexpr std::array<std::uint16_t, {len(value['sdk_protocol_versions'])}> adapter_protocols_{index} {{{{{versions}}}}};",
                f"inline constexpr std::array<std::string_view, {len(value['feature_families'])}> adapter_features_{index} {{{{{features}}}}};",
            ]
        )
    lines.extend(["", f"inline constexpr std::array<UpstreamRecord, {len(catalog['upstreams'])}> upstreams {{{{"])
    for index, value in enumerate(catalog["upstreams"]):
        lines.append(
            "    {"
            + ", ".join(
                json.dumps(value[key])
                for key in (
                    "id",
                    "name",
                    "repository",
                    "version",
                    "commit",
                    "license_expression",
                    "api_contract",
                )
            )
            + f", upstream_uses_{index}" + "},"
        )
    lines.extend(["}};", "", f"inline constexpr std::array<AdapterRecord, {len(catalog['adapters'])}> adapters {{{{"])
    for index, value in enumerate(catalog["adapters"]):
        lines.append(
            f"    {{{json.dumps(value['id'])}, {json.dumps(value['application'])}, {json.dumps(value['kind'])}, "
            f"{json.dumps(value['status'])}, adapter_upstreams_{index}, adapter_protocols_{index}, "
            f"adapter_features_{index}, {json.dumps(value['coexistence_policy'])}}},"
        )
    lines.extend(
        [
            "}};",
            "",
            "[[nodiscard]] constexpr const UpstreamRecord* upstream_by_id(std::string_view id)",
            "{",
            "    for(const auto& value : upstreams)",
            "    {",
            "        if(value.id == id)",
            "        {",
            "            return &value;",
            "        }",
            "    }",
            "    return nullptr;",
            "}",
            "",
            "} // namespace hyperflux::integrations",
            "",
        ]
    )
    return "\n".join(lines)


def python_catalog(catalog: dict[str, Any]) -> str:
    value = pformat(catalog, width=120, sort_dicts=True)
    return "\n".join(
        [
            '"""Generated by ./hfx generate. Do not edit manually."""',
            "# SPDX-License-Identifier: GPL-2.0-or-later",
            "",
            "from types import MappingProxyType",
            "from typing import Final",
            "",
            f"INTEGRATION_CATALOG: Final = {value}",
            "UPSTREAMS_BY_ID: Final = MappingProxyType({value['id']: value for value in INTEGRATION_CATALOG['upstreams']})",
            "ADAPTERS_BY_ID: Final = MappingProxyType({value['id']: value for value in INTEGRATION_CATALOG['adapters']})",
            "",
            '__all__ = ["ADAPTERS_BY_ID", "INTEGRATION_CATALOG", "UPSTREAMS_BY_ID"]',
            "",
        ]
    )


def python_openrazer_metadata(metadata: dict[str, Any]) -> str:
    value = pformat(metadata, width=120, sort_dicts=True)
    return "\n".join(
        [
            '"""Pinned OpenRazer presentation metadata generated by ./hfx generate."""',
            "# SPDX-License-Identifier: GPL-2.0-or-later",
            "",
            "from types import MappingProxyType",
            "from typing import Final",
            "",
            f"OPENRAZER_METADATA: Final = {value}",
            "OPENRAZER_DEVICES_BY_PROFILE: Final = MappingProxyType(",
            "    {value['profile_id']: value for value in OPENRAZER_METADATA['devices']}",
            ")",
            "",
            '__all__ = ["OPENRAZER_DEVICES_BY_PROFILE", "OPENRAZER_METADATA"]',
            "",
        ]
    )


def python_openrazer_compatibility_contract(contract: dict[str, Any]) -> str:
    value = pformat(contract, width=120, sort_dicts=True)
    return "\n".join(
        [
            '"""OpenRazer compatibility contract generated by ./hfx generate."""',
            "# SPDX-License-Identifier: GPL-2.0-or-later",
            "",
            "from typing import Final",
            "",
            f"OPENRAZER_COMPATIBILITY_CONTRACT: Final = {value}",
            "",
            '__all__ = ["OPENRAZER_COMPATIBILITY_CONTRACT"]',
            "",
        ]
    )
