# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

import re

from ..kernel_uapi import KernelUapi, UapiField, UapiStruct


def _macro(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", value).upper()


def _pascal(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def _rust_number(value: int) -> str:
    return f"{value:_}"


def _count_c(field: UapiField) -> str:
    if isinstance(field.count, str):
        return f"HFX_UAPI_{_macro(field.count)}"
    return str(field.count)


def _count_rust(field: UapiField) -> str:
    if isinstance(field.count, str):
        return f"HFX_UAPI_{_macro(field.count)}"
    return str(field.count)


def _c_type(type_name: str) -> str:
    primitive = {
        "u8": "__u8",
        "u16": "__u16",
        "u32": "__u32",
        "i32": "__s32",
        "u64": "__aligned_u64",
    }
    return primitive.get(type_name, f"struct hfx_uapi_{type_name}")


def _rust_type(type_name: str) -> str:
    primitive = {
        "u8": "u8",
        "u16": "u16",
        "u32": "u32",
        "i32": "i32",
        "u64": "AlignedU64",
    }
    return primitive.get(type_name, f"HfxUapi{_pascal(type_name)}")


def _rust_default(field: UapiField) -> str:
    if field.count is not None:
        value = (
            "0"
            if field.type_name in {"u8", "u16", "u32", "i32"}
            else f"{_rust_type(field.type_name)}::default()"
        )
        return f"[{value}; {_count_rust(field)}]"
    if field.type_name in {"u8", "u16", "u32", "i32"}:
        return "0"
    return f"{_rust_type(field.type_name)}::default()"


def _rust_can_derive_default(struct: UapiStruct, catalog: KernelUapi) -> bool:
    for field in struct.fields:
        if field.count is None:
            continue
        count = catalog.limits[field.count] if isinstance(field.count, str) else field.count
        if count > 32:
            return False
    return True


def c_header(catalog: KernelUapi) -> str:
    lines = [
        "/* Generated by ./hfx generate. Do not edit manually. */",
        "/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */",
        f"/* UAPI source SHA-256: {catalog.source_sha256} */",
        "",
        "#ifndef _UAPI_HYPERFLUX_NEXT_H",
        "#define _UAPI_HYPERFLUX_NEXT_H",
        "",
        "#include <linux/ioctl.h>",
        "#include <linux/types.h>",
        "",
        f"#define HFX_UAPI_ABI_VERSION {catalog.abi_version}U",
        f"#define HFX_UAPI_IOCTL_MAGIC 0x{catalog.ioctl_magic:02x}",
    ]
    for name, value in catalog.limits.items():
        suffix = "ULL" if value > 0xFFFFFFFF else "U"
        lines.append(f"#define HFX_UAPI_{_macro(name)} {value}{suffix}")
    for enum in catalog.enums:
        lines.append("")
        for value in enum.values:
            lines.append(
                f"#define HFX_UAPI_{_macro(enum.name)}_{_macro(value.name)} {value.value}U"
            )
    for struct in catalog.structs:
        lines.extend(["", f"struct hfx_uapi_{struct.name} {{"])
        for field in struct.fields:
            declaration = f"\t{_c_type(field.type_name)} {field.name}"
            if field.count is not None:
                declaration += f"[{_count_c(field)}]"
            lines.append(f"{declaration};")
        lines.append("};")
    direction = {"read": "_IOR", "write": "_IOW", "read_write": "_IOWR"}
    lines.append("")
    for ioctl in catalog.ioctls:
        lines.extend(
            [
                f"#define HFX_UAPI_IOCTL_{_macro(ioctl.name)} \\",
                f"\t{direction[ioctl.direction]}(HFX_UAPI_IOCTL_MAGIC, 0x{ioctl.number:02x}, \\",
                f"\t\tstruct hfx_uapi_{ioctl.struct_name})",
            ]
        )
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def rust_bindings(catalog: KernelUapi) -> str:
    count_limits = {
        field.count
        for struct in catalog.structs
        for field in struct.fields
        if isinstance(field.count, str)
    }
    lines = [
        "// Generated by ./hfx generate. Do not edit manually.",
        "// SPDX-License-Identifier: GPL-2.0-only",
        f"// UAPI source SHA-256: {catalog.source_sha256}",
        "",
        "#[repr(C, align(8))]",
        "#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]",
        "pub struct AlignedU64(pub u64);",
        "",
        f"pub const HFX_UAPI_ABI_VERSION: u32 = {catalog.abi_version};",
        f"pub const HFX_UAPI_IOCTL_MAGIC: u8 = 0x{catalog.ioctl_magic:02x};",
    ]
    for name, value in catalog.limits.items():
        rust_type = "usize" if name in count_limits else "u64"
        lines.append(
            f"pub const HFX_UAPI_{_macro(name)}: {rust_type} = {_rust_number(value)};"
        )
    for enum in catalog.enums:
        lines.append("")
        for value in enum.values:
            lines.append(
                f"pub const HFX_UAPI_{_macro(enum.name)}_{_macro(value.name)}: u32 = "
                f"{_rust_number(value.value)};"
            )
    for struct in catalog.structs:
        derives = "Clone, Copy, Debug, Default, Eq, PartialEq"
        if not _rust_can_derive_default(struct, catalog):
            derives = "Clone, Copy, Debug, Eq, PartialEq"
        lines.extend(
            [
                "",
                "#[repr(C)]",
                f"#[derive({derives})]",
                f"pub struct HfxUapi{_pascal(struct.name)} {{",
            ]
        )
        for field in struct.fields:
            rust_type = _rust_type(field.type_name)
            if field.count is not None:
                rust_type = f"[{rust_type}; {_count_rust(field)}]"
            lines.append(f"    pub {field.name}: {rust_type},")
        lines.append("}")
        if not _rust_can_derive_default(struct, catalog):
            lines.extend(
                [
                    "",
                    f"impl Default for HfxUapi{_pascal(struct.name)} {{",
                    "    fn default() -> Self {",
                    "        Self {",
                    *[
                        f"            {field.name}: {_rust_default(field)},"
                        for field in struct.fields
                    ],
                    "        }",
                    "    }",
                    "}",
                ]
            )
    direction = {"read": "Read", "write": "Write", "read_write": "ReadWrite"}
    lines.extend(
        [
            "",
            "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
            "pub enum IoctlDirection {",
            "    Read,",
            "    Write,",
            "    ReadWrite,",
            "}",
            "",
            "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
            "pub struct IoctlDescriptor {",
            "    pub number: u8,",
            "    pub direction: IoctlDirection,",
            "    pub size: usize,",
            "}",
        ]
    )
    for ioctl in catalog.ioctls:
        lines.extend(
            [
                "",
                f"pub const HFX_UAPI_IOCTL_{_macro(ioctl.name)}: IoctlDescriptor = IoctlDescriptor {{",
                f"    number: 0x{ioctl.number:02x},",
                f"    direction: IoctlDirection::{direction[ioctl.direction]},",
                f"    size: core::mem::size_of::<HfxUapi{_pascal(ioctl.struct_name)}>(),",
                "};",
            ]
        )
    return "\n".join(lines) + "\n"


def markdown(catalog: KernelUapi) -> str:
    lines = [
        "# Kernel UAPI",
        "",
        "> Generated by `./hfx generate`. Do not edit manually.",
        "",
        f"ABI version: `{catalog.abi_version}`.",
        "",
        "The UAPI contains fixed-width values, no pointers, and no application or product presentation.",
        "",
        "## Structures",
        "",
        "| Structure | Size | Purpose boundary |",
        "| --- | ---: | --- |",
    ]
    ioctl_structs = {item.struct_name: item.name for item in catalog.ioctls}
    for struct in catalog.structs:
        owner = ioctl_structs.get(struct.name, "nested payload")
        lines.append(f"| `hfx_uapi_{struct.name}` | {struct.size} | `{owner}` |")
    lines.extend(["", "## Ioctls", "", "| Name | Number | Direction | Structure |", "| --- | ---: | --- | --- |"])
    for ioctl in catalog.ioctls:
        lines.append(
            f"| `{ioctl.name}` | `0x{ioctl.number:02x}` | `{ioctl.direction}` | "
            f"`hfx_uapi_{ioctl.struct_name}` |"
        )
    lines.extend(
        [
            "",
            "## Ownership",
            "",
            "The kernel owns receiver generations, passive observation sequencing, one writer file, session expiry, revocation, and bounded envelope transport. The bridge owns profile selection, logical-device identities, capabilities, carrier maps, effects, scheduling, and application policy.",
            "",
        ]
    )
    return "\n".join(lines)
