# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

import json
from typing import Any


def compiled_json(catalog: dict[str, Any]) -> str:
    return json.dumps(catalog, indent=2, sort_keys=True, ensure_ascii=True) + "\n"


def _topology_summary(record: dict[str, Any]) -> str:
    topology = record["lighting_topology"]
    if not isinstance(topology, dict):
        return "not documented"
    dimensions = topology.get("matrix_dimensions")
    if isinstance(dimensions, list):
        return f"matrix {dimensions[0]}x{dimensions[1]}"
    rows = topology.get("rows")
    columns = topology.get("columns")
    parts = [f"slots {rows}x{columns}"]
    zones = topology.get("zones", [])
    if zones:
        parts.append("zones " + ", ".join(zone["name"] for zone in zones))
    if topology.get("layout_key"):
        parts.append(f"layout {topology['layout_key']}")
    return "; ".join(parts)


def _source_registration(record: dict[str, Any]) -> str:
    if record["record_id"].startswith("openrazer:"):
        return "hardware class"
    return "active detector" if record["facts"].get("detector_registered") else "table only"


def _markdown_value(value: Any) -> str:
    if isinstance(value, bool):
        return "supported" if value else "not supported"
    if isinstance(value, list):
        return ", ".join(str(item) for item in value)
    return str(value)


def render_knowledge_markdown(catalog: dict[str, Any]) -> str:
    source_index = {source["id"]: source for source in catalog["reviewed_sources"]}
    lines = [
        "# Device Knowledge and Route Assurance",
        "",
        "<!-- Generated by ./hfx generate. Do not edit directly. -->",
        "",
        f"Reviewed on `{catalog['reviewed_on']}`. This catalog separates manufacturer product documentation, exact records in pinned Linux projects, HyperFlux route mapping, and physical qualification. Evidence in one layer never grants authority in another.",
        "",
        "Bluetooth, direct USB, a product's own 2.4 GHz receiver, and the HyperFlux V2 receiver are independent routes. Application matrix slots can include unlit holes and are not automatically physical LED counts.",
        "",
        "| Candidate | Product facts | Primary sources | Exact code records | HyperFlux route | Open gaps |",
        "| --- | ---: | ---: | ---: | --- | ---: |",
    ]
    for candidate in catalog["candidates"]:
        coverage = candidate["coverage"]
        lines.append(
            f"| {candidate['official_name']} | {coverage['reviewed_fact_count']} | "
            f"{coverage['reviewed_source_count']} | {coverage['implementation_record_count']} | "
            f"`{candidate['hyperflux_support']}` | {coverage['open_gap_count']} |"
        )

    lines.extend(["", "## Candidate Detail", ""])
    for candidate in catalog["candidates"]:
        coverage = candidate["coverage"]
        lines.extend(
            [
                "<details>",
                f"<summary><strong>{candidate['official_name']}</strong> · {candidate['hyperflux_support']} · {coverage['open_gap_count']} open gaps</summary>",
                "",
                f"### {candidate['official_name']}",
                "",
                f"HyperFlux route: `{candidate['hyperflux_support']}`. Pinned code status: `{candidate['knowledge_status']}`.",
                "",
                "#### Connection Routes",
                "",
                "| Route | Product state | Exact Linux records | HyperFlux state |",
                "| --- | --- | ---: | --- |",
            ]
        )
        for route in candidate["transport_matrix"]:
            lines.append(
                f"| {route['label']} | `{route['product_state']}` | "
                f"{len(route['implementation_records'])} | `{route['hyperflux_state']}` |"
            )

        lines.extend(
            [
                "",
                "#### Reviewed Product Facts",
                "",
                "| Capability | Value | Routes | Assurance |",
                "| --- | --- | --- | --- |",
            ]
        )
        for fact in candidate["reviewed_facts"]:
            value = _markdown_value(fact["value"]).replace("|", "\\|")
            unit = f" {fact['unit']}" if fact.get("unit") else ""
            routes = ", ".join(f"`{route}`" for route in fact["routes"])
            lines.append(
                f"| `{fact['semantic_capability']}` | {value}{unit} | {routes} | "
                f"`{fact['assurance']}` |"
            )

        lines.extend(["", "Reviewed sources:", ""])
        for source_id in candidate["reviewed_source_ids"]:
            source = source_index[source_id]
            lines.append(
                f"- [{source['title']}]({source['url']}) - `{source['kind']}`, "
                f"revision `{source['revision']}`, checked `{source['retrieved_on']}`."
            )

        lines.extend(["", "#### Open Questions", ""])
        if candidate["knowledge_gaps"]:
            for gap in candidate["knowledge_gaps"]:
                lines.append(
                    f"- **{gap['title']}** (`{gap['status']}`): {gap['detail']}"
                )
        else:
            lines.append("No reviewed gap is recorded.")

        lines.extend(["", "#### Pinned Linux Implementation", ""])
        if candidate["source_records"]:
            lines.extend(
                [
                    "| Exact source record | Route | USB identity | Registration | Topology |",
                    "| --- | --- | --- | --- | --- |",
                ]
            )
            for record in candidate["source_records"]:
                identity = record["usb_identity"]
                usb_identity = (
                    f"{identity['vendor_id']:04x}:{identity['product_id']:04x}"
                    if isinstance(identity["vendor_id"], int)
                    else f"unknown:{identity['product_id']:04x}"
                )
                lines.append(
                    f"| [`{record['record_id']}`]({record['source_url']}) | "
                    f"`{record['source_route']}` | `{usb_identity}` | "
                    f"{_source_registration(record)} | {_topology_summary(record)} |"
                )
        else:
            lines.append("No exact record exists in either pinned Linux revision.")

        if candidate["source_conflicts"]:
            lines.extend(["", "Pinned code disagreements:", ""])
            for conflict in candidate["source_conflicts"]:
                values = ", ".join(f"`{value}`" for value in conflict["values"])
                lines.append(
                    f"- `{conflict['field']}` on `{conflict['route']}`: {values}. "
                    "The disagreement is not promoted into a HyperFlux profile."
                )

        if candidate["settings"]:
            lines.extend(
                [
                    "",
                    "| Pinned Linux semantic | Presentation | HyperFlux state | Missing capability |",
                    "| --- | --- | --- | --- |",
                ]
            )
            for setting in candidate["settings"]:
                missing = ", ".join(
                    f"`{value}`" for value in setting["missing_hyperflux_capabilities"]
                ) or "none"
                lines.append(
                    f"| `{setting['semantic_capability']}` | `{setting['presentation']}` | "
                    f"`{setting['control_state']}` | {missing} |"
                )

            source_vocab = [
                setting for setting in candidate["settings"] if setting["source_methods"]
            ]
            if source_vocab:
                lines.extend(
                    [
                        "",
                        "<details>",
                        "<summary>Methods exposed by the pinned OpenRazer revision</summary>",
                        "",
                        "These method names are implementation vocabulary, not a complete product capability list.",
                        "",
                    ]
                )
                for setting in source_vocab:
                    methods = ", ".join(f"`{value}`" for value in setting["source_methods"])
                    lines.append(f"- `{setting['semantic_capability']}`: {methods}")
                lines.extend(["", "</details>"])
        if candidate["notes"]:
            lines.extend(["", "Additional reviewed-link notes:", ""])
            lines.extend(f"- {note}" for note in candidate["notes"])
        lines.extend(["", "</details>", ""])

    lines.extend(
        [
            "## Assurance Vocabulary",
            "",
            "- `product-documented`: an official product source documents the fact.",
            "- `cross-documented`: more than one official source supports the fact.",
            "- `upstream-reported`: an upstream issue reports the fact; it is not manufacturer documentation.",
            "- `documented-and-implemented`: official documentation and an exact pinned Linux record intersect.",
            "- `physically-qualified`: an exact HyperFlux child profile maps the fact to a capability with public physical evidence.",
            "- `candidate-only`: the official mat list names the model, but no HyperFlux child profile grants controls.",
            "- `route-qualified`: an exact child profile grants only its explicitly evidenced capabilities.",
            "",
        ]
    )
    return "\n".join(lines)
