# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

from typing import Any


def markdown(contract: dict[str, Any]) -> str:
    states = ", ".join(f"`{state.title()}`" for state in contract["snapshot"]["evidence_states"])
    requirements = "\n".join(
        f"- `{requirement}`" for requirement in contract["write_capabilities"]["requirements"]
    )
    return f"""# Local Companion Contract

> Generated by `./hfx generate`. Do not edit manually.

The future local companion gives the static documentation portal a privacy-safe,
versioned view of an installed HyperFlux system. The website itself cannot detect
a driver, inspect USB, or write hardware.

## Read Boundary

- Endpoint: `GET {contract['snapshot']['path']}` on `{contract['base_url']}`.
- Transport: loopback-only HTTP with bounded JSON.
- Default access: read-only.
- Device evidence states: {states}.
- Pairing and a retained receiver route never imply that a device is active.

## Evidence States

| State | Meaning |
| --- | --- |
| `Active` | Fresh receiver evidence shows the device is currently active. |
| `Sleeping` | The paired device is retained, but bounded evidence identifies sleep. |
| `Disconnected` | The current generation has explicit route-removal evidence. |
| `Unknown` | Evidence is absent, stale, or insufficient for a stronger statement. |

## Optional Writes

Writes are disabled by default. A future lighting write requires every condition:

{requirements}

The maximum capability lifetime is {contract['write_capabilities']['maximum_ttl_seconds']} seconds.
Closing or expiring the capability returns the companion to read-only behavior.

## Privacy And Transport

Hardware serials and stable host identifiers are excluded. The companion never
uploads evidence silently, never uses WebHID, and never opens USB directly. All
hardware authority remains in the installed HyperFlux bridge and kernel path.
"""
