# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

from ..performance import PerformanceMetric


def performance_budgets_markdown(metrics: tuple[PerformanceMetric, ...]) -> str:
    software = sum(metric.status == "enforced-software" for metric in metrics)
    physical = len(metrics) - software
    lines = [
        "# Performance Budgets",
        "",
        "> Generated by `./hfx generate`. Do not edit manually.",
        "",
        f"Software-enforced metrics: `{software}`. Physical qualification metrics: `{physical}`.",
        "A declared physical budget remains blocked until measured on an exact installed candidate.",
        "",
        "| Metric | Maximum | Measurement | Status | Release block |",
        "| --- | ---: | --- | --- | --- |",
    ]
    for metric in metrics:
        maximum = f"{metric.maximum:g} {metric.unit}"
        lines.append(
            f"| `{metric.id}` {metric.title} | {maximum} | `{metric.measurement_kind}` | "
            f"`{metric.status}` | {'yes' if metric.release_blocking else 'no'} |"
        )
    lines.extend(["", "## Measurement Contracts", ""])
    for metric in metrics:
        lines.extend(
            [
                f"### {metric.title}",
                "",
                f"Source: [`{metric.source}`](../../{metric.source}); selector `{metric.selector}`.",
                f"Samples: {metric.sample_count}; warmups: {metric.warmup_count}.",
                "",
                metric.rationale,
                "",
            ]
        )
    return "\n".join(lines)
