# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

import json
from pprint import pformat
import re
from typing import Any


def _symbol(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()


def _variant(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in value.replace(".", "-").split("-"))


def _rust_strings(values: list[str]) -> str:
    return "&[" + ", ".join(json.dumps(value) for value in values) + "]"


def _rust_variants(type_name: str, values: list[str]) -> str:
    return "&[" + ", ".join(f"{type_name}::{_variant(value)}" for value in values) + "]"


def _wrapped_numbers(values: list[int], *, indent: str = "    ", width: int = 100) -> list[str]:
    lines: list[str] = []
    current = indent
    for value in values:
        token = f"{value},"
        separator = "" if current == indent else " "
        if len(current) + len(separator) + len(token) > width:
            lines.append(current)
            current = indent + token
        else:
            current += separator + token
    if current != indent:
        lines.append(current)
    return lines


def compiled_json(catalog: dict[str, Any]) -> str:
    return json.dumps(catalog, indent=2, sort_keys=True, ensure_ascii=True) + "\n"


def fixtures_json(fixtures: dict[str, Any]) -> str:
    return json.dumps(fixtures, indent=2, sort_keys=True, ensure_ascii=True) + "\n"


def markdown(catalog: dict[str, Any]) -> str:
    capabilities = {item["id"]: item for item in catalog["capabilities"]}
    lines = [
        "# Supported Hardware",
        "",
        "> Generated by `./hfx generate`. Do not edit manually.",
        "",
        f"Profile source: `{catalog['source_sha256']}`",
        "",
        "Support is capability-specific. A listed model does not transfer its transport map to a similar name or PID.",
        "",
        "## Qualified Profiles",
        "",
        "| Profile | Kind | Identity | Runtime binding | Read capabilities | Write capabilities |",
        "| --- | --- | --- | --- | ---: | ---: |",
    ]
    for profile in catalog["profiles"]:
        identity = profile["identity"]
        if "product_id" in identity:
            hardware = f"`{identity['vendor_id']:04x}:{identity['product_id']:04x}`"
        else:
            hardware = "reviewed surface metadata (no USB identity)"
        reads = sum(capabilities[item["id"]]["access"] == "read" for item in profile["capabilities"])
        writes = sum(capabilities[item["id"]]["access"] == "write" for item in profile["capabilities"])
        lines.append(
            f"| **{identity['model_name']}**<br><code>{profile['profile_id']}</code> | "
            f"{profile['device_kind']} | {hardware} | `{profile['runtime_sha256'][:12]}` | {reads} | {writes} |"
        )
    lines.extend(
        [
            "",
            "## Composition Contract",
            "",
            "- A receiver profile, zero or more independently qualified child profiles, and optional surface metadata compose at runtime.",
            "- A mouse does not require a keyboard. A keyboard does not require a mouse.",
            "- Unknown children expose observed identity safely and receive **zero writable capabilities**.",
            "- Surface variants are never selected by an invented USB product ID.",
            "- The receiver and mat are transport and system-information objects, not addressable RGB controllers.",
            "",
            "## Qualified Lighting Topology",
            "",
            "| Device | Physical LEDs | Application slots | Transport map | Presentation owner |",
            "| --- | ---: | ---: | --- | --- |",
        ]
    )
    for profile in catalog["profiles"]:
        lighting = profile.get("transport", {}).get("lighting")
        if not lighting:
            continue
        mapping = lighting["application_index_to_carrier"]
        map_summary = "identity" if mapping == list(range(len(mapping))) else "profile permutation"
        lines.append(
            f"| {profile['identity']['model_name']} | {lighting['physical_led_count']} | "
            f"{lighting['application_slot_count']} | {map_summary} | {profile['presentation']['owner']} |"
        )
    lines.extend(
        [
            "",
            "OpenRGB owns key names, geometry, zones, layout variants, and visual ordering. HyperFlux owns only the evidence-backed receiver-carrier translation and transport policy.",
            "",
            "## Compatibility Candidates",
            "",
            "These names came from a dated official compatibility snapshot. They are investigation candidates, not writable support claims.",
            "",
            "| Candidate | Kind | Support | Writable capabilities |",
            "| --- | --- | --- | ---: |",
        ]
    )
    for candidate in catalog["candidates"]:
        lines.append(f"| {candidate['official_name']} | {candidate['device_kind']} | candidate | 0 |")
    lines.extend(["", "## Evidence Boundaries", ""])
    for claim in catalog["evidence_claims"]:
        limits = " ".join(claim["limitations"])
        lines.extend(
            [
                f"### `{claim['id']}`",
                "",
                f"{claim['summary']} Evidence: `{claim['evidence_level']}`; privacy: `{claim['privacy']}`.",
                "",
                f"Boundary: {limits}",
                "",
            ]
        )
    return "\n".join(lines)


def rust_catalog(catalog: dict[str, Any]) -> str:
    lines = [
        "// Generated by ./hfx generate. Do not edit manually.",
        "// SPDX-License-Identifier: GPL-2.0-only",
        f"// Profile source SHA-256: {catalog['source_sha256']}",
        "",
        "use hfx_domain::{DeviceKind, ProfileKind, RouteKind, SupportLevel};",
        "",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub struct CapabilityRecord {",
        "    pub id: &'static str,",
        "    pub support_level: SupportLevel,",
        "    pub writable: bool,",
        "}",
        "",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub struct LightingTopology {",
        "    pub physical_led_count: u16,",
        "    pub application_slot_count: u16,",
        "    pub carrier_count: u16,",
        "    pub rows: u16,",
        "    pub columns: u16,",
        "    pub application_index_to_carrier: &'static [u16],",
        "}",
        "",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub struct PresentationRecord {",
        "    pub upstream_id: &'static str,",
        "    pub owner: &'static str,",
        "    pub project_version: &'static str,",
        "    pub source_commit: &'static str,",
        "    pub model_key: &'static str,",
        "    pub layout_key: Option<&'static str>,",
        "    pub transport_variant: &'static str,",
        "}",
        "",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub struct ProfileRecord {",
        "    pub id: &'static str,",
        "    pub runtime_sha256: &'static str,",
        "    pub revision: u32,",
        "    pub profile_kind: ProfileKind,",
        "    pub device_kind: DeviceKind,",
        "    pub vendor_id: Option<u16>,",
        "    pub product_id: Option<u16>,",
        "    pub model_name: &'static str,",
        "    pub transport_backend_id: Option<u32>,",
        "    pub protocol_family: Option<&'static str>,",
        "    pub receiver_protocols: &'static [&'static str],",
        "    pub routes: &'static [RouteKind],",
        "    pub supported_child_kinds: &'static [DeviceKind],",
        "    pub required_sibling_kinds: &'static [DeviceKind],",
        "    pub exact_child_combinations: bool,",
        "    pub capabilities: &'static [CapabilityRecord],",
        "    pub lighting: Option<LightingTopology>,",
        "    pub presentation: Option<PresentationRecord>,",
        "}",
        "",
        "pub const PROFILE_SOURCE_SHA256: &str =",
        f'    "{catalog["source_sha256"]}";',
        "",
    ]
    capability_defs = {item["id"]: item for item in catalog["capabilities"]}
    for index, profile in enumerate(catalog["profiles"]):
        capabilities_name = f"CAPABILITIES_{index}"
        lines.append(f"const {capabilities_name}: &[CapabilityRecord] = &[")
        for capability in profile["capabilities"]:
            writable = str(capability_defs[capability["id"]]["access"] == "write").lower()
            lines.extend(
                [
                    "    CapabilityRecord {",
                    f'        id: "{capability["id"]}",',
                    f"        support_level: SupportLevel::{_variant(capability['support_level'])},",
                    f"        writable: {writable},",
                    "    },",
                ]
            )
        lines.extend(["];", ""])
        lighting = profile.get("transport", {}).get("lighting")
        if lighting:
            values = ", ".join(str(value) for value in lighting["application_index_to_carrier"])
            single_line = f"const CARRIERS_{index}: &[u16] = &[{values}];"
            if len(single_line) <= 100:
                lines.extend([single_line, ""])
            else:
                lines.append(f"const CARRIERS_{index}: &[u16] = &[")
                lines.extend(_wrapped_numbers(lighting["application_index_to_carrier"]))
                lines.extend(["];", ""])
    lines.extend(["pub const PROFILES: &[ProfileRecord] = &[",])
    for index, profile in enumerate(catalog["profiles"]):
        identity = profile["identity"]
        compatibility = profile.get("compatibility", {})
        vendor = f"Some({identity['vendor_id']})" if "vendor_id" in identity else "None"
        product = f"Some({identity['product_id']})" if "product_id" in identity else "None"
        protocol_family = compatibility.get("protocol_family")
        protocol_family = f"Some({json.dumps(protocol_family)})" if protocol_family else "None"
        backend_id = profile.get("transport", {}).get("backend_id")
        backend_id = f"Some({backend_id})" if backend_id is not None else "None"
        receiver_protocols = _rust_strings(compatibility.get("receiver_protocols", []))
        routes = _rust_variants("RouteKind", compatibility.get("routes", []))
        supported_child_kinds = _rust_variants(
            "DeviceKind", compatibility.get("supported_child_kinds", [])
        )
        required_sibling_kinds = _rust_variants(
            "DeviceKind", compatibility.get("required_sibling_kinds", [])
        )
        exact_child_combinations = str(compatibility.get("exact_child_combinations", False)).lower()
        lighting = profile.get("transport", {}).get("lighting")
        if lighting:
            lighting_value = None
        else:
            lighting_value = "None"
        presentation = profile.get("presentation")
        if presentation:
            layout_key = (
                f"Some({json.dumps(presentation['layout_key'])})"
                if presentation["layout_key"] is not None
                else "None"
            )
            presentation_lines = [
                "        presentation: Some(PresentationRecord {",
                f"            upstream_id: {json.dumps(presentation['upstream_id'])},",
                f"            owner: {json.dumps(presentation['owner'])},",
                f"            project_version: {json.dumps(presentation['project_version'])},",
                f"            source_commit: {json.dumps(presentation['source_commit'])},",
                f"            model_key: {json.dumps(presentation['model_key'])},",
                f"            layout_key: {layout_key},",
                f"            transport_variant: {json.dumps(presentation['transport_variant'])},",
                "        }),",
            ]
        else:
            presentation_lines = ["        presentation: None,"]
        lines.extend(
            [
                "    ProfileRecord {",
                f'        id: "{profile["profile_id"]}",',
                f'        runtime_sha256: "{profile["runtime_sha256"]}",',
                f"        revision: {profile['revision']},",
                f"        profile_kind: ProfileKind::{_variant(profile['kind'])},",
                f"        device_kind: DeviceKind::{_variant(profile['device_kind'])},",
                f"        vendor_id: {vendor},",
                f"        product_id: {product},",
                f'        model_name: "{profile["identity"]["model_name"]}",',
                f"        transport_backend_id: {backend_id},",
                f"        protocol_family: {protocol_family},",
                f"        receiver_protocols: {receiver_protocols},",
                f"        routes: {routes},",
                f"        supported_child_kinds: {supported_child_kinds},",
                f"        required_sibling_kinds: {required_sibling_kinds},",
                f"        exact_child_combinations: {exact_child_combinations},",
                f"        capabilities: CAPABILITIES_{index},",
                *(
                    [
                        "        lighting: Some(LightingTopology {",
                        f"            physical_led_count: {lighting['physical_led_count']},",
                        f"            application_slot_count: {lighting['application_slot_count']},",
                        f"            carrier_count: {lighting['carrier_count']},",
                        f"            rows: {lighting['rows']},",
                        f"            columns: {lighting['columns']},",
                        f"            application_index_to_carrier: CARRIERS_{index},",
                        "        }),",
                    ]
                    if lighting
                    else [f"        lighting: {lighting_value},"]
                ),
                *presentation_lines,
                "    },",
            ]
        )
    lines.extend(
        [
            "];",
            "",
            "#[must_use]",
            "pub fn profile_by_id(id: &str) -> Option<&'static ProfileRecord> {",
            "    PROFILES.iter().find(|profile| profile.id == id)",
            "}",
            "",
            "#[must_use]",
            "pub fn receiver_profile_by_usb_id(",
            "    vendor_id: u16,",
            "    product_id: u16,",
            ") -> Option<&'static ProfileRecord> {",
            "    PROFILES.iter().find(|profile| {",
            "        profile.profile_kind == ProfileKind::Receiver",
            "            && profile.vendor_id == Some(vendor_id)",
            "            && profile.product_id == Some(product_id)",
            "    })",
            "}",
            "",
            "#[must_use]",
            "pub fn child_profile_by_product_id(product_id: u16) -> Option<&'static ProfileRecord> {",
            "    PROFILES.iter().find(|profile| {",
            "        profile.profile_kind == ProfileKind::Child && profile.product_id == Some(product_id)",
            "    })",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def cpp_catalog(catalog: dict[str, Any]) -> str:
    capability_defs = {item["id"]: item for item in catalog["capabilities"]}
    lines = [
        "// Generated by ./hfx generate. Do not edit manually.",
        "// SPDX-License-Identifier: GPL-2.0-only",
        f"// Profile source SHA-256: {catalog['source_sha256']}",
        "",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <optional>",
        "#include <span>",
        "#include <string_view>",
        "",
        "#include <hyperflux/generated/domain_types.hpp>",
        "",
        "namespace hyperflux::profiles",
        "{",
        "",
        "struct CapabilityRecord",
        "{",
        "    std::string_view id;",
        "    SupportLevel support_level;",
        "    bool writable;",
        "};",
        "",
        "struct LightingTopology",
        "{",
        "    std::uint16_t physical_led_count;",
        "    std::uint16_t application_slot_count;",
        "    std::uint16_t carrier_count;",
        "    std::uint16_t rows;",
        "    std::uint16_t columns;",
        "    std::span<const std::uint16_t> application_index_to_carrier;",
        "};",
        "",
        "struct PresentationRecord",
        "{",
        "    std::string_view upstream_id;",
        "    std::string_view owner;",
        "    std::string_view project_version;",
        "    std::string_view source_commit;",
        "    std::string_view model_key;",
        "    std::optional<std::string_view> layout_key;",
        "    std::string_view transport_variant;",
        "};",
        "",
        "struct ProfileRecord",
        "{",
        "    std::string_view id;",
        "    std::string_view runtime_sha256;",
        "    std::uint32_t revision;",
        "    ProfileKind profile_kind;",
        "    DeviceKind device_kind;",
        "    bool has_usb_identity;",
        "    std::uint16_t vendor_id;",
        "    std::uint16_t product_id;",
        "    std::string_view model_name;",
        "    std::optional<std::uint32_t> transport_backend_id;",
        "    std::string_view protocol_family;",
        "    std::span<const std::string_view> receiver_protocols;",
        "    std::span<const RouteKind> routes;",
        "    std::span<const DeviceKind> supported_child_kinds;",
        "    std::span<const DeviceKind> required_sibling_kinds;",
        "    bool exact_child_combinations;",
        "    std::span<const CapabilityRecord> capabilities;",
        "    const LightingTopology* lighting;",
        "    const PresentationRecord* presentation;",
        "};",
        "",
        f'inline constexpr std::string_view profile_source_sha256 = "{catalog["source_sha256"]}";',
        "",
    ]
    for index, profile in enumerate(catalog["profiles"]):
        compatibility = profile.get("compatibility", {})
        receiver_protocols = compatibility.get("receiver_protocols", [])
        routes = compatibility.get("routes", [])
        supported_child_kinds = compatibility.get("supported_child_kinds", [])
        required_sibling_kinds = compatibility.get("required_sibling_kinds", [])
        lines.extend(
            [
                f"inline constexpr std::array<std::string_view, {len(receiver_protocols)}> receiver_protocols_{index} {{{{"
                + ", ".join(json.dumps(value) for value in receiver_protocols)
                + "}};",
                f"inline constexpr std::array<RouteKind, {len(routes)}> routes_{index} {{{{"
                + ", ".join(f"RouteKind::{_variant(value)}" for value in routes)
                + "}};",
                f"inline constexpr std::array<DeviceKind, {len(supported_child_kinds)}> supported_child_kinds_{index} {{{{"
                + ", ".join(f"DeviceKind::{_variant(value)}" for value in supported_child_kinds)
                + "}};",
                f"inline constexpr std::array<DeviceKind, {len(required_sibling_kinds)}> required_sibling_kinds_{index} {{{{"
                + ", ".join(f"DeviceKind::{_variant(value)}" for value in required_sibling_kinds)
                + "}};",
                "",
            ]
        )
        lines.append(f"inline constexpr std::array<CapabilityRecord, {len(profile['capabilities'])}> capabilities_{index} {{{{")
        for capability in profile["capabilities"]:
            writable = str(capability_defs[capability["id"]]["access"] == "write").lower()
            lines.append(
                f'    {{"{capability["id"]}", SupportLevel::{_variant(capability["support_level"])}, {writable}}},'
            )
        lines.extend(["}};", ""])
        lighting = profile.get("transport", {}).get("lighting")
        if lighting:
            mapping = ", ".join(str(value) for value in lighting["application_index_to_carrier"])
            lines.extend(
                [
                    f"inline constexpr std::array<std::uint16_t, {len(lighting['application_index_to_carrier'])}> carriers_{index} {{{{{mapping}}}}};",
                    f"inline constexpr LightingTopology lighting_{index} {{",
                    f"    {lighting['physical_led_count']}, {lighting['application_slot_count']}, {lighting['carrier_count']}, {lighting['rows']}, {lighting['columns']}, carriers_{index}",
                    "};",
                    "",
                ]
            )
        presentation = profile.get("presentation")
        if presentation:
            layout_key = (
                f"std::string_view{{{json.dumps(presentation['layout_key'])}}}"
                if presentation["layout_key"] is not None
                else "std::nullopt"
            )
            lines.extend(
                [
                    f"inline constexpr PresentationRecord presentation_{index} {{",
                    f"    {json.dumps(presentation['upstream_id'])}, {json.dumps(presentation['owner'])},",
                    f"    {json.dumps(presentation['project_version'])}, {json.dumps(presentation['source_commit'])},",
                    f"    {json.dumps(presentation['model_key'])}, {layout_key},",
                    f"    {json.dumps(presentation['transport_variant'])}",
                    "};",
                    "",
                ]
            )
    lines.append(f"inline constexpr std::array<ProfileRecord, {len(catalog['profiles'])}> catalog {{{{")
    for index, profile in enumerate(catalog["profiles"]):
        identity = profile["identity"]
        compatibility = profile.get("compatibility", {})
        has_usb = "vendor_id" in identity
        vendor = identity.get("vendor_id", 0)
        product = identity.get("product_id", 0)
        protocol_family = json.dumps(compatibility.get("protocol_family", ""))
        backend_id = profile.get("transport", {}).get("backend_id")
        backend_id = (
            f"std::uint32_t{{{backend_id}}}" if backend_id is not None else "std::nullopt"
        )
        exact_child_combinations = str(compatibility.get("exact_child_combinations", False)).lower()
        lighting = f"&lighting_{index}" if profile.get("transport", {}).get("lighting") else "nullptr"
        presentation = f"&presentation_{index}" if profile.get("presentation") else "nullptr"
        lines.append(
            "    {"
            f'"{profile["profile_id"]}", "{profile["runtime_sha256"]}", {profile["revision"]}, ProfileKind::{_variant(profile["kind"])}, '
            f'DeviceKind::{_variant(profile["device_kind"])}, {str(has_usb).lower()}, {vendor}, {product}, '
            f'"{profile["identity"]["model_name"]}", {backend_id}, {protocol_family}, receiver_protocols_{index}, routes_{index}, '
            f'supported_child_kinds_{index}, required_sibling_kinds_{index}, {exact_child_combinations}, capabilities_{index}, {lighting}, {presentation}'
            "},"
        )
    lines.extend(
        [
            "}};",
            "",
            "[[nodiscard]] constexpr const ProfileRecord* profile_by_id(std::string_view id)",
            "{",
            "    for(const auto& profile : catalog)",
            "    {",
            "        if(profile.id == id)",
            "        {",
            "            return &profile;",
            "        }",
            "    }",
            "    return nullptr;",
            "}",
            "",
            "} // namespace hyperflux::profiles",
            "",
        ]
    )
    return "\n".join(lines)


def python_catalog(catalog: dict[str, Any]) -> str:
    value = pformat(catalog, width=120, sort_dicts=True)
    return "\n".join(
        [
            '"""Generated by ./hfx generate. Do not edit manually."""',
            "# SPDX-License-Identifier: GPL-2.0-or-later",
            "",
            "from types import MappingProxyType",
            "from typing import Final",
            "",
            f"PROFILE_SOURCE_SHA256: Final = {catalog['source_sha256']!r}",
            f"PROFILE_CATALOG: Final = {value}",
            "PROFILES_BY_ID: Final = MappingProxyType({profile['profile_id']: profile for profile in PROFILE_CATALOG['profiles']})",
            "",
            '__all__ = ["PROFILE_CATALOG", "PROFILE_SOURCE_SHA256", "PROFILES_BY_ID"]',
            "",
        ]
    )


def kernel_receiver_table(catalog: dict[str, Any]) -> str:
    lines = [
        "/* Generated by ./hfx generate. Do not edit manually. */",
        "/* SPDX-License-Identifier: GPL-2.0-only */",
        f"/* Profile source SHA-256: {catalog['source_sha256']} */",
        "",
        "#ifndef HFX_RECEIVER_PROFILE",
        '#error "Define HFX_RECEIVER_PROFILE before including this table"',
        "#endif",
        "",
    ]
    for profile in catalog["profiles"]:
        if profile["kind"] != "receiver":
            continue
        identity = profile["identity"]
        transport = profile["transport"]
        lines.append(
            f'HFX_RECEIVER_PROFILE(0x{identity["vendor_id"]:04x}, '
            f'0x{identity["product_id"]:04x}, {transport["backend_id"]})'
        )
    lines.extend(["", "#undef HFX_RECEIVER_PROFILE", ""])
    return "\n".join(lines)
