# SPDX-License-Identifier: GPL-2.0-only

from __future__ import annotations

from ..release import ReleaseGate


def release_gates_markdown(gates: tuple[ReleaseGate, ...]) -> str:
    satisfied = sum(gate.status == "software-satisfied" for gate in gates)
    lines = [
        "# Release Gates",
        "",
        "> Generated by `./hfx generate`. Do not edit manually.",
        "",
        f"Software-satisfied gates: `{satisfied}` of `{len(gates)}`.",
        "A software-satisfied gate is not a release, hardware qualification, or publication decision.",
        "",
        "| Gate | Status | Physical evidence | Publication decision |",
        "| --- | --- | --- | --- |",
    ]
    for gate in gates:
        lines.append(
            f"| `{gate.id}` {gate.title} | `{gate.status}` | "
            f"{'required' if gate.physical_evidence_required else 'no'} | "
            f"{'required' if gate.publication_authorization_required else 'no'} |"
        )
    lines.extend(["", "## Criteria And Remaining Work", ""])
    for gate in gates:
        lines.extend([f"### {gate.id}: {gate.title}", "", "Criteria:", ""])
        lines.extend(f"- {item}" for item in gate.criteria)
        lines.extend(["", "Evidence:", ""])
        lines.extend(f"- [`{path}`](../../{path})" for path in gate.evidence)
        lines.extend(["", "Remaining:", ""])
        if gate.remaining:
            lines.extend(f"- {item}" for item in gate.remaining)
        else:
            lines.append("- No remaining work inside this gate's defined software scope.")
        lines.append("")
    return "\n".join(lines)
