// Generated by ./hfx generate. Do not edit manually.
// SPDX-License-Identifier: GPL-2.0-only

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UpstreamRecord {
    pub id: &'static str,
    pub name: &'static str,
    pub repository: &'static str,
    pub version: &'static str,
    pub commit: &'static str,
    pub license_expression: &'static str,
    pub api_contract: &'static str,
    pub uses: &'static [&'static str],
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AdapterRecord {
    pub id: &'static str,
    pub application: &'static str,
    pub kind: &'static str,
    pub status: &'static str,
    pub upstream_ids: &'static [&'static str],
    pub sdk_protocol_versions: &'static [u16],
    pub feature_families: &'static [&'static str],
    pub coexistence_policy: &'static str,
}

pub const INTEGRATION_SOURCE_SHA256: &str =
    "5174b3a4a6cd59dc6e1059b8be44ec924ebdff35712f7bf5ebfa3612c4fae356";

pub const UPSTREAMS: &[UpstreamRecord] = &[
    UpstreamRecord {
        id: "openrazer",
        name: "OpenRazer",
        repository: "https://github.com/openrazer/openrazer.git",
        version: "3.12.1-41-g6820f9d",
        commit: "6820f9da169d354bc7e6e93a0aa8683a6bb75792",
        license_expression: "GPL-2.0-or-later AND CC-BY-SA-4.0",
        api_contract: "org.razer 3.x metadata and D-Bus vocabulary",
        uses: &["compatibility-contract", "metadata-import"],
    },
    UpstreamRecord {
        id: "openrgb",
        name: "OpenRGB",
        repository: "https://github.com/CalcProgrammer1/OpenRGB.git",
        version: "1.0rc3",
        commit: "6fbcf62d7694e7b92fd0a5884b40b92984fbd1b0",
        license_expression: "GPL-2.0-only",
        api_contract: "OpenRGB plugin API 4",
        uses: &[
            "effect-engine",
            "model-layout-registry",
            "plugin-build-contract",
        ],
    },
    UpstreamRecord {
        id: "polychromatic",
        name: "Polychromatic",
        repository: "https://github.com/polychromatic/polychromatic.git",
        version: "0.9.7-7-g716737b",
        commit: "716737bf444ab7e962f4d3b7a5188b2f07c0c4a1",
        license_expression: "GPL-3.0-only",
        api_contract: "Polychromatic 0.9 native backend contract",
        uses: &["backend-contract", "presentation-reference"],
    },
];

pub const ADAPTERS: &[AdapterRecord] = &[
    AdapterRecord {
        id: "openrazer-compatibility",
        application: "OpenRazer-compatible clients",
        kind: "compatibility-service",
        status: "planned",
        upstream_ids: &["openrazer"],
        sdk_protocol_versions: &[4],
        feature_families: &["inventory", "lighting", "ownership", "telemetry"],
        coexistence_policy: "private-explicit-service-only",
    },
    AdapterRecord {
        id: "openrgb-native",
        application: "OpenRGB",
        kind: "native-plugin",
        status: "in-progress",
        upstream_ids: &["openrgb"],
        sdk_protocol_versions: &[4],
        feature_families: &[
            "effects",
            "inventory",
            "lighting",
            "ownership",
            "presentation",
            "telemetry",
        ],
        coexistence_policy: "application-plugin",
    },
    AdapterRecord {
        id: "polychromatic-native",
        application: "Polychromatic",
        kind: "native-backend",
        status: "planned",
        upstream_ids: &["openrazer", "polychromatic"],
        sdk_protocol_versions: &[4],
        feature_families: &[
            "inventory",
            "lighting",
            "ownership",
            "presentation",
            "telemetry",
        ],
        coexistence_policy: "native-backend-beside-existing",
    },
];

#[must_use]
pub fn upstream_by_id(id: &str) -> Option<&'static UpstreamRecord> {
    UPSTREAMS.iter().find(|value| value.id == id)
}

#[must_use]
pub fn adapter_by_id(id: &str) -> Option<&'static AdapterRecord> {
    ADAPTERS.iter().find(|value| value.id == id)
}
