// Generated by ./hfx generate. Do not edit manually.
// SPDX-License-Identifier: GPL-2.0-only

use hfx_domain::{ErrorSeverity, PrivacyClass};
use serde::{Deserialize, Serialize};
use std::fmt;
use std::str::FromStr;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CatalogValueError {
    type_name: &'static str,
}

impl CatalogValueError {
    const fn new(type_name: &'static str) -> Self {
        Self { type_name }
    }
}

impl fmt::Display for CatalogValueError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "unknown wire value for {}", self.type_name)
    }
}

impl std::error::Error for CatalogValueError {}

macro_rules! wire_enum {
    ($name:ident { $($variant:ident => $wire:literal,)+ }) => {
        #[derive(
            Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize,
        )]
        pub enum $name {
            $(#[serde(rename = $wire)] $variant,)+
        }

        impl $name {
            #[must_use]
            pub const fn as_str(self) -> &'static str {
                match self {
                    $(Self::$variant => $wire,)+
                }
            }
        }

        impl FromStr for $name {
            type Err = CatalogValueError;

            fn from_str(value: &str) -> Result<Self, Self::Err> {
                match value {
                    $($wire => Ok(Self::$variant),)+
                    _ => Err(CatalogValueError::new(stringify!($name))),
                }
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str(self.as_str())
            }
        }
    };
}

wire_enum!(ErrorCode {
    HfxDeadline001 => "HFX-DEADLINE-001",
    HfxGeneration001 => "HFX-GENERATION-001",
    HfxIntegration001 => "HFX-INTEGRATION-001",
    HfxInternal001 => "HFX-INTERNAL-001",
    HfxKernel001 => "HFX-KERNEL-001",
    HfxOutcome001 => "HFX-OUTCOME-001",
    HfxOutcome002 => "HFX-OUTCOME-002",
    HfxOwnership001 => "HFX-OWNERSHIP-001",
    HfxOwnership002 => "HFX-OWNERSHIP-002",
    HfxPersistence001 => "HFX-PERSISTENCE-001",
    HfxPersistence002 => "HFX-PERSISTENCE-002",
    HfxProfile001 => "HFX-PROFILE-001",
    HfxProfile002 => "HFX-PROFILE-002",
    HfxProtocol001 => "HFX-PROTOCOL-001",
    HfxProtocol002 => "HFX-PROTOCOL-002",
    HfxQueue001 => "HFX-QUEUE-001",
    HfxRequest001 => "HFX-REQUEST-001",
    HfxService001 => "HFX-SERVICE-001",
    HfxTransport001 => "HFX-TRANSPORT-001",
    HfxTransport002 => "HFX-TRANSPORT-002",
    HfxTransport003 => "HFX-TRANSPORT-003",
});

wire_enum!(RemediationId {
    AcquireNewLease => "acquire-new-lease",
    ActivateInstalledDriver => "activate-installed-driver",
    CollectSupportBundle => "collect-support-bundle",
    CorrectRequest => "correct-request",
    DisableUnsupportedFeature => "disable-unsupported-feature",
    LookupTransactionOutcome => "lookup-transaction-outcome",
    QualifyDevice => "qualify-device",
    ReconcileTransactionState => "reconcile-transaction-state",
    RefreshGeneration => "refresh-generation",
    ReleaseOwner => "release-owner",
    RepairStateStorage => "repair-state-storage",
    RetryBounded => "retry-bounded",
    StartBridge => "start-bridge",
    SubmitBeforeDeadline => "submit-before-deadline",
    UpdateIntegration => "update-integration",
    UpdateProtocolPeer => "update-protocol-peer",
    VerifyProfileCatalog => "verify-profile-catalog",
});

wire_enum!(ErrorClass {
    Deadline => "deadline",
    Generation => "generation",
    Integration => "integration",
    Internal => "internal",
    Kernel => "kernel",
    Outcome => "outcome",
    Ownership => "ownership",
    Persistence => "persistence",
    Profile => "profile",
    Protocol => "protocol",
    Queue => "queue",
    Request => "request",
    Service => "service",
    Transport => "transport",
});

wire_enum!(RetryPolicy {
    Never => "never",
    BoundedBackoff => "bounded-backoff",
    AfterRemediation => "after-remediation",
    OutcomeLookupOnly => "outcome-lookup-only",
});

wire_enum!(SideEffectCertaintyPolicy {
    NotApplicable => "not-applicable",
    MustBeNone => "must-be-none",
    RuntimeReported => "runtime-reported",
    Possible => "possible",
    Partial => "partial",
});

wire_enum!(ErrorLifecycleState {
    Active => "active",
    Deprecated => "deprecated",
    Retired => "retired",
});

wire_enum!(ErrorOwner {
    Kernel => "kernel",
    Bridge => "bridge",
    Sdk => "sdk",
    Integration => "integration",
    Packaging => "packaging",
    Tooling => "tooling",
});

wire_enum!(SafeDetailKind {
    Boolean => "boolean",
    U16 => "u16",
    U32 => "u32",
    U64Decimal => "u64-decimal",
    Identifier => "identifier",
    Text => "text",
    Enum => "enum",
});

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RemediationDescriptor {
    pub id: RemediationId,
    pub title: &'static str,
    pub safe_action: &'static str,
    pub verification: &'static str,
    pub automatic: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct LifecycleDescriptor {
    pub state: ErrorLifecycleState,
    pub introduced_in: &'static str,
    pub deprecated_in: Option<&'static str>,
    pub replacement_code: Option<ErrorCode>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SafeDetailFieldDescriptor {
    pub name: &'static str,
    pub kind: SafeDetailKind,
    pub required: bool,
    pub maximum_length: Option<usize>,
    pub maximum_value: Option<u64>,
    pub allowed_values: &'static [&'static str],
    pub privacy: PrivacyClass,
    pub description: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ErrorDescriptor {
    pub code: ErrorCode,
    pub error_class: ErrorClass,
    pub severity: ErrorSeverity,
    pub retry_policy: RetryPolicy,
    pub side_effect_certainty_policy: SideEffectCertaintyPolicy,
    pub remediation_id: RemediationId,
    pub safe_detail_fields: &'static [SafeDetailFieldDescriptor],
    pub lifecycle: LifecycleDescriptor,
    pub owner: ErrorOwner,
    pub technical_cause: &'static str,
    pub user_explanation: &'static str,
    pub privacy: PrivacyClass,
    pub docs_path: &'static str,
}

pub const ERROR_CATALOG_SHA256: &str =
    "dc21516800b761970c0e7c14a030424a56235610f3355f70f70259e2e4843e91";
pub const MAX_ERROR_COUNT: usize = 256;
pub const MAX_REMEDIATION_COUNT: usize = 128;
pub const MAX_SAFE_DETAIL_FIELDS: usize = 12;
pub const MAX_SAFE_DETAIL_LENGTH: usize = 256;

pub const REMEDIATIONS: &[RemediationDescriptor] = &[
    RemediationDescriptor {
        id: RemediationId::AcquireNewLease,
        title: "Acquire a current lease",
        safe_action: "Request a new lease for the complete resource set before submitting another operation.",
        verification: "Read the ownership snapshot and confirm the new lease is current.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::ActivateInstalledDriver,
        title: "Activate the installed driver",
        safe_action: "Use the platform's documented reboot or receiver-disconnect activation path.",
        verification: "Run Doctor and confirm the loaded and installed driver identities match.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::CollectSupportBundle,
        title: "Collect a privacy-safe support bundle",
        safe_action: "Preview and create the bounded HyperFlux support bundle for the unresolved internal failure.",
        verification: "Confirm the bundle preview excludes private paths, serials, raw reports, and arbitrary logs.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::CorrectRequest,
        title: "Correct the request",
        safe_action: "Correct the named request field and submit a new request with a new request identifier.",
        verification: "Validate the corrected request against the negotiated protocol schema.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::DisableUnsupportedFeature,
        title: "Disable the unsupported feature",
        safe_action: "Continue without the feature or use a peer that advertises it during negotiation.",
        verification: "Repeat negotiation and inspect the enabled feature set.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::LookupTransactionOutcome,
        title: "Resolve the existing transaction",
        safe_action: "Look up the existing transaction identifier; do not resubmit the hardware operation.",
        verification: "Confirm the transaction reaches exactly one recorded terminal outcome.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::QualifyDevice,
        title: "Use a qualified device capability",
        safe_action: "Keep the device read-only until an evidence-backed profile qualifies the requested capability.",
        verification: "Inspect the capability snapshot and confirm the support level permits the operation.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::ReconcileTransactionState,
        title: "Reconcile the current device state",
        safe_action: "Do not repeat the old hardware operation automatically; refresh device state and submit only a new intentional request.",
        verification: "Confirm the application has refreshed the active generation and is not replaying the unavailable transaction.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::RefreshGeneration,
        title: "Refresh receiver state",
        safe_action: "Discard state from the old generation and request a fresh snapshot before new work.",
        verification: "Confirm the request uses the currently active generation identifier.",
        automatic: true,
    },
    RemediationDescriptor {
        id: RemediationId::ReleaseOwner,
        title: "Release the current owner",
        safe_action: "Release control in the owning application or close it, then request ownership again.",
        verification: "Read the ownership snapshot and confirm the resource has no conflicting owner.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::RepairStateStorage,
        title: "Repair state storage",
        safe_action: "Restore writable, schema-compatible state storage without deleting the last known-good copy.",
        verification: "Restart the bridge and confirm it can read and transactionally commit its state.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::RetryBounded,
        title: "Retry within the declared bound",
        safe_action: "Retry with bounded backoff only while the original deadline remains valid.",
        verification: "Confirm the new attempt is admitted once and produces one terminal outcome.",
        automatic: true,
    },
    RemediationDescriptor {
        id: RemediationId::StartBridge,
        title: "Start the bridge service",
        safe_action: "Start or restart the compatible HyperFlux bridge service.",
        verification: "Run Doctor and confirm the bridge diagnostic endpoint is ready.",
        automatic: true,
    },
    RemediationDescriptor {
        id: RemediationId::SubmitBeforeDeadline,
        title: "Submit a fresh operation",
        safe_action: "Create a new request with a deadline that has not elapsed; do not revive the expired request.",
        verification: "Confirm admission occurs before the new monotonic deadline.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::UpdateIntegration,
        title: "Update the application integration",
        safe_action: "Install an integration compatible with the negotiated HyperFlux SDK protocol.",
        verification: "Restart the application and confirm protocol negotiation succeeds.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::UpdateProtocolPeer,
        title: "Update the protocol peer",
        safe_action: "Update either peer so their supported protocol version ranges overlap.",
        verification: "Repeat negotiation and confirm one common protocol version is selected.",
        automatic: false,
    },
    RemediationDescriptor {
        id: RemediationId::VerifyProfileCatalog,
        title: "Verify the profile catalog",
        safe_action: "Reload the generated profile catalog and retain read-only behavior until its digest matches.",
        verification: "Confirm the active profile identifier, revision, and digest match the generated catalog.",
        automatic: true,
    },
];

const DETAILS_0: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "deadline_ms",
        kind: SafeDetailKind::U64Decimal,
        required: true,
        maximum_length: None,
        maximum_value: Some(18_446_744_073_709_551_615),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Expired monotonic deadline.",
    },
    SafeDetailFieldDescriptor {
        name: "request_id",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(128),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::PublicSummary,
        description: "Rejected request identity.",
    },
];

const DETAILS_1: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "active_generation",
        kind: SafeDetailKind::U64Decimal,
        required: true,
        maximum_length: None,
        maximum_value: Some(18_446_744_073_709_551_615),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Current receiver generation.",
    },
    SafeDetailFieldDescriptor {
        name: "requested_generation",
        kind: SafeDetailKind::U64Decimal,
        required: true,
        maximum_length: None,
        maximum_value: Some(18_446_744_073_709_551_615),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Generation carried by the rejected request.",
    },
];

const DETAILS_2: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "integration",
        kind: SafeDetailKind::Text,
        required: true,
        maximum_length: Some(96),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Application integration name.",
    },
    SafeDetailFieldDescriptor {
        name: "protocol_range",
        kind: SafeDetailKind::Text,
        required: true,
        maximum_length: Some(32),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Protocol range advertised by the integration.",
    },
];

const DETAIL_VALUES_3_1: &[&str] = &[
    "bridge",
    "kernel",
    "persistence",
    "protocol",
    "sdk",
    "transport",
];

const DETAILS_3: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "invariant_id",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(64),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Stable violated invariant identifier.",
    },
    SafeDetailFieldDescriptor {
        name: "subsystem",
        kind: SafeDetailKind::Enum,
        required: true,
        maximum_length: None,
        maximum_value: None,
        allowed_values: DETAIL_VALUES_3_1,
        privacy: PrivacyClass::Public,
        description: "Subsystem that raised the invariant failure.",
    },
];

const DETAILS_4: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "installed_abi",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(64),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Installed kernel interface identity.",
    },
    SafeDetailFieldDescriptor {
        name: "loaded_abi",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(64),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Currently loaded kernel interface identity.",
    },
];

const DETAILS_5: &[SafeDetailFieldDescriptor] = &[SafeDetailFieldDescriptor {
    name: "transaction_id",
    kind: SafeDetailKind::Identifier,
    required: true,
    maximum_length: Some(128),
    maximum_value: None,
    allowed_values: &[],
    privacy: PrivacyClass::PublicSummary,
    description: "Transaction identity that has no retained or eviction record.",
}];

const DETAILS_6: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "history_capacity",
        kind: SafeDetailKind::U16,
        required: true,
        maximum_length: None,
        maximum_value: Some(4_096),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Configured retained outcome capacity.",
    },
    SafeDetailFieldDescriptor {
        name: "transaction_id",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(128),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::PublicSummary,
        description: "Transaction identity whose terminal record aged out.",
    },
];

const DETAILS_7: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "owner_name",
        kind: SafeDetailKind::Text,
        required: false,
        maximum_length: Some(96),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::PublicSummary,
        description: "Current application owner when available.",
    },
    SafeDetailFieldDescriptor {
        name: "resource_id",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(128),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::PublicSummary,
        description: "Contended logical resource.",
    },
];

const DETAIL_VALUES_8_1: &[&str] = &["expired", "released", "revoked"];

const DETAILS_8: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "lease_id",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(128),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::PublicSummary,
        description: "Expired or revoked lease identity.",
    },
    SafeDetailFieldDescriptor {
        name: "lease_state",
        kind: SafeDetailKind::Enum,
        required: true,
        maximum_length: None,
        maximum_value: None,
        allowed_values: DETAIL_VALUES_8_1,
        privacy: PrivacyClass::Public,
        description: "Terminal lease state.",
    },
];

const DETAIL_VALUES_9_0: &[&str] = &["load", "migrate", "validate"];

const DETAIL_VALUES_9_1: &[&str] = &[
    "corrupt",
    "incompatible-schema",
    "missing",
    "permission-denied",
];

const DETAILS_9: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "operation",
        kind: SafeDetailKind::Enum,
        required: true,
        maximum_length: None,
        maximum_value: None,
        allowed_values: DETAIL_VALUES_9_0,
        privacy: PrivacyClass::Public,
        description: "Failed state-read phase.",
    },
    SafeDetailFieldDescriptor {
        name: "reason",
        kind: SafeDetailKind::Enum,
        required: true,
        maximum_length: None,
        maximum_value: None,
        allowed_values: DETAIL_VALUES_9_1,
        privacy: PrivacyClass::Public,
        description: "Sanitized failure reason.",
    },
];

const DETAIL_VALUES_10_0: &[&str] = &["commit", "rollback", "snapshot"];

const DETAIL_VALUES_10_1: &[&str] = &["io-failure", "permission-denied", "validation-failed"];

const DETAILS_10: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "operation",
        kind: SafeDetailKind::Enum,
        required: true,
        maximum_length: None,
        maximum_value: None,
        allowed_values: DETAIL_VALUES_10_0,
        privacy: PrivacyClass::Public,
        description: "Failed state-write phase.",
    },
    SafeDetailFieldDescriptor {
        name: "reason",
        kind: SafeDetailKind::Enum,
        required: true,
        maximum_length: None,
        maximum_value: None,
        allowed_values: DETAIL_VALUES_10_1,
        privacy: PrivacyClass::Public,
        description: "Sanitized failure reason.",
    },
];

const DETAILS_11: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "capability",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(96),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Requested semantic capability.",
    },
    SafeDetailFieldDescriptor {
        name: "product_id",
        kind: SafeDetailKind::U16,
        required: false,
        maximum_length: None,
        maximum_value: Some(65_535),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Observed USB product identifier when available.",
    },
];

const DETAILS_12: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "active_digest",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(64),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Digest bound to the active generation.",
    },
    SafeDetailFieldDescriptor {
        name: "catalog_digest",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(64),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Digest from the generated profile catalog.",
    },
    SafeDetailFieldDescriptor {
        name: "profile_id",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(128),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Selected profile identity.",
    },
];

const DETAILS_13: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "client_max_version",
        kind: SafeDetailKind::U16,
        required: true,
        maximum_length: None,
        maximum_value: Some(65_535),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Highest protocol version supported by the client.",
    },
    SafeDetailFieldDescriptor {
        name: "client_min_version",
        kind: SafeDetailKind::U16,
        required: true,
        maximum_length: None,
        maximum_value: Some(65_535),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Lowest protocol version supported by the client.",
    },
    SafeDetailFieldDescriptor {
        name: "server_max_version",
        kind: SafeDetailKind::U16,
        required: true,
        maximum_length: None,
        maximum_value: Some(65_535),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Highest protocol version supported by the bridge.",
    },
    SafeDetailFieldDescriptor {
        name: "server_min_version",
        kind: SafeDetailKind::U16,
        required: true,
        maximum_length: None,
        maximum_value: Some(65_535),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Lowest protocol version supported by the bridge.",
    },
];

const DETAILS_14: &[SafeDetailFieldDescriptor] = &[SafeDetailFieldDescriptor {
    name: "feature",
    kind: SafeDetailKind::Identifier,
    required: true,
    maximum_length: Some(64),
    maximum_value: None,
    allowed_values: &[],
    privacy: PrivacyClass::Public,
    description: "Requested protocol feature identifier.",
}];

const DETAIL_VALUES_15_1: &[&str] = &[
    "configuration",
    "diagnostics",
    "effects",
    "events",
    "restore",
];

const DETAILS_15: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "capacity",
        kind: SafeDetailKind::U16,
        required: true,
        maximum_length: None,
        maximum_value: Some(4_096),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Configured queue capacity.",
    },
    SafeDetailFieldDescriptor {
        name: "queue",
        kind: SafeDetailKind::Enum,
        required: true,
        maximum_length: None,
        maximum_value: None,
        allowed_values: DETAIL_VALUES_15_1,
        privacy: PrivacyClass::Public,
        description: "Bounded queue that rejected admission.",
    },
];

const DETAIL_VALUES_16_1: &[&str] = &[
    "duplicate",
    "missing",
    "out-of-range",
    "unknown",
    "unsupported",
];

const DETAILS_16: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "field",
        kind: SafeDetailKind::Text,
        required: true,
        maximum_length: Some(128),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Schema field path without request data.",
    },
    SafeDetailFieldDescriptor {
        name: "reason",
        kind: SafeDetailKind::Enum,
        required: true,
        maximum_length: None,
        maximum_value: None,
        allowed_values: DETAIL_VALUES_16_1,
        privacy: PrivacyClass::Public,
        description: "Sanitized validation reason.",
    },
    SafeDetailFieldDescriptor {
        name: "request_id",
        kind: SafeDetailKind::Identifier,
        required: false,
        maximum_length: Some(128),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::PublicSummary,
        description: "Request identity when parsing reached it.",
    },
];

const DETAIL_VALUES_17_0: &[&str] = &[
    "activating",
    "active-unready",
    "failed",
    "inactive",
    "stopping",
    "unavailable",
];

const DETAILS_17: &[SafeDetailFieldDescriptor] = &[SafeDetailFieldDescriptor {
    name: "service_state",
    kind: SafeDetailKind::Enum,
    required: true,
    maximum_length: None,
    maximum_value: None,
    allowed_values: DETAIL_VALUES_17_0,
    privacy: PrivacyClass::Public,
    description: "Sanitized bridge service state.",
}];

const DETAIL_VALUES_18_0: &[&str] = &["device-absent", "session-unavailable", "transport-busy"];

const DETAILS_18: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "reason",
        kind: SafeDetailKind::Enum,
        required: true,
        maximum_length: None,
        maximum_value: None,
        allowed_values: DETAIL_VALUES_18_0,
        privacy: PrivacyClass::Public,
        description: "Sanitized pre-dispatch failure reason.",
    },
    SafeDetailFieldDescriptor {
        name: "transaction_id",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(128),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::PublicSummary,
        description: "Transaction that did not begin transport.",
    },
];

const DETAILS_19: &[SafeDetailFieldDescriptor] = &[SafeDetailFieldDescriptor {
    name: "transaction_id",
    kind: SafeDetailKind::Identifier,
    required: true,
    maximum_length: Some(128),
    maximum_value: None,
    allowed_values: &[],
    privacy: PrivacyClass::PublicSummary,
    description: "Transaction whose transport outcome is uncertain.",
}];

const DETAILS_20: &[SafeDetailFieldDescriptor] = &[
    SafeDetailFieldDescriptor {
        name: "delivered_frames",
        kind: SafeDetailKind::U16,
        required: true,
        maximum_length: None,
        maximum_value: Some(4_096),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Frames terminally delivered before failure.",
    },
    SafeDetailFieldDescriptor {
        name: "total_frames",
        kind: SafeDetailKind::U16,
        required: true,
        maximum_length: None,
        maximum_value: Some(4_096),
        allowed_values: &[],
        privacy: PrivacyClass::Public,
        description: "Frames declared by the transaction.",
    },
    SafeDetailFieldDescriptor {
        name: "transaction_id",
        kind: SafeDetailKind::Identifier,
        required: true,
        maximum_length: Some(128),
        maximum_value: None,
        allowed_values: &[],
        privacy: PrivacyClass::PublicSummary,
        description: "Partially delivered transaction identity.",
    },
];

pub const ERRORS: &[ErrorDescriptor] = &[
    ErrorDescriptor {
        code: ErrorCode::HfxDeadline001,
        error_class: ErrorClass::Deadline,
        severity: ErrorSeverity::Warning,
        retry_policy: RetryPolicy::Never,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::MustBeNone,
        remediation_id: RemediationId::SubmitBeforeDeadline,
        safe_detail_fields: DETAILS_0,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "The request deadline elapsed before transport admission.",
        user_explanation: "The operation expired before HyperFlux could safely start it.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-deadline-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxGeneration001,
        error_class: ErrorClass::Generation,
        severity: ErrorSeverity::Warning,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::MustBeNone,
        remediation_id: RemediationId::RefreshGeneration,
        safe_detail_fields: DETAILS_1,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "The request references a receiver generation that is no longer active.",
        user_explanation: "The receiver reconnected or resumed, so the application must refresh its device state.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-generation-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxIntegration001,
        error_class: ErrorClass::Integration,
        severity: ErrorSeverity::Error,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::NotApplicable,
        remediation_id: RemediationId::UpdateIntegration,
        safe_detail_fields: DETAILS_2,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Integration,
        technical_cause: "The application integration is incompatible with the installed SDK protocol.",
        user_explanation: "This application adapter must be updated before it can use HyperFlux.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-integration-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxInternal001,
        error_class: ErrorClass::Internal,
        severity: ErrorSeverity::Critical,
        retry_policy: RetryPolicy::Never,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::RuntimeReported,
        remediation_id: RemediationId::CollectSupportBundle,
        safe_detail_fields: DETAILS_3,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "A declared HyperFlux invariant was violated.",
        user_explanation: "HyperFlux stopped the affected operation because an internal safety rule failed.",
        privacy: PrivacyClass::PublicSummary,
        docs_path: "docs/generated/error-catalog.md#hfx-internal-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxKernel001,
        error_class: ErrorClass::Kernel,
        severity: ErrorSeverity::Error,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::NotApplicable,
        remediation_id: RemediationId::ActivateInstalledDriver,
        safe_detail_fields: DETAILS_4,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Packaging,
        technical_cause: "The loaded kernel interface does not match the installed userspace contract.",
        user_explanation: "The newly installed driver is not active yet.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-kernel-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxOutcome001,
        error_class: ErrorClass::Outcome,
        severity: ErrorSeverity::Warning,
        retry_policy: RetryPolicy::Never,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::NotApplicable,
        remediation_id: RemediationId::ReconcileTransactionState,
        safe_detail_fields: DETAILS_5,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "The bounded bridge history has no retained or eviction record for the requested transaction.",
        user_explanation: "HyperFlux cannot determine the result of this transaction from its current history.",
        privacy: PrivacyClass::PublicSummary,
        docs_path: "docs/generated/error-catalog.md#hfx-outcome-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxOutcome002,
        error_class: ErrorClass::Outcome,
        severity: ErrorSeverity::Info,
        retry_policy: RetryPolicy::Never,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::NotApplicable,
        remediation_id: RemediationId::ReconcileTransactionState,
        safe_detail_fields: DETAILS_6,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "The transaction was known, but its terminal result aged out of bounded retained history.",
        user_explanation: "The transaction result is older than the history HyperFlux keeps in memory.",
        privacy: PrivacyClass::PublicSummary,
        docs_path: "docs/generated/error-catalog.md#hfx-outcome-002",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxOwnership001,
        error_class: ErrorClass::Ownership,
        severity: ErrorSeverity::Warning,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::MustBeNone,
        remediation_id: RemediationId::ReleaseOwner,
        safe_detail_fields: DETAILS_7,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "Another live client owns at least one requested resource.",
        user_explanation: "Another application currently controls this device function.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-ownership-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxOwnership002,
        error_class: ErrorClass::Ownership,
        severity: ErrorSeverity::Warning,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::MustBeNone,
        remediation_id: RemediationId::AcquireNewLease,
        safe_detail_fields: DETAILS_8,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "The lease no longer authorizes the requested resource set.",
        user_explanation: "The application's control lease ended before the operation started.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-ownership-002",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxPersistence001,
        error_class: ErrorClass::Persistence,
        severity: ErrorSeverity::Error,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::NotApplicable,
        remediation_id: RemediationId::RepairStateStorage,
        safe_detail_fields: DETAILS_9,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "Persisted bridge state could not be loaded and validated safely.",
        user_explanation: "HyperFlux could not read its saved state and kept hardware restoration disabled.",
        privacy: PrivacyClass::PublicSummary,
        docs_path: "docs/generated/error-catalog.md#hfx-persistence-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxPersistence002,
        error_class: ErrorClass::Persistence,
        severity: ErrorSeverity::Error,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::NotApplicable,
        remediation_id: RemediationId::RepairStateStorage,
        safe_detail_fields: DETAILS_10,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "A transactional state update could not be committed or rolled back safely.",
        user_explanation: "HyperFlux could not save its latest stable state.",
        privacy: PrivacyClass::PublicSummary,
        docs_path: "docs/generated/error-catalog.md#hfx-persistence-002",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxProfile001,
        error_class: ErrorClass::Profile,
        severity: ErrorSeverity::Warning,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::MustBeNone,
        remediation_id: RemediationId::QualifyDevice,
        safe_detail_fields: DETAILS_11,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "No evidence-backed profile qualifies the requested device capability.",
        user_explanation: "The device is visible, but this operation is not qualified for it.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-profile-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxProfile002,
        error_class: ErrorClass::Profile,
        severity: ErrorSeverity::Error,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::MustBeNone,
        remediation_id: RemediationId::VerifyProfileCatalog,
        safe_detail_fields: DETAILS_12,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "The active profile binding does not match the generated profile catalog.",
        user_explanation: "HyperFlux paused writes because its hardware profile changed.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-profile-002",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxProtocol001,
        error_class: ErrorClass::Protocol,
        severity: ErrorSeverity::Error,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::NotApplicable,
        remediation_id: RemediationId::UpdateProtocolPeer,
        safe_detail_fields: DETAILS_13,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Sdk,
        technical_cause: "The client and bridge protocol version ranges do not overlap.",
        user_explanation: "The application and HyperFlux service are not protocol-compatible.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-protocol-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxProtocol002,
        error_class: ErrorClass::Protocol,
        severity: ErrorSeverity::Warning,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::NotApplicable,
        remediation_id: RemediationId::DisableUnsupportedFeature,
        safe_detail_fields: DETAILS_14,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Sdk,
        technical_cause: "The request requires a feature that was not enabled during negotiation.",
        user_explanation: "This feature is unavailable with the current application and service combination.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-protocol-002",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxQueue001,
        error_class: ErrorClass::Queue,
        severity: ErrorSeverity::Warning,
        retry_policy: RetryPolicy::BoundedBackoff,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::MustBeNone,
        remediation_id: RemediationId::RetryBounded,
        safe_detail_fields: DETAILS_15,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "The bounded queue had no admissible capacity before the request deadline.",
        user_explanation: "HyperFlux is temporarily busy and did not start this operation.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-queue-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxRequest001,
        error_class: ErrorClass::Request,
        severity: ErrorSeverity::Error,
        retry_policy: RetryPolicy::Never,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::MustBeNone,
        remediation_id: RemediationId::CorrectRequest,
        safe_detail_fields: DETAILS_16,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Sdk,
        technical_cause: "The request violates the negotiated bounded protocol schema.",
        user_explanation: "The application sent a request HyperFlux cannot safely accept.",
        privacy: PrivacyClass::PublicSummary,
        docs_path: "docs/generated/error-catalog.md#hfx-request-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxService001,
        error_class: ErrorClass::Service,
        severity: ErrorSeverity::Error,
        retry_policy: RetryPolicy::AfterRemediation,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::NotApplicable,
        remediation_id: RemediationId::StartBridge,
        safe_detail_fields: DETAILS_17,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Packaging,
        technical_cause: "The compatible bridge service is stopped or is not ready to accept SDK requests.",
        user_explanation: "The HyperFlux service is not ready yet.",
        privacy: PrivacyClass::Public,
        docs_path: "docs/generated/error-catalog.md#hfx-service-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxTransport001,
        error_class: ErrorClass::Transport,
        severity: ErrorSeverity::Warning,
        retry_policy: RetryPolicy::BoundedBackoff,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::MustBeNone,
        remediation_id: RemediationId::RetryBounded,
        safe_detail_fields: DETAILS_18,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "Transport failed before any hardware frame was dispatched.",
        user_explanation: "The receiver was unavailable before HyperFlux sent anything.",
        privacy: PrivacyClass::PublicSummary,
        docs_path: "docs/generated/error-catalog.md#hfx-transport-001",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxTransport002,
        error_class: ErrorClass::Transport,
        severity: ErrorSeverity::Error,
        retry_policy: RetryPolicy::OutcomeLookupOnly,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::Possible,
        remediation_id: RemediationId::LookupTransactionOutcome,
        safe_detail_fields: DETAILS_19,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "Transport began, but the bridge could not prove whether the receiver accepted a frame.",
        user_explanation: "The operation may have reached the receiver, so HyperFlux will not repeat it automatically.",
        privacy: PrivacyClass::PublicSummary,
        docs_path: "docs/generated/error-catalog.md#hfx-transport-002",
    },
    ErrorDescriptor {
        code: ErrorCode::HfxTransport003,
        error_class: ErrorClass::Transport,
        severity: ErrorSeverity::Error,
        retry_policy: RetryPolicy::OutcomeLookupOnly,
        side_effect_certainty_policy: SideEffectCertaintyPolicy::Partial,
        remediation_id: RemediationId::LookupTransactionOutcome,
        safe_detail_fields: DETAILS_20,
        lifecycle: LifecycleDescriptor {
            state: ErrorLifecycleState::Active,
            introduced_in: "0.0.0-dev.1",
            deprecated_in: None,
            replacement_code: None,
        },
        owner: ErrorOwner::Bridge,
        technical_cause: "At least one declared frame was delivered before a later frame failed.",
        user_explanation: "The operation was only partly delivered and will not be repeated automatically.",
        privacy: PrivacyClass::PublicSummary,
        docs_path: "docs/generated/error-catalog.md#hfx-transport-003",
    },
];

#[must_use]
pub fn error_by_code(code: ErrorCode) -> &'static ErrorDescriptor {
    ERRORS
        .iter()
        .find(|descriptor| descriptor.code == code)
        .unwrap_or_else(|| unreachable!("generated ErrorCode has no descriptor"))
}

#[must_use]
pub fn remediation_by_id(id: RemediationId) -> &'static RemediationDescriptor {
    REMEDIATIONS
        .iter()
        .find(|descriptor| descriptor.id == id)
        .unwrap_or_else(|| unreachable!("generated RemediationId has no descriptor"))
}
