// Generated by ./hfx generate. Do not edit manually.
// SPDX-License-Identifier: GPL-2.0-only

use hfx_domain::{
    ActivityState, BatteryPercent, CapabilityId, ClientId, ClientName, ColorChannel,
    ComponentVersion, ConnectionMode, ContactState, DeliveredFrameCount, DeviceApplicationState,
    DeviceKind, DocumentationPath, DroppedEventCount, EndpointId, ErrorSeverity, EventBatchLimit,
    EventKind, EvidenceClaimId, EvidenceConfidence, FindingId, FrameCount, FrameIndex,
    FreshnessState, GenerationId, HumanMessage, LeaseDurationMs, LeaseId, LeaseState, LedCount,
    LogicalDeviceId, MonotonicMs, NegotiationToken, PairingState, PowerState, PresenceState,
    PrivacyClass, ProductId, ProfileDigest, ProfileId, ProjectionRevision, ProtocolErrorKind,
    ProtocolFeatureId, ProtocolSessionId, ProtocolVersion, QueueAdmission, QueueCapacity,
    ReceiverId, ReceiverLifecycleState, RequestDigest, RequestId, ResourceKind, RestoreState,
    RouteKind, RouteState, SequenceNumber, ServerInstanceId, SideEffectCertainty, SleepState,
    StableLightingMode, StreamEpoch, StreamId, SubscriptionId, SupportLevel, TelemetryAvailability,
    TransactionClass, TransactionId, TransactionState,
};
use serde::{Deserialize, Serialize};

pub const MINIMUM_PROTOCOL_VERSION: u16 = 3;
pub const MAXIMUM_PROTOCOL_VERSION: u16 = 3;
pub const MAX_WIRE_MESSAGE_BYTES: usize = 1_048_576;
pub const MAX_JSON_DEPTH: usize = 128;
pub const SUPPORTED_FEATURES: &[&str] = &[
    "ownership-leases",
    "atomic-transactions",
    "profile-bound-transactions",
    "semantic-stable-lighting",
    "event-subscriptions",
    "structured-diagnostics",
];

/// A method request with no method-specific fields.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct EmptyRequest {}

/// One canonical eight-bit RGB color.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RgbColor {
    /// Red channel.
    pub red: ColorChannel,
    /// Green channel.
    pub green: ColorChannel,
    /// Blue channel.
    pub blue: ColorChannel,
}

/// Bounded client protocol and feature offer.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ClientHello {
    /// Process-scoped client identity.
    pub client_id: ClientId,
    /// User-facing application name.
    pub client_name: ClientName,
    /// Oldest protocol accepted by the client.
    pub minimum_version: ProtocolVersion,
    /// Newest protocol accepted by the client.
    pub maximum_version: ProtocolVersion,
    /// Features without which this client cannot operate.
    pub required_features: Vec<ProtocolFeatureId>,
    /// Features the client can use when available.
    pub optional_features: Vec<ProtocolFeatureId>,
}

/// Negotiated protocol version and bridge feature set.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ServerHello {
    /// Mutually supported protocol version.
    pub selected_version: ProtocolVersion,
    /// Changes whenever the bridge process identity changes.
    pub server_instance_id: ServerInstanceId,
    /// Server-issued connection ownership identity.
    pub protocol_session_id: ProtocolSessionId,
    /// Binds subsequent requests to this negotiated selection.
    pub negotiation_token: NegotiationToken,
    /// Bridge component version.
    pub bridge_version: ComponentVersion,
    /// Protocol features enabled for this connection.
    pub enabled_features: Vec<ProtocolFeatureId>,
    /// Maximum retained event count.
    pub event_buffer_capacity: QueueCapacity,
}

/// One device-scoped writable resource.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ResourceKey {
    /// Receiver that owns the route.
    pub receiver_id: ReceiverId,
    /// Receiver generation to which ownership is bound.
    pub generation_id: GenerationId,
    /// Logical resource owner.
    pub device_id: LogicalDeviceId,
    /// Generic resource domain.
    pub kind: ResourceKind,
}

/// Atomic request for one or more writable resources.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LeaseRequest {
    /// Idempotency identity.
    pub request_id: RequestId,
    /// Requesting client.
    pub client_id: ClientId,
    /// Complete atomic resource set.
    pub resources: Vec<ResourceKey>,
    /// Renewable lease duration.
    pub duration_ms: LeaseDurationMs,
}

/// Granted ownership lease.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LeaseGrant {
    /// Lease identity.
    pub lease_id: LeaseId,
    /// Owning client.
    pub client_id: ClientId,
    /// Atomically owned resources.
    pub resources: Vec<ResourceKey>,
    /// Exclusive monotonic expiry.
    pub expires_at_ms: MonotonicMs,
    /// Current lease state.
    pub state: LeaseState,
}

/// Deterministic first conflict from an otherwise atomic lease request.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LeaseConflict {
    /// Current owner.
    pub conflicting_client: ClientId,
    /// First conflict in canonical resource order.
    pub conflicting_resource: ResourceKey,
}

/// Structured lease rejection unrelated to another owner.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LeaseRejection {
    /// Stable rejection category.
    pub error_kind: ProtocolErrorKind,
    /// Central error catalog reference.
    pub finding_id: FindingId,
}

/// Idempotent renewal of one existing lease.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RenewLeaseRequest {
    /// Idempotency identity.
    pub request_id: RequestId,
    /// Owning client.
    pub client_id: ClientId,
    /// Lease to renew.
    pub lease_id: LeaseId,
    /// New bounded duration.
    pub duration_ms: LeaseDurationMs,
}

/// Idempotent release of one existing lease.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ReleaseLeaseRequest {
    /// Idempotency identity.
    pub request_id: RequestId,
    /// Owning client.
    pub client_id: ClientId,
    /// Lease to release.
    pub lease_id: LeaseId,
}

/// Complete resumable position in one event stream projection.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct EventCursor {
    /// Bridge event-stream identity.
    pub stream_id: StreamId,
    /// Changes whenever the event stream restarts.
    pub stream_epoch: StreamEpoch,
    /// Snapshot and event projection contract revision.
    pub projection_revision: ProjectionRevision,
    /// Last event reflected by this cursor.
    pub sequence: SequenceNumber,
}

/// Independent route, power, sleep, activity, contact, and freshness facts.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct EndpointSnapshot {
    /// Stable logical route identity.
    pub endpoint_id: EndpointId,
    /// Transport route category.
    pub route_kind: RouteKind,
    /// Current route evidence.
    pub route_state: RouteState,
    /// User-facing connection mode.
    pub connection_mode: ConnectionMode,
    /// Explicit power evidence, independent of route.
    pub power_state: PowerState,
    /// Explicit sleep evidence.
    pub sleep_state: SleepState,
    /// Recent activity evidence.
    pub activity_state: ActivityState,
    /// Mat-contact evidence where applicable.
    pub contact_state: ContactState,
    /// Freshness of the route projection.
    pub freshness: FreshnessState,
    /// How directly the state was established.
    pub confidence: EvidenceConfidence,
    /// Privacy-safe evidence provenance when available.
    pub evidence_claim_id: Option<EvidenceClaimId>,
    /// Bridge-local observation instant.
    pub observed_at_ms: Option<MonotonicMs>,
}

/// Battery availability and value without collapsing unknown and unavailable.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BatteryObservation {
    /// Whether a current value exists.
    pub availability: TelemetryAvailability,
    /// Reported value only when availability is reported.
    pub percentage: Option<BatteryPercent>,
    /// Freshness of the battery observation.
    pub freshness: FreshnessState,
    /// How directly the value was established.
    pub confidence: EvidenceConfidence,
    /// Bridge-local observation instant.
    pub observed_at_ms: Option<MonotonicMs>,
}

/// Current bounded application ownership for one generation-scoped resource.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ResourceOwnershipSnapshot {
    /// Owned resource.
    pub resource: ResourceKey,
    /// Current owning client.
    pub client_id: ClientId,
    /// Authorizing lease.
    pub lease_id: LeaseId,
    /// Exclusive bridge-clock expiry.
    pub expires_at_ms: MonotonicMs,
}

/// Application-neutral logical controller state.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LogicalDeviceSnapshot {
    /// Logical identity.
    pub device_id: LogicalDeviceId,
    /// Device category.
    pub device_kind: DeviceKind,
    /// Observed product id.
    pub product_id: ProductId,
    /// Qualified profile when available.
    pub profile_id: Option<ProfileId>,
    /// Receiver inventory state independent of route.
    pub pairing: PairingState,
    /// Derived controller presence.
    pub presence: PresenceState,
    /// Evidence-backed support level.
    pub support_level: SupportLevel,
    /// Independent known routes in canonical endpoint order.
    pub endpoints: Vec<EndpointSnapshot>,
    /// Current battery projection.
    pub battery: BatteryObservation,
    /// Qualified semantic capabilities.
    pub capabilities: Vec<CapabilityId>,
}

/// Generation-bound receiver and child inventory.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ReceiverSnapshot {
    /// Logical receiver identity.
    pub receiver_id: ReceiverId,
    /// Current receiver generation.
    pub generation_id: GenerationId,
    /// Receiver lifecycle state.
    pub lifecycle: ReceiverLifecycleState,
    /// Independent logical children.
    pub devices: Vec<LogicalDeviceSnapshot>,
    /// Current generation-scoped write ownership.
    pub ownership: Vec<ResourceOwnershipSnapshot>,
    /// Whether stable state restoration is enabled.
    pub stable_restore_enabled: bool,
    /// Current restoration state.
    pub restore_state: RestoreState,
}

/// Sequence-bound complete bridge snapshot.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BridgeSnapshot {
    /// Complete event position reflected by this snapshot.
    pub cursor: EventCursor,
    /// Exactly one current generation per receiver in canonical order.
    pub receivers: Vec<ReceiverSnapshot>,
}

/// One logical-device direct-mode frame.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LightingFrame {
    /// Frame target.
    pub device_id: LogicalDeviceId,
    /// Transaction-local frame order.
    pub frame_index: FrameIndex,
    /// Logical LED colors before carrier translation.
    pub colors: Vec<RgbColor>,
}

/// Exact profile and lighting dimensions bound to one transaction target.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct DeviceProfileBinding {
    /// Logical transaction target.
    pub device_id: LogicalDeviceId,
    /// Qualified child profile selected at admission.
    pub profile_id: ProfileId,
    /// Immutable profile-catalog digest selected at admission.
    pub profile_digest: ProfileDigest,
    /// Exact logical color count required by this profile.
    pub application_slot_count: LedCount,
}

/// Explicit semantic stable-lighting intent for one frame target.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct StableLightingIntent {
    /// Logical stable-lighting target.
    pub device_id: LogicalDeviceId,
    /// Stable Static or Off meaning independent of RGB payload values.
    pub mode: StableLightingMode,
}

/// Atomic generation- and ownership-bound operation.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TransactionRequest {
    /// Idempotency identity.
    pub request_id: RequestId,
    /// Transaction identity.
    pub transaction_id: TransactionId,
    /// Submitting client.
    pub client_id: ClientId,
    /// Atomic ownership proof.
    pub lease_id: LeaseId,
    /// Receiver target.
    pub receiver_id: ReceiverId,
    /// Generation binding.
    pub generation_id: GenerationId,
    /// Exact qualified receiver profile selected at admission.
    pub receiver_profile_id: ProfileId,
    /// Immutable receiver profile-catalog digest selected at admission.
    pub receiver_profile_digest: ProfileDigest,
    /// Complete canonical profile binding for every frame target.
    pub device_profiles: Vec<DeviceProfileBinding>,
    /// Ordering and coalescing class.
    pub transaction_class: TransactionClass,
    /// Canonical per-target semantic intent for static-lighting; empty for every other transaction class.
    pub stable_intents: Vec<StableLightingIntent>,
    /// Absolute monotonic deadline.
    pub deadline_ms: MonotonicMs,
    /// Complete ownership set.
    pub resources: Vec<ResourceKey>,
    /// Complete atomic frame batch.
    pub frames: Vec<LightingFrame>,
}

/// Nonterminal generation-bound transaction projection.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TransactionProgress {
    /// Original idempotency identity.
    pub request_id: RequestId,
    /// Canonical request digest used for exact replay.
    pub request_digest: RequestDigest,
    /// Transaction identity.
    pub transaction_id: TransactionId,
    /// Bound receiver.
    pub receiver_id: ReceiverId,
    /// Bound receiver generation.
    pub generation_id: GenerationId,
    /// Current nonterminal state.
    pub state: TransactionState,
    /// Bounded queue decision.
    pub admission: QueueAdmission,
    /// Frames promised by the transaction.
    pub declared_frames: FrameCount,
    /// Frames terminally accepted so far.
    pub delivered_frames: DeliveredFrameCount,
    /// Current transport side-effect knowledge.
    pub side_effect_certainty: SideEffectCertainty,
    /// Whether transport has begun a hardware write.
    pub live_write_executed: bool,
}

/// Immutable terminal transaction outcome retained for bounded lookup.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TransactionTerminal {
    /// Original idempotency identity.
    pub request_id: RequestId,
    /// Canonical request digest used for exact replay.
    pub request_digest: RequestDigest,
    /// Transaction identity.
    pub transaction_id: TransactionId,
    /// Bound receiver.
    pub receiver_id: ReceiverId,
    /// Bound receiver generation.
    pub generation_id: GenerationId,
    /// Terminal succeeded, failed, revoked, or superseded state.
    pub state: TransactionState,
    /// Frames promised by the transaction.
    pub declared_frames: FrameCount,
    /// Frames terminally accepted by transport.
    pub delivered_frames: DeliveredFrameCount,
    /// Terminal transport side-effect knowledge.
    pub side_effect_certainty: SideEffectCertainty,
    /// Whether transport began a hardware write.
    pub live_write_executed: bool,
    /// Whether exact automatic replay is safe; false after possible transport.
    pub automatic_retry: bool,
    /// Separate child-application evidence.
    pub device_application: DeviceApplicationState,
    /// Immutable completion event sequence.
    pub terminal_sequence: SequenceNumber,
    /// Structured failure category.
    pub error_kind: Option<ProtocolErrorKind>,
    /// Newer unsent effect transaction that replaced this one.
    pub superseded_by: Option<TransactionId>,
}

/// Outcome lookup cannot return a retained transaction record.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TransactionUnavailable {
    /// Requested transaction identity.
    pub transaction_id: TransactionId,
    /// Unknown or evicted outcome category.
    pub error_kind: ProtocolErrorKind,
    /// Central error catalog reference.
    pub finding_id: FindingId,
}

/// Idempotent lookup of one previously submitted transaction.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TransactionLookup {
    /// Lookup request identity.
    pub request_id: RequestId,
    /// Original transaction owner.
    pub client_id: ClientId,
    /// Transaction to inspect.
    pub transaction_id: TransactionId,
}

/// Bounded event subscription cursor.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SubscriptionRequest {
    /// Subscribing client.
    pub client_id: ClientId,
    /// Server-issued subscription identity when continuing.
    pub subscription_id: Option<SubscriptionId>,
    /// Previously observed complete event cursor.
    pub expected_cursor: Option<EventCursor>,
    /// Maximum events requested in this batch.
    pub max_events: EventBatchLimit,
}

/// Sequence-bound typed event with snapshot references.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BridgeEvent {
    /// Strictly increasing sequence.
    pub sequence: SequenceNumber,
    /// Typed event category.
    pub kind: EventKind,
    /// Affected receiver when applicable.
    pub receiver_id: Option<ReceiverId>,
    /// Affected generation when applicable.
    pub generation_id: Option<GenerationId>,
    /// Affected logical device when applicable.
    pub device_id: Option<LogicalDeviceId>,
    /// Affected lease when applicable.
    pub lease_id: Option<LeaseId>,
    /// Affected transaction when applicable.
    pub transaction_id: Option<TransactionId>,
    /// Affected finding when applicable.
    pub finding_id: Option<FindingId>,
}

/// Bounded event result with explicit cursor-gap state.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct EventBatch {
    /// Subscription identity.
    pub subscription_id: SubscriptionId,
    /// Cursor to supply for the next batch.
    pub next_cursor: EventCursor,
    /// Events after the requested cursor.
    pub events: Vec<BridgeEvent>,
    /// Oldest retained sequence.
    pub oldest_available: SequenceNumber,
    /// Newest retained sequence.
    pub latest_available: SequenceNumber,
    /// Events evicted since this stream epoch began.
    pub dropped_events: DroppedEventCount,
    /// Whether the client must refresh its snapshot.
    pub cursor_gap: bool,
    /// Whether another retained event follows this batch.
    pub has_more: bool,
}

/// One privacy-classified actionable finding.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct DiagnosticFinding {
    /// Stable finding code.
    pub finding_id: FindingId,
    /// User-facing severity.
    pub severity: ErrorSeverity,
    /// Bounded technical cause.
    pub cause: HumanMessage,
    /// Plain user explanation.
    pub explanation: HumanMessage,
    /// One safe remediation.
    pub safe_action: HumanMessage,
    /// Support-output privacy class.
    pub privacy: PrivacyClass,
    /// Stable documentation path.
    pub documentation: DocumentationPath,
}

/// Bounded bridge findings and queue health.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct DiagnosticSnapshot {
    /// Latest reflected event sequence.
    pub sequence: SequenceNumber,
    /// Active actionable findings.
    pub findings: Vec<DiagnosticFinding>,
    /// Configured event bound.
    pub event_buffer_capacity: QueueCapacity,
    /// Configured transaction bound.
    pub transaction_queue_capacity: QueueCapacity,
}

/// Stable structured request failure.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RpcError {
    /// Related request when parsing reached it.
    pub request_id: Option<RequestId>,
    /// Machine-readable failure class.
    pub kind: ProtocolErrorKind,
    /// Bounded user-safe explanation.
    pub message: HumanMessage,
    /// Diagnostic catalog reference.
    pub finding_id: FindingId,
}

/// Contradiction-free atomic lease outcome.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(tag = "outcome", content = "detail")]
pub enum LeaseResult {
    /// Every requested resource was granted.
    #[serde(rename = "granted")]
    Granted(LeaseGrant),
    /// Another client owns at least one requested resource; none were granted.
    #[serde(rename = "conflict")]
    Conflict(LeaseConflict),
    /// The request failed without granting any resource.
    #[serde(rename = "rejected")]
    Rejected(LeaseRejection),
}

/// Contradiction-free current, terminal, or unavailable transaction outcome.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(tag = "outcome", content = "detail")]
pub enum TransactionResult {
    /// The transaction has not reached a terminal state.
    #[serde(rename = "progress")]
    Progress(TransactionProgress),
    /// The immutable terminal outcome is retained.
    #[serde(rename = "terminal")]
    Terminal(TransactionTerminal),
    /// No retained outcome can answer this lookup.
    #[serde(rename = "unavailable")]
    Unavailable(TransactionUnavailable),
}

/// Unnegotiated request envelope used only for the handshake.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NegotiationRequestEnvelope {
    pub request_id: RequestId,
    pub params: ClientHello,
}

/// Request envelope bound to one negotiated bridge connection.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SessionRequestEnvelope<T> {
    pub request_id: RequestId,
    pub protocol_session_id: ProtocolSessionId,
    pub negotiation_token: NegotiationToken,
    pub params: T,
}

/// Typed request envelope; arbitrary method strings or parameters are impossible.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(tag = "method", content = "request")]
pub enum RpcRequest {
    #[serde(rename = "negotiate")]
    Negotiate(NegotiationRequestEnvelope),
    #[serde(rename = "snapshot")]
    Snapshot(SessionRequestEnvelope<EmptyRequest>),
    #[serde(rename = "acquire-lease")]
    AcquireLease(SessionRequestEnvelope<LeaseRequest>),
    #[serde(rename = "renew-lease")]
    RenewLease(SessionRequestEnvelope<RenewLeaseRequest>),
    #[serde(rename = "release-lease")]
    ReleaseLease(SessionRequestEnvelope<ReleaseLeaseRequest>),
    #[serde(rename = "submit-transaction")]
    SubmitTransaction(SessionRequestEnvelope<TransactionRequest>),
    #[serde(rename = "transaction-outcome")]
    TransactionOutcome(SessionRequestEnvelope<TransactionLookup>),
    #[serde(rename = "subscribe")]
    Subscribe(SessionRequestEnvelope<SubscriptionRequest>),
    #[serde(rename = "diagnostics")]
    Diagnostics(SessionRequestEnvelope<EmptyRequest>),
}

/// Successful method response bound to the serving bridge instance.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SuccessEnvelope<T> {
    pub request_id: RequestId,
    pub server_instance_id: ServerInstanceId,
    pub result: T,
}

/// Structured error response bound to the serving bridge instance.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ErrorEnvelope {
    pub request_id: Option<RequestId>,
    pub server_instance_id: ServerInstanceId,
    pub error: RpcError,
}

/// Typed success-or-error response envelope.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(tag = "type", content = "response")]
pub enum RpcResponse {
    #[serde(rename = "negotiate-success")]
    NegotiateSuccess(SuccessEnvelope<ServerHello>),
    #[serde(rename = "snapshot-success")]
    SnapshotSuccess(SuccessEnvelope<BridgeSnapshot>),
    #[serde(rename = "acquire-lease-success")]
    AcquireLeaseSuccess(SuccessEnvelope<LeaseResult>),
    #[serde(rename = "renew-lease-success")]
    RenewLeaseSuccess(SuccessEnvelope<LeaseResult>),
    #[serde(rename = "release-lease-success")]
    ReleaseLeaseSuccess(SuccessEnvelope<LeaseResult>),
    #[serde(rename = "submit-transaction-success")]
    SubmitTransactionSuccess(SuccessEnvelope<TransactionResult>),
    #[serde(rename = "transaction-outcome-success")]
    TransactionOutcomeSuccess(SuccessEnvelope<TransactionResult>),
    #[serde(rename = "subscribe-success")]
    SubscribeSuccess(SuccessEnvelope<EventBatch>),
    #[serde(rename = "diagnostics-success")]
    DiagnosticsSuccess(SuccessEnvelope<DiagnosticSnapshot>),
    #[serde(rename = "error")]
    Error(ErrorEnvelope),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct MethodDescriptor {
    pub name: &'static str,
    pub request: &'static str,
    pub response: &'static str,
    pub required_feature: Option<&'static str>,
}

pub const METHODS: &[MethodDescriptor] = &[
    MethodDescriptor {
        name: "negotiate",
        request: "ClientHello",
        response: "ServerHello",
        required_feature: None,
    },
    MethodDescriptor {
        name: "snapshot",
        request: "EmptyRequest",
        response: "BridgeSnapshot",
        required_feature: None,
    },
    MethodDescriptor {
        name: "acquire-lease",
        request: "LeaseRequest",
        response: "LeaseResult",
        required_feature: Some("ownership-leases"),
    },
    MethodDescriptor {
        name: "renew-lease",
        request: "RenewLeaseRequest",
        response: "LeaseResult",
        required_feature: Some("ownership-leases"),
    },
    MethodDescriptor {
        name: "release-lease",
        request: "ReleaseLeaseRequest",
        response: "LeaseResult",
        required_feature: Some("ownership-leases"),
    },
    MethodDescriptor {
        name: "submit-transaction",
        request: "TransactionRequest",
        response: "TransactionResult",
        required_feature: Some("atomic-transactions"),
    },
    MethodDescriptor {
        name: "transaction-outcome",
        request: "TransactionLookup",
        response: "TransactionResult",
        required_feature: Some("atomic-transactions"),
    },
    MethodDescriptor {
        name: "subscribe",
        request: "SubscriptionRequest",
        response: "EventBatch",
        required_feature: Some("event-subscriptions"),
    },
    MethodDescriptor {
        name: "diagnostics",
        request: "EmptyRequest",
        response: "DiagnosticSnapshot",
        required_feature: Some("structured-diagnostics"),
    },
];

impl RpcRequest {
    /// Returns the request identity carried by every method envelope.
    #[must_use]
    pub fn request_id(&self) -> &RequestId {
        match self {
            Self::Negotiate(envelope) => &envelope.request_id,
            Self::Snapshot(envelope) | Self::Diagnostics(envelope) => &envelope.request_id,
            Self::AcquireLease(envelope) => &envelope.request_id,
            Self::RenewLease(envelope) => &envelope.request_id,
            Self::ReleaseLease(envelope) => &envelope.request_id,
            Self::SubmitTransaction(envelope) => &envelope.request_id,
            Self::TransactionOutcome(envelope) => &envelope.request_id,
            Self::Subscribe(envelope) => &envelope.request_id,
        }
    }

    /// Returns the generated descriptor for this request variant.
    #[must_use]
    pub const fn method_descriptor(&self) -> &'static MethodDescriptor {
        match self {
            Self::Negotiate(_) => &METHODS[0],
            Self::Snapshot(_) => &METHODS[1],
            Self::AcquireLease(_) => &METHODS[2],
            Self::RenewLease(_) => &METHODS[3],
            Self::ReleaseLease(_) => &METHODS[4],
            Self::SubmitTransaction(_) => &METHODS[5],
            Self::TransactionOutcome(_) => &METHODS[6],
            Self::Subscribe(_) => &METHODS[7],
            Self::Diagnostics(_) => &METHODS[8],
        }
    }

    /// Returns negotiated connection credentials for session-bound methods.
    #[must_use]
    pub fn session_credentials(&self) -> Option<(&ProtocolSessionId, &NegotiationToken)> {
        match self {
            Self::Negotiate(_) => None,
            Self::Snapshot(envelope) | Self::Diagnostics(envelope) => {
                Some((&envelope.protocol_session_id, &envelope.negotiation_token))
            }
            Self::AcquireLease(envelope) => {
                Some((&envelope.protocol_session_id, &envelope.negotiation_token))
            }
            Self::RenewLease(envelope) => {
                Some((&envelope.protocol_session_id, &envelope.negotiation_token))
            }
            Self::ReleaseLease(envelope) => {
                Some((&envelope.protocol_session_id, &envelope.negotiation_token))
            }
            Self::SubmitTransaction(envelope) => {
                Some((&envelope.protocol_session_id, &envelope.negotiation_token))
            }
            Self::TransactionOutcome(envelope) => {
                Some((&envelope.protocol_session_id, &envelope.negotiation_token))
            }
            Self::Subscribe(envelope) => {
                Some((&envelope.protocol_session_id, &envelope.negotiation_token))
            }
        }
    }
}
